-- Independent boundary holdout; contract and own baseline fixture shapes only.
begin;
set local role postgres;
set local search_path to public, extensions;
select plan(23);
create function pg_temp.u(n integer) returns uuid language sql immutable as $$select ('74910000-0000-4000-8000-'||lpad(to_hex(n),12,'0'))::uuid$$;
create function pg_temp.sc(n integer default 1) returns text language sql as $$select jsonb_build_object('sub',pg_temp.u(200+n),'role','authenticated','tenant_id',pg_temp.u(1),'staff_id',pg_temp.u(200+n),'app_role',case n when 1 then 'gym_owner' when 2 then 'gym_manager' else 'front_desk' end)::text$$;
create function pg_temp.run(q text,c text default pg_temp.sc(),r text default 'authenticated') returns jsonb language plpgsql as $$declare v jsonb;begin perform set_config('request.jwt.claims',coalesce(c,''),true);execute format('set local role %I',r);begin execute q into v;exception when others then v:=jsonb_build_object('error',sqlstate);end;set local role postgres;perform set_config('request.jwt.claims','',true);return coalesce(v,'null'::jsonb);end$$;
insert into public.organizations(id,name,gym_code,status,timezone,currency)values(pg_temp.u(1),'Boundary gym','H74TBA','active','Pacific/Kiritimati','INR');
insert into public.organization_settings(tenant_id)values(pg_temp.u(1));
insert into public.branches(id,tenant_id,name,timezone,is_default)values(pg_temp.u(11),pg_temp.u(1),'Branch','Pacific/Honolulu',true);
insert into auth.users(id)select pg_temp.u(n)from generate_series(201,203)n;
insert into public.staff(id,user_id,tenant_id,role,full_name,is_active)select pg_temp.u(200+n),pg_temp.u(200+n),pg_temp.u(1),case n when 1 then 'gym_owner'::public.app_role when 2 then 'gym_manager'::public.app_role else 'front_desk'::public.app_role end,'Boundary staff',true from generate_series(1,3)n;
create function pg_temp.day() returns date language sql stable as $$select (statement_timestamp()at time zone 'Pacific/Honolulu')::date+2$$;
insert into public.services(id,tenant_id,name,default_duration_minutes,default_capacity)values(pg_temp.u(600),pg_temp.u(1),'Boundary class',60,5);
insert into public.class_sessions(id,tenant_id,service_id,branch_id,session_date,starts_at,ends_at,capacity)values(pg_temp.u(700),pg_temp.u(1),pg_temp.u(600),pg_temp.u(11),pg_temp.day(),(pg_temp.day()+time '12:00')at time zone 'Pacific/Honolulu',(pg_temp.day()+time '13:00')at time zone 'Pacific/Honolulu',5);
create temp table original as select to_jsonb(s)facts from public.class_sessions s where id=pg_temp.u(700);
create temp table effects as select (select count(*)from public.class_rules where tenant_id=pg_temp.u(1))rules,(select count(*)from public.class_sessions where tenant_id=pg_temp.u(1))sessions,(select count(*)from public.audit_log where tenant_id=pg_temp.u(1))audits,(select count(*)from public.notifications where tenant_id=pg_temp.u(1))notices;
select is(pg_temp.run($q$select to_jsonb(g)from public.create_class_rules(pg_temp.u(600),pg_temp.u(11),array[0,3]::smallint[],time '24:00',60,5,null,pg_temp.day(),null)g$q$,pg_temp.sc(1))->>'error','22023','CLS boundary command 1 actor 1 refusal');
select is(pg_temp.run($q$select to_jsonb(g)from public.create_class_rules(pg_temp.u(600),pg_temp.u(11),array[0,3]::smallint[],time '24:00',60,5,null,pg_temp.day(),null)g$q$,pg_temp.sc(2))->>'error','22023','CLS boundary command 1 actor 2 refusal');
select is(pg_temp.run($q$select to_jsonb(g)from public.create_class_rules(pg_temp.u(600),pg_temp.u(11),array[0,3]::smallint[],time '24:00',60,5,null,pg_temp.day(),null)g$q$,pg_temp.sc(3))->>'error','42501','CLS boundary command 1 actor 3 refusal');
select is(pg_temp.run($q$select to_jsonb(public.create_class_session(pg_temp.u(600),pg_temp.u(11),pg_temp.day(),time '24:00',60,5,null))$q$,pg_temp.sc(1))->>'error','22023','CLS boundary command 2 actor 1 refusal');
select is(pg_temp.run($q$select to_jsonb(public.create_class_session(pg_temp.u(600),pg_temp.u(11),pg_temp.day(),time '24:00',60,5,null))$q$,pg_temp.sc(2))->>'error','22023','CLS boundary command 2 actor 2 refusal');
select is(pg_temp.run($q$select to_jsonb(public.create_class_session(pg_temp.u(600),pg_temp.u(11),pg_temp.day(),time '24:00',60,5,null))$q$,pg_temp.sc(3))->>'error','42501','CLS boundary command 2 actor 3 refusal');
select is(pg_temp.run($q$select to_jsonb(public.update_class_session(pg_temp.u(700),pg_temp.day(),time '24:00',60,5,null))$q$,pg_temp.sc(1))->>'error','22023','CLS boundary command 3 actor 1 refusal');
select is(pg_temp.run($q$select to_jsonb(public.update_class_session(pg_temp.u(700),pg_temp.day(),time '24:00',60,5,null))$q$,pg_temp.sc(2))->>'error','22023','CLS boundary command 3 actor 2 refusal');
select is(pg_temp.run($q$select to_jsonb(public.update_class_session(pg_temp.u(700),pg_temp.day(),time '24:00',60,5,null))$q$,pg_temp.sc(3))->>'error','42501','CLS boundary command 3 actor 3 refusal');
select is((select to_jsonb(s)from public.class_sessions s where id=pg_temp.u(700)),(select facts from original),'CLS refusal leaves edited session byte-for-byte intact');
select ok((select rules=(select count(*)from public.class_rules where tenant_id=pg_temp.u(1))and sessions=(select count(*)from public.class_sessions where tenant_id=pg_temp.u(1))and audits=(select count(*)from public.audit_log where tenant_id=pg_temp.u(1))and notices=(select count(*)from public.notifications where tenant_id=pg_temp.u(1))from effects),'CLS rejected starts have no rules sessions audit or notices');
create temp table results(k text primary key,v jsonb);
grant select on results to authenticated;
insert into results values('midnight',pg_temp.run($q$select to_jsonb(public.create_class_session(pg_temp.u(600),pg_temp.u(11),pg_temp.day(),time '00:00:00',60,5,null))$q$));
select is((select v->>'error'from results where k='midnight'),null::text,'CLS midnight start accepted');
select ok(exists(select 1 from public.class_sessions where id=(select (v#>>'{}')::uuid from results where k='midnight'and v->>'error'is null)and session_date=pg_temp.day()and (starts_at at time zone 'Pacific/Honolulu')::date=session_date),'CLS midnight stores resolved branch date');
insert into results values('last',pg_temp.run($q$select to_jsonb(public.create_class_session(pg_temp.u(600),pg_temp.u(11),pg_temp.day(),time '23:59:59.999999',60,5,null))$q$));
select is((select v->>'error'from results where k='last'),null::text,'CLS last start accepted');
select ok(exists(select 1 from public.class_sessions where id=(select (v#>>'{}')::uuid from results where k='last'and v->>'error'is null)and session_date=pg_temp.day()and (starts_at at time zone 'Pacific/Honolulu')::date=session_date),'CLS last stores resolved branch date');
select ok(exists(select 1 from public.class_sessions where id=(select (v#>>'{}')::uuid from results where k='last'and v->>'error'is null)and (ends_at at time zone 'Pacific/Honolulu')::date=session_date+1),'CLS crossing midnight end preserves start-day identity');
insert into results values('rule',pg_temp.run($q$select to_jsonb(g)from public.create_class_rules(pg_temp.u(600),pg_temp.u(11),array[extract(dow from pg_temp.day())::smallint],time '04:10',60,5,null,pg_temp.day(),pg_temp.day())g$q$));
select is((select v->>'error'from results where k='rule'),null::text,'CLS ordinary rule accepted');
select is(pg_temp.run($q$select to_jsonb(public.update_class_session((select id from public.class_sessions where rule_id=(select (v->>'rule_id')::uuid from results where k='rule')),pg_temp.day()+1,time '04:10',60,5,null))$q$)->>'error','22023','CLS explicit rule edit cannot move calendar day');
select ok(not exists(select 1 from public.class_sessions where tenant_id=pg_temp.u(1)and rule_id is not null and(session_date<>pg_temp.day()or session_date<>(starts_at at time zone 'Pacific/Honolulu')::date)),'CLS rule identity and resolved branch date agree');
select is(app.class_local_instant('America/New_York',date '2027-03-14',time '02:30'),timestamptz '2027-03-14 07:30:00+00','CLS normal DST spring gap PostgreSQL resolution preserved');
select is(app.class_local_instant('America/New_York',date '2027-11-07',time '01:30'),timestamptz '2027-11-07 06:30:00+00','CLS normal DST overlap PostgreSQL resolution preserved');
-- The real whole-date shift in Pacific/Apia occurred 2011-12-30, outside today's
-- fixed generation horizon. No clock substitution or generator replacement is used.
insert into public.services(id,tenant_id,name,default_duration_minutes,default_capacity)values(pg_temp.u(601),pg_temp.u(1),'Legacy generator boundary',60,5);
insert into public.class_rules(id,tenant_id,service_id,branch_id,weekday,start_time,duration_minutes,capacity,valid_from,valid_until)values(pg_temp.u(620),pg_temp.u(1),pg_temp.u(601),pg_temp.u(11),extract(dow from pg_temp.day())::smallint,time '24:00',60,5,pg_temp.day(),pg_temp.day());
select is(pg_temp.run($q$select to_jsonb(app.generate_class_sessions(pg_temp.u(1),pg_temp.u(620),null))$q$,'','postgres')->>'error',null::text,'CLS generator does not raise on shifted legacy wall-time date');
select is((select count(*)from public.class_sessions where rule_id=pg_temp.u(620)),0::bigint,'CLS generator skips shifted next-day occurrence entirely');
select * from finish();
rollback;
