import { beforeEach, describe, expect, it, vi } from 'vitest';
import type { Session } from '@supabase/supabase-js';
import type { GymloopIdentity } from '@gymloop/shared';
const harness = vi.hoisted(() => ({ slots: [] as unknown[], cursor: 0, effects: [] as Array<() => void | (() => void)>, cleanups: [] as Array<() => void>, value: null as unknown, listener: null as null | ((event: string, session: Session | null) => void), session: null as Session | null, identity: { kind: 'unlinked' } as GymloopIdentity, resolving: null as Promise<void> | null, cleanup: null as Promise<void> | null, cleanupCalls: 0, tokenGate: null as Promise<void> | null, fetch: vi.fn(), logout: vi.fn() }));
vi.mock('react', () => {
  const state = (initial: unknown) => { const index = harness.cursor++; if (!(index in harness.slots)) harness.slots[index] = typeof initial === 'function' ? (initial as () => unknown)() : initial; return [harness.slots[index], (value: unknown) => { harness.slots[index] = typeof value === 'function' ? (value as (old: unknown) => unknown)(harness.slots[index]) : value; }]; };
  const react = { createContext: () => { const context = ({ value }: { value: unknown }) => { harness.value = value; return null; }; return Object.assign(context, { Provider: context }); }, useContext: () => harness.value, useState: state, useRef: (initial: unknown) => state({ current: initial })[0], useMemo: (fn: () => unknown) => fn(), useCallback: (fn: unknown) => fn, useEffect: (fn: () => void | (() => void), deps: unknown[]) => { const index = harness.cursor++; const prior = harness.slots[index] as unknown[] | undefined; if (!prior || deps.some((value, position) => value !== prior[position])) { harness.slots[index] = deps; harness.effects.push(fn); } } };
  return { ...react, default: react };
});
vi.mock('react/jsx-runtime', () => ({ jsx: (type: unknown, props: unknown) => typeof type === 'function' ? (type as (props: unknown) => unknown)(props) : null, jsxs: (type: unknown, props: unknown) => typeof type === 'function' ? (type as (props: unknown) => unknown)(props) : null }));
vi.mock('react-native', () => ({ StatusBar: () => null, View: () => null, useColorScheme: () => 'light', AppState: { addEventListener: () => ({ remove: vi.fn() }) } }));
vi.mock('@expo-google-fonts/archivo', () => ({ useFonts: () => [true], Archivo_400Regular: 1, Archivo_500Medium: 1, Archivo_600SemiBold: 1, Archivo_700Bold: 1 }));
vi.mock('../../apps/mobile/assets/fonts/ArchivoExtraCondensed-ExtraBold.ttf', () => ({ default: 1 }));
vi.mock('../../apps/mobile/assets/fonts/ArchivoExtraCondensed-Bold.ttf', () => ({ default: 1 }));
vi.mock('expo-splash-screen', () => ({ preventAutoHideAsync: vi.fn(async () => undefined), hideAsync: vi.fn(async () => undefined) }));
vi.mock('expo-secure-store', () => ({ getItemAsync: vi.fn(async () => null), setItemAsync: vi.fn(), deleteItemAsync: vi.fn() }));
vi.mock('@gymloop/shared', async (original) => ({ ...await original<object>(), mobileClientEnv: () => ({ EXPO_PUBLIC_SUPABASE_URL: 'https://example.supabase.co', EXPO_PUBLIC_SUPABASE_ANON_KEY: 'public-test', EXPO_PUBLIC_API_BASE_URL: 'https://example.test', EXPO_PUBLIC_WEB_URL: 'https://example.test' }) }));
vi.mock('../../apps/mobile/lib/native-session', () => ({ createMobileSupabase: () => ({ from: () => ({ select: () => ({ eq: () => ({ maybeSingle: async () => ({ data: { business_type: 'gym' }, error: null }) }) }) }), auth: { getSession: async () => { if (harness.tokenGate) await harness.tokenGate; return { data: { session: harness.session }, error: null }; }, onAuthStateChange: (listener: typeof harness.listener) => { harness.listener = listener; return { data: { subscription: { unsubscribe: vi.fn() } } }; } } }), resolveNativeMobileSession: async () => { const identity = harness.identity; if (harness.resolving) await harness.resolving; return { identity, queueScope: identity.kind === 'member' ? identity : null, replay: 'ready' }; }, signOutMobile: () => harness.logout() }));
vi.mock('../../apps/mobile/lib/offline-check-in', () => ({ clearOfflineCheckIns: vi.fn(async () => undefined) }));
vi.mock('../../apps/mobile/lib/shop-cache', () => ({ clearShopCache: vi.fn(async () => { harness.cleanupCalls += 1; if (harness.cleanup) await harness.cleanup; }) }));
vi.mock('../../apps/mobile/lib/announcements', () => ({ clearAnnouncementCache: vi.fn(async () => { harness.cleanupCalls += 1; if (harness.cleanup) await harness.cleanup; }) }));
import { MobileProvider, useMobile } from '../../apps/mobile/lib/mobile-context';
function render() { harness.cursor = 0; const tree = MobileProvider({ children: null }); const visit = (node: unknown): void => { if (!node || typeof node !== 'object') return; const item = node as { type?: unknown; props?: { children?: unknown; value?: unknown } }; if (item.props && 'value' in item.props) harness.value = item.props.value; if (item.props?.children) { if (Array.isArray(item.props.children)) item.props.children.forEach(visit); else visit(item.props.children); } }; visit(tree); const effects = harness.effects.splice(0); for (const effect of effects) { const cleanup = effect(); if (cleanup) harness.cleanups.push(cleanup); } }
async function settle() { for (let turn = 0; turn < 20; turn += 1) { await Promise.resolve(); render(); } }
function deferred() { let resolve!: () => void; const promise = new Promise<void>((done) => { resolve = done; }); return { promise, resolve }; }
function setOwner(suffix: string) { harness.identity = { kind: 'member', userId: `20000000-0000-4000-8000-00000000000${suffix}`, tenantId: '10000000-0000-4000-8000-000000000001', memberId: `30000000-0000-4000-8000-00000000000${suffix}` }; harness.session = { access_token: `jwt-${suffix}` } as Session; }
beforeEach(() => { harness.slots = []; harness.cursor = 0; harness.effects = []; harness.cleanups = []; harness.listener = null; harness.resolving = null; harness.cleanup = null; harness.cleanupCalls = 0; harness.tokenGate = null; harness.logout.mockReset().mockResolvedValue(undefined); harness.fetch.mockReset().mockResolvedValue({ json: async () => ({ ok: true, data: {} }) }); vi.stubGlobal('fetch', harness.fetch); setOwner('1'); });
describe('independent native caller capability lifetime', () => {
  it('revokes the old capability immediately while replacement claims wait', async () => { render(); await settle(); const api = useMobile().api; const gate = deferred(); harness.resolving = gate.promise; setOwner('2'); harness.listener!('SIGNED_IN', harness.session); await api.post('/invites/accept', {}).catch(() => undefined); expect(harness.fetch).not.toHaveBeenCalled(); gate.resolve(); await settle(); await useMobile().api.post('/invites/accept', {}); expect(harness.fetch).toHaveBeenCalled(); });
  it('does not let suspended old token acquisition borrow replacement JWT', async () => { render(); await settle(); const gate = deferred(); harness.tokenGate = gate.promise; const request = useMobile().api.post('/shop/catalogue', {}).catch(() => undefined); setOwner('2'); harness.listener!('SIGNED_IN', harness.session); gate.resolve(); await request; expect(harness.fetch).not.toHaveBeenCalled(); });
  it('never revives an A capability across A to B to A', async () => { render(); await settle(); const api = useMobile().api; setOwner('2'); harness.listener!('SIGNED_IN', harness.session); await settle(); setOwner('1'); harness.listener!('SIGNED_IN', harness.session); await settle(); await api.post('/shop/catalogue', {}).catch(() => undefined); expect(harness.fetch).not.toHaveBeenCalled(); });
  it('revokes on provider teardown', async () => { render(); await settle(); const api = useMobile().api; for (const cleanup of harness.cleanups) cleanup(); await api.post('/shop/catalogue', {}).catch(() => undefined); expect(harness.fetch).not.toHaveBeenCalled(); });
  it('attempts Auth logout when private cleanup fails', async () => { render(); await settle(); harness.cleanup = Promise.reject(new Error('private delete failed')); void harness.cleanup.catch(() => undefined); await useMobile().signOut().catch(() => undefined); expect(harness.cleanupCalls).toBeGreaterThan(0); expect(harness.logout).toHaveBeenCalled(); });
  it('holds another verified caller behind pending privacy cleanup', async () => { render(); await settle(); const gate = deferred(); harness.cleanup = gate.promise; setOwner('2'); harness.listener!('SIGNED_IN', harness.session); await settle(); expect(useMobile().identity).not.toEqual(harness.identity); gate.resolve(); await settle(); expect(useMobile().identity).toEqual(harness.identity); });
  it('revokes on signout before pending private deletion finishes', async () => { render(); await settle(); const api = useMobile().api; const gate = deferred(); harness.cleanup = gate.promise; const signingOut = useMobile().signOut().catch(() => undefined); await api.post('/shop/catalogue', {}).catch(() => undefined); expect(harness.fetch).not.toHaveBeenCalled(); gate.resolve(); await signingOut; });
  it('blocks new owner publication when private deletion fails', async () => { render(); await settle(); harness.cleanup = Promise.reject(new Error('privacy failure')); void harness.cleanup.catch(() => undefined); setOwner('2'); harness.listener!('SIGNED_IN', harness.session); await settle(); expect(useMobile().identity).not.toEqual(harness.identity); });
  it('keeps authenticated unlinked invite recovery usable', async () => { harness.identity = { kind: 'unlinked' }; render(); await settle(); await useMobile().api.post('/invites/accept', {}); expect(harness.fetch).toHaveBeenCalled(); });
});
