-- Phase 6 metrics callable/security boundary; deliberately implementation-blind.
begin;
set local role postgres;
set local search_path = extensions, public;
select set_config('request.jwt.claims','',true);
select plan(22);
select has_function('public','owner_metrics',array['date','date']::name[],'MET-001 exact owner signature');
select has_function('app','gym_metrics',array['uuid','timestamp with time zone','date','date']::name[],'MET-002 exact shared signature');
select has_function('public','fleet_metrics',array[]::name[],'OPS-001 fleet has no parameters');
select has_function('app','gym_readiness',array['uuid']::name[],'OPS-004 exact readiness signature');
select ok((select prorettype='jsonb'::regtype and provolatile='s' and not prosecdef and proconfig @> array['search_path=""'] from pg_proc where oid=to_regprocedure('public.owner_metrics(date,date)')),'MET-001 owner is stable invoker and empty-path');
select ok((select prorettype='jsonb'::regtype and provolatile='s' and not prosecdef and proconfig @> array['search_path=""'] from pg_proc where oid=to_regprocedure('app.gym_metrics(uuid,timestamptz,date,date)')),'MET-002 helper is stable invoker and empty-path');
select ok((select prorettype='jsonb'::regtype and provolatile='s' and not prosecdef and proconfig @> array['search_path=""'] from pg_proc where oid=to_regprocedure('public.fleet_metrics()')),'OPS-001 fleet is stable invoker and empty-path');
select ok((select prorettype='jsonb'::regtype and provolatile='s' and prosecdef and proconfig @> array['search_path=""'] from pg_proc where oid=to_regprocedure('app.gym_readiness(uuid)')),'OPS-004 readiness is stable definer and empty-path');
select ok((select has_function_privilege('authenticated',oid,'EXECUTE') and not has_function_privilege('anon',oid,'EXECUTE') from pg_proc where oid=to_regprocedure('public.owner_metrics(date,date)')),'owner execute is authenticated-only');
select ok((select has_function_privilege('authenticated',oid,'EXECUTE') and not has_function_privilege('anon',oid,'EXECUTE') from pg_proc where oid=to_regprocedure('app.gym_metrics(uuid,timestamptz,date,date)')),'helper execute is authenticated-only');
select ok((select has_function_privilege('authenticated',oid,'EXECUTE') and not has_function_privilege('anon',oid,'EXECUTE') from pg_proc where oid=to_regprocedure('public.fleet_metrics()')),'fleet execute is authenticated-only');
select ok((select has_function_privilege('authenticated',oid,'EXECUTE') and not has_function_privilege('anon',oid,'EXECUTE') from pg_proc where oid=to_regprocedure('app.gym_readiness(uuid)')),'readiness execute is authenticated-only');
set local role authenticated;
select throws_ok($$select public.owner_metrics(null,null)$$,'42501','MET-001 claimless owner caller is refused');
select throws_ok($$select public.fleet_metrics()$$,'42501','OPS-001 claimless fleet caller is refused');
select throws_ok($$select public.owner_metrics(current_date,null)$$,'22023','MET-003 half range is rejected');
select throws_ok($$select public.owner_metrics(null,current_date)$$,'22023','MET-003 other half range is rejected');
select throws_ok($$select public.owner_metrics(current_date,current_date-1)$$,'22023','MET-003 reversed range is rejected');
select set_config('request.jwt.claims','{"sub":"34000000-0000-4000-8000-000000000901","role":"authenticated","app_role":"member","tenant_id":"34000000-0000-4000-8000-000000000001","member_id":"34000000-0000-4000-8000-000000000031"}',true);
select throws_ok($$select public.owner_metrics(null,null)$$,'42501','MET-001 member role is refused before lookup');
select throws_ok($$select public.fleet_metrics()$$,'42501','OPS-001 gym identity cannot read fleet');
select is(app.gym_metrics('34000000-0000-4000-8000-000000000001','2026-09-15 18:30+00','2026-09-15','2026-09-15'),null::jsonb,'MET-002 unreadable helper target is SQL NULL');
select is(app.gym_readiness('34000000-0000-4000-8000-000000000001'),null::jsonb,'OPS-004 unreadable readiness target is SQL NULL');
select set_config('request.jwt.claims','{"sub":"34000000-0000-4000-8000-000000000902","role":"authenticated","app_role":"super_admin"}',true);
select throws_ok($$select public.owner_metrics(null,null)$$,'42501','MET-001 platform identity does not collide with owner access');
select * from finish();
rollback;
