-- BIZ-001..008, independent visible author; frozen proposal and biz bar only.
-- No implementation or holdout read. Actual concurrent owners require the
-- post-CI two-caller proof; this rollback file pins sequential locking outcomes.
begin;
set local role postgres;
set local search_path=extensions,public;
select set_config('request.jwt.claims','',true);
select plan(61);
create function pg_temp.bid(n integer) returns uuid language sql immutable as
$$ select ('70000000-0000-4000-8000-'||lpad(n::text,12,'0'))::uuid $$;
create function pg_temp.biz_claim(r text,s integer default 21,u integer default 901,t integer default 1,p boolean default false) returns void language plpgsql as $$
begin perform set_config('request.jwt.claims',jsonb_strip_nulls(jsonb_build_object('sub',pg_temp.bid(u),'role','authenticated','app_role',r,'staff_id',case when s is not null then pg_temp.bid(s) end,'tenant_id',case when t is not null then pg_temp.bid(t) end,'member_id',case when r='member' then pg_temp.bid(101) end,'impersonation_session_id',case when p then pg_temp.bid(999) end))::text,true); end $$;
create function pg_temp.biz_refuse(q text,with_detail boolean default false) returns text language plpgsql as $$
declare detail text;
begin begin execute q; raise exception using errcode='Z7000'; exception when others then if sqlstate='Z7000' then return 'SUCCESS'; end if; get stacked diagnostics detail=PG_EXCEPTION_DETAIL; return sqlstate||case when with_detail then ':'||coalesce(detail,'') else '' end; end; end $$;
grant execute on function pg_temp.bid(integer),pg_temp.biz_claim(text,integer,integer,integer,boolean),pg_temp.biz_refuse(text,boolean) to authenticated,anon,service_role;
select enum_has_labels('public','business_type',array['gym','dance','yoga','martial_arts','studio']::name[],'BIZ-001: five canonical verticals in order');
select col_type_is('public','organizations','business_type','business_type','BIZ-001: type is a Postgres enum');
select col_not_null('public','organizations','business_type','BIZ-001: every organization has a value');
select ok((select pg_get_expr(d.adbin,d.adrelid) like '%gym%' from pg_attrdef d join pg_attribute a on a.attrelid=d.adrelid and a.attnum=d.adnum where a.attrelid='public.organizations'::regclass and a.attname='business_type'),'BIZ-001: default gym');
select is_empty($q$select c.relname from pg_attribute a join pg_class c on c.oid=a.attrelid join pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and c.relkind in('r','p') and a.attname='business_type' and not a.attisdropped and c.relname<>'organizations'$q$,'BIZ-001: only organizations stores the setting');
select is_empty($q$select i.indexrelid::regclass::text from pg_index i join pg_attribute a on a.attrelid=i.indrelid and a.attnum=any(i.indkey) where i.indrelid='public.organizations'::regclass and a.attname='business_type'$q$,'BIZ-001: no index introduced for single-row vocabulary reads');
select is_empty($q$with w(sig) as(values ('public.set_business_type(public.business_type)'),('public.set_gym_business_type(uuid,public.business_type,public.business_type,uuid)')) select sig from w left join pg_proc p on p.oid=to_regprocedure(w.sig) where p.oid is null or not p.prosecdef or p.provolatile<>'v' or pg_get_userbyid(p.proowner)<>'postgres' or not coalesce(p.proconfig @> array['search_path=""'],false) or not has_function_privilege('authenticated',p.oid,'EXECUTE') or has_function_privilege('anon',p.oid,'EXECUTE') or has_function_privilege('service_role',p.oid,'EXECUTE')$q$,'BIZ-003/005: two exact postgres-owned volatile definers, empty path, authenticated only');
select ok(not has_function_privilege('authenticated','app.business_type_audit(uuid,uuid,public.app_role,text,text,uuid,jsonb,jsonb)','EXECUTE') and not has_function_privilege('service_role','app.business_type_audit(uuid,uuid,public.app_role,text,text,uuid,jsonb,jsonb)','EXECUTE') and not has_function_privilege('anon','app.business_type_audit(uuid,uuid,public.app_role,text,text,uuid,jsonb,jsonb)','EXECUTE'),'BIZ-008: audit helper private');
select ok(exists(select 1 from pg_trigger t join pg_proc p on p.oid=t.tgfoid where t.tgrelid='public.organizations'::regclass and t.tgname='organizations_commercial_invariant' and t.tgtype=23 and t.tgenabled='O' and not p.prosecdef and p.proname='enforce_organization_commercial'),'BIZ-006: existing commercial trigger posture retained');
insert into public.organizations(id,name,gym_code,status,timezone,currency) values(pg_temp.bid(1),'BIZ A','BIZ70A','active','Asia/Kolkata','INR'),(pg_temp.bid(2),'BIZ B','BIZ70B','trial','Asia/Kolkata','INR');
insert into public.organization_settings(tenant_id,no_show_threshold_days,preset) values(pg_temp.bid(1),12,'premium_studio'),(pg_temp.bid(2),7,null);
insert into public.branches(id,tenant_id,name,is_default) values(pg_temp.bid(11),pg_temp.bid(1),'A',true),(pg_temp.bid(12),pg_temp.bid(2),'B',true);
insert into auth.users(id) select pg_temp.bid(n) from generate_series(901,909) n;
insert into public.staff(id,tenant_id,user_id,branch_id,role,full_name) values
(pg_temp.bid(21),pg_temp.bid(1),pg_temp.bid(901),pg_temp.bid(11),'gym_owner','Owner'),(pg_temp.bid(22),pg_temp.bid(1),pg_temp.bid(902),pg_temp.bid(11),'gym_manager','Manager'),(pg_temp.bid(23),pg_temp.bid(1),pg_temp.bid(903),pg_temp.bid(11),'front_desk','Desk'),(pg_temp.bid(24),pg_temp.bid(1),pg_temp.bid(904),pg_temp.bid(11),'trainer','Trainer'),(pg_temp.bid(25),pg_temp.bid(2),pg_temp.bid(905),pg_temp.bid(12),'gym_owner','Other owner');
insert into public.members(id,tenant_id,branch_id,user_id,full_name,phone,date_of_birth) values(pg_temp.bid(101),pg_temp.bid(1),pg_temp.bid(11),pg_temp.bid(906),'Member','+917000000101','1990-01-01');
insert into public.platform_users(user_id,role,full_name,email,is_active) values(pg_temp.bid(907),'super_admin','Platform','platform70@example.test',true),(pg_temp.bid(908),'platform_support','Support','support70@example.test',true);
create temp table biz_settings_before as select to_jsonb(s) as row from public.organization_settings s where tenant_id=pg_temp.bid(1);
create temp table biz_org_before as select to_jsonb(o)-'business_type'-'updated_at' as row from public.organizations o where id=pg_temp.bid(1);
select is((select business_type::text from public.organizations where id=pg_temp.bid(1)),'gym','BIZ-001: newly inserted organization defaults gym');
select pg_temp.biz_claim('gym_owner');
set local role authenticated;
create temp table biz_first as select * from public.set_business_type('dance');
select results_eq($q$select business_type::text,previous_business_type::text,changed from biz_first$q$,$q$select 'dance'::text,'gym'::text,true$q$,'BIZ-003: owner returns true previous and target');
select ok(not (select changed from public.set_business_type('dance')),'BIZ-003: same value is a no-op');
select is(pg_temp.biz_refuse($q$select public.set_business_type(null)$q$),'22023','BIZ-004: authorized null value rejected');
select is(pg_temp.biz_refuse($q$update public.organizations set business_type='yoga' where id=pg_temp.bid(1)$q$,true),'42501:business_type_command_required','BIZ-006: reached owner direct type write has the exact command-required detail');
select is(pg_temp.biz_refuse($q$update public.organizations set status='suspended' where id=pg_temp.bid(1)$q$),'GL049','BIZ-006: owner direct status remains refused');
select is(pg_temp.biz_refuse($q$update public.organizations set tier='pro' where id=pg_temp.bid(1)$q$),'GL049','BIZ-006: owner direct tier remains refused');
select is(pg_temp.biz_refuse($q$update public.organizations set trial_ends_at=clock_timestamp()+interval '1 day' where id=pg_temp.bid(1)$q$),'GL049','BIZ-006: owner direct trial deadline remains refused');
select is(pg_temp.biz_refuse($q$update public.organizations set activated_at=clock_timestamp() where id=pg_temp.bid(1)$q$),'GL049','BIZ-006: owner direct activation remains refused');
select is(pg_temp.biz_refuse($q$insert into public.organizations(id,name,gym_code,status,timezone,currency) values(pg_temp.bid(99),'Unrelated','BIZ70Z','pending_approval','Asia/Kolkata','INR')$q$),'42501','BIZ-006: authenticated cross-tenant organization INSERT remains refused');
set local role postgres;
select is((select to_jsonb(o)-'business_type'-'updated_at' from public.organizations o where id=pg_temp.bid(1)),(select row from biz_org_before),'BIZ-007: type change touches no other organization fact');
select is((select to_jsonb(s) from public.organization_settings s where tenant_id=pg_temp.bid(1)),(select row from biz_settings_before),'BIZ-007: preset and threshold unchanged');
select is((select business_type::text from public.organizations where id=pg_temp.bid(2)),'gym','BIZ-007: owner affects only own tenant');
select is((select count(*)::integer from public.audit_log where tenant_id=pg_temp.bid(1) and action='organization.business_type_changed'),1,'BIZ-008: first change audited once, replay writes nothing');
select ok(exists(select 1 from public.audit_log where tenant_id=pg_temp.bid(1) and action='organization.business_type_changed' and actor_user_id=pg_temp.bid(901) and actor_role='gym_owner' and record_type='organization' and record_id=pg_temp.bid(1) and before='{"business_type":"gym"}' and after='{"business_type":"dance"}' and reason is null),'BIZ-008: exact owner audit identity and before/after shape');
select is(pg_temp.biz_refuse($q$update public.organizations set business_type='studio',name='Hidden extra edit' where id=pg_temp.bid(1)$q$),'42501','BIZ-006: postgres caller with owner subject cannot exploit pure-type exception for extra columns');
set local role authenticated;
select lives_ok($q$update public.organizations set name='BIZ owner rename',timezone='Etc/GMT+12' where id=pg_temp.bid(1)$q$,'BIZ-006: ordinary owner rename/timezone edit still succeeds');
set local role postgres;
select pg_temp.biz_claim('gym_manager',22,902);
set local role authenticated;
select is(pg_temp.biz_refuse($q$select public.set_business_type('yoga')$q$),'42501','BIZ-004: manager cannot set type');
select results_eq($q$with changed as(update public.organizations set business_type='yoga' where id=pg_temp.bid(1) returning id) select count(*)::integer from changed$q$,$q$select 0$q$,'BIZ-006: existing owner-only RLS prevents manager direct update before the row guard');
set local role postgres;
select pg_temp.biz_claim('front_desk',23,903);
set local role authenticated;
select is(pg_temp.biz_refuse($q$select public.set_business_type('yoga')$q$),'42501','BIZ-004: front desk cannot set type');
set local role postgres;
select pg_temp.biz_claim('trainer',24,904);
set local role authenticated;
select is(pg_temp.biz_refuse($q$select public.set_business_type('yoga')$q$),'42501','BIZ-004: trainer cannot set type');
set local role postgres;
select pg_temp.biz_claim('member',null,906);
set local role authenticated;
select is(pg_temp.biz_refuse($q$select public.set_business_type('yoga')$q$),'42501','BIZ-004: member cannot set type');
select is((select business_type::text from public.organizations where id=pg_temp.bid(1)),'dance','BIZ-002: member reads own tenant copy setting');
select is((select count(*)::integer from public.organizations where id=pg_temp.bid(2)),0,'BIZ-002: member cannot read foreign type');
set local role postgres;
select pg_temp.biz_claim('gym_owner',21,902);
set local role authenticated;
select is(pg_temp.biz_refuse($q$select public.set_business_type('yoga')$q$),'42501','BIZ-004: owner subject mismatch refused');
set local role postgres;
select pg_temp.biz_claim('gym_owner',21,901,1,true);
set local role authenticated;
select is(pg_temp.biz_refuse($q$select public.set_business_type('yoga')$q$),'42501','BIZ-004: impersonating owner refused');
set local role postgres;
update public.staff set is_active=false where id=pg_temp.bid(21);
select pg_temp.biz_claim('gym_owner');
set local role authenticated;
select is(pg_temp.biz_refuse($q$select public.set_business_type('yoga')$q$),'42501','BIZ-004: inactive owner refused');
set local role postgres;
update public.staff set is_active=true where id=pg_temp.bid(21);
select pg_temp.biz_claim('gym_owner',25,905,2);
set local role authenticated;
select is((select business_type::text from public.organizations where id=pg_temp.bid(2)),'gym','BIZ-002: foreign owner reads own original type');
select is((select count(*)::integer from public.organizations where id=pg_temp.bid(1)),0,'BIZ-002: other owner cannot read first tenant type');
select lives_ok($q$select public.set_business_type('martial_arts')$q$,'BIZ-003: second owner changes second tenant independently');
set local role postgres;
select is((select business_type::text from public.organizations where id=pg_temp.bid(1)),'dance','BIZ-007: second tenant change leaves first intact');
select pg_temp.biz_claim('platform_support',null,908,null);
set local role authenticated;
select is(pg_temp.biz_refuse($q$select public.set_business_type('yoga')$q$),'42501','BIZ-004: platform support cannot use owner command');
select is(pg_temp.biz_refuse($q$select public.set_gym_business_type(pg_temp.bid(1),'dance','yoga',pg_temp.bid(401))$q$),'42501','BIZ-005: platform support cannot use platform command');
set local role postgres;
select pg_temp.biz_claim('super_admin',null,907,null);
set local role authenticated;
select is(pg_temp.biz_refuse($q$select public.set_business_type('yoga')$q$),'42501','BIZ-004: super admin cannot use owner command');
select is(pg_temp.biz_refuse($q$update public.organizations set business_type='yoga' where id=pg_temp.bid(1)$q$),'42501','BIZ-006: authenticated super admin direct update refused');
select is(pg_temp.biz_refuse($q$select public.set_gym_business_type(pg_temp.bid(1),null,'yoga',pg_temp.bid(401))$q$),'22023','BIZ-005: platform null input refused');
select is(pg_temp.biz_refuse($q$select public.set_gym_business_type(pg_temp.bid(9999),'gym','yoga',pg_temp.bid(401))$q$),'P0002','BIZ-005: platform unknown tenant');
select is(pg_temp.biz_refuse($q$select public.set_gym_business_type(pg_temp.bid(1),'gym','yoga',pg_temp.bid(401))$q$),'40001','BIZ-005: stale platform expected type');
create temp table biz_platform as select public.set_gym_business_type(pg_temp.bid(1),'dance','yoga',pg_temp.bid(401)) as result;
select is((select result from biz_platform),jsonb_build_object('tenantId',pg_temp.bid(1),'businessType','yoga'),'BIZ-005: platform change returns exact result');
select is(public.set_gym_business_type(pg_temp.bid(1),'dance','yoga',pg_temp.bid(401)),(select result from biz_platform),'BIZ-005: exact replay precedes stale check and returns original result');
select is(pg_temp.biz_refuse($q$select public.set_gym_business_type(pg_temp.bid(1),'yoga','studio',pg_temp.bid(401))$q$),'GL068','BIZ-005: same request key with different facts refused');
select is(public.set_gym_business_type(pg_temp.bid(1),'yoga','yoga',pg_temp.bid(402)),jsonb_build_object('tenantId',pg_temp.bid(1),'businessType','yoga'),'BIZ-005: semantic no-op returns result');
select is(pg_temp.biz_refuse($q$select public.set_gym_status(pg_temp.bid(2),'trial','suspended','reason',pg_temp.bid(403))$q$),'GL050','BIZ-006: illegal status edge unchanged');
select is(pg_temp.biz_refuse($q$select public.set_gym_status(pg_temp.bid(2),'trial','active',null,pg_temp.bid(404))$q$),'GL051','BIZ-006: activation readiness guard unchanged');
set local role postgres;
select is((select count(*)::integer from public.audit_log where tenant_id=pg_temp.bid(1) and action='organization.business_type_changed'),2,'BIZ-008: platform change adds exactly one audit; replay/no-op/refusals add none');
select ok(exists(select 1 from public.audit_log where tenant_id=pg_temp.bid(1) and action='organization.business_type_changed' and actor_user_id=pg_temp.bid(907) and actor_role='super_admin' and before='{"business_type":"dance"}' and after='{"business_type":"yoga"}' and request_key=pg_temp.bid(401) and request_facts->>'command'='set_gym_business_type' and request_facts->'request'='{"expectedBusinessType":"dance","businessType":"yoga"}'),'BIZ-008: platform audit stores actor, keyed request and exact type facts');
select set_config('request.jwt.claims','',true);
select lives_ok($q$update public.organizations set business_type='studio' where id=pg_temp.bid(1)$q$,'BIZ-006: trusted migration/seed writer remains allowed');
set local role service_role;
select lives_ok($q$update public.organizations set business_type='gym' where id=pg_temp.bid(1)$q$,'BIZ-006: subjectless service-role provisioning remains allowed');
select is(pg_temp.biz_refuse($q$select public.set_business_type('dance')$q$),'42501','BIZ-004: service role cannot call owner command');
set local role postgres;
select is(pg_temp.biz_refuse($q$select app.business_type_audit(pg_temp.bid(1),null,null,'other.action','organization',pg_temp.bid(1),null,null)$q$),'22023','BIZ-008: helper refuses other audit actions');
set local role anon;
select is(pg_temp.biz_refuse($q$select business_type from public.organizations where id in(pg_temp.bid(1),pg_temp.bid(2))$q$),'42501','BIZ-002: anon organization-type read refused by canonical SELECT privilege');
select is(pg_temp.biz_refuse($q$select public.set_business_type('dance')$q$),'42501','BIZ-004: anon cannot call owner command');
set local role postgres;
select * from finish();
rollback;
