-- PLC-001..004/020: implementation-blind visible RLS contract.
begin;
set local role postgres;
set local search_path=extensions,public;
select set_config('request.jwt.claims','',true);
select plan(32);
create function pg_temp.pid(n integer) returns uuid language sql immutable as $$select ('71000000-0000-4000-8000-'||lpad(n::text,12,'0'))::uuid$$;
create function pg_temp.plc_claim(r text,t integer default 1,s integer default null,m integer default 101) returns void language plpgsql as $$begin perform set_config('request.jwt.claims',jsonb_strip_nulls(jsonb_build_object('role','authenticated','app_role',r,'tenant_id',case when t is not null then pg_temp.pid(t) end,'staff_id',case when s is not null then pg_temp.pid(s) end,'member_id',case when m is not null then pg_temp.pid(m) end))::text,true); end$$;
grant execute on function pg_temp.pid(integer),pg_temp.plc_claim(text,integer,integer,integer) to authenticated,anon;
select results_eq($q$select polname::text from pg_policy where polrelid='public.plans'::regclass order by polname$q$,$q$select * from (values('plans_member_select'),('plans_platform_select'),('plans_platform_write'),('plans_tenant_select'),('plans_tenant_write')) as expected$q$,'PLC-003: exactly existing five named policies');
select is((select polcmd::text from pg_policy where polrelid='public.plans'::regclass and polname='plans_member_select'),'r','PLC-003: member gate remains select');
select ok((select polroles=array[(select oid from pg_roles where rolname='authenticated')] from pg_policy where polrelid='public.plans'::regclass and polname='plans_member_select'),'PLC-003: member gate remains authenticated');
select is((select regexp_replace(regexp_replace(lower(pg_get_expr(polqual,polrelid)),'\s+as\s+\w+','','g'),'[\s()]','','g') from pg_policy where polrelid='public.plans'::regclass and polname='plans_member_select'),$p$tenant_id=selectapp.current_tenant_idandselectapp.current_app_role='member'::textandselectapp.current_member_idisnotnullandis_active$p$,'PLC-003: exact one-conjunct narrowing');
select results_eq($q$select attname::text from pg_attribute where attrelid='public.plans'::regclass and attnum>0 and not attisdropped order by attname$q$,$q$select * from (values('created_at'),('currency'),('description'),('duration_days'),('gst_rate_bp'),('id'),('is_active'),('max_freeze_days'),('name'),('price_paise'),('sort_order'),('tenant_id'),('updated_at')) as expected$q$,'PLC-003: exact unchanged column set');
select ok(exists(select 1 from pg_index i where i.indexrelid='public.plans_tenant_id_is_active_idx'::regclass and i.indrelid='public.plans'::regclass and pg_get_indexdef(i.indexrelid) like '%(tenant_id, is_active)%'),'PLC-003: existing indexed member access path');
select ok(has_table_privilege('authenticated','public.plans','SELECT,INSERT,UPDATE') and not has_table_privilege('authenticated','public.plans','DELETE') and not has_table_privilege('authenticated','public.plans','TRUNCATE'),'PLC-002: unchanged table privileges');
insert into public.organizations(id,name,gym_code,status) values(pg_temp.pid(1),'PLC A','PLC71A','active'),(pg_temp.pid(2),'PLC B','PLC71B','active');
insert into public.branches(id,tenant_id,name,is_default) values(pg_temp.pid(11),pg_temp.pid(1),'A',true),(pg_temp.pid(12),pg_temp.pid(2),'B',true);
insert into public.staff(id,tenant_id,branch_id,role,full_name) values(pg_temp.pid(21),pg_temp.pid(1),pg_temp.pid(11),'gym_owner','Owner'),(pg_temp.pid(22),pg_temp.pid(1),pg_temp.pid(11),'gym_manager','Manager'),(pg_temp.pid(23),pg_temp.pid(1),pg_temp.pid(11),'front_desk','Desk'),(pg_temp.pid(24),pg_temp.pid(1),pg_temp.pid(11),'trainer','Trainer');
insert into public.members(id,tenant_id,branch_id,full_name,phone,date_of_birth) values(pg_temp.pid(101),pg_temp.pid(1),pg_temp.pid(11),'PLC Adult','+917100000101','1990-01-01'),(pg_temp.pid(102),pg_temp.pid(2),pg_temp.pid(12),'PLC Other','+917100000102','1990-01-01');
insert into public.plans(id,tenant_id,name,duration_days,price_paise,is_active,sort_order) values
(pg_temp.pid(201),pg_temp.pid(1),'A first',30,150000,true,1),(pg_temp.pid(202),pg_temp.pid(1),'A second',90,400000,true,2),(pg_temp.pid(203),pg_temp.pid(1),'A hidden',30,120000,false,0),(pg_temp.pid(204),pg_temp.pid(2),'B active',30,99000,true,0),(pg_temp.pid(205),pg_temp.pid(2),'B hidden',30,88000,false,1);
insert into public.memberships(id,tenant_id,member_id,plan_id,status,price_paise,currency) values(pg_temp.pid(301),pg_temp.pid(1),pg_temp.pid(101),pg_temp.pid(203),'expired',120000,'INR');
select pg_temp.plc_claim('member');
set local role authenticated;
select results_eq($q$select id from public.plans order by sort_order$q$,$q$select * from (values(pg_temp.pid(201)),(pg_temp.pid(202))) as expected$q$,'PLC-001: unfiltered member read only own active plans in database order');
select is((select count(*)::integer from public.plans where id=pg_temp.pid(203)),0,'PLC-001: hidden own plan by primary key is zero rows');
select is((select count(*)::integer from public.plans where is_active=false),0,'PLC-001: explicit inactive predicate is zero rows');
select is((select count(*)::integer from public.plans),2,'PLC-001: count reveals only active own rows');
select is((select count(*)::integer from public.plans where tenant_id=pg_temp.pid(2)),0,'PLC-020: foreign active and inactive rows absent');
select is((select count(*)::integer from public.memberships where id=pg_temp.pid(301)),1,'PLC-004: own inactive-plan membership retained');
select is((select count(*)::integer from public.memberships m join public.plans p on p.id=m.plan_id where m.id=pg_temp.pid(301)),0,'PLC-004: inactive plan inner join absent');
select ok((select p.name is null from public.memberships m left join public.plans p on p.id=m.plan_id where m.id=pg_temp.pid(301)),'PLC-004: embedded equivalent leaves generic-name fallback');
select throws_ok($q$insert into public.plans(tenant_id,name,duration_days,price_paise) values(pg_temp.pid(1),'Member created',30,1)$q$,'42501',null,'PLC-002: member insert refused');
select results_eq($q$with changed as(update public.plans set price_paise=1 where id=pg_temp.pid(201) returning id) select count(*)::integer from changed$q$,$q$select 0$q$,'PLC-002: member update affects zero rows');
select throws_ok($q$delete from public.plans where id=pg_temp.pid(201)$q$,'42501',null,'PLC-002: delete privilege still absent');
reset role;
select pg_temp.plc_claim('gym_owner',1,21,null);
set local role authenticated;
select is((select count(*)::integer from public.plans),3,'PLC-002: owner sees active and inactive own plans');
update public.plans set is_active=false where id=pg_temp.pid(202);
reset role;
select pg_temp.plc_claim('member');
set local role authenticated;
select is((select count(*)::integer from public.plans),1,'PLC-001: owner deactivation hides immediately within transaction');
reset role;
select pg_temp.plc_claim('gym_owner',1,21,null);
set local role authenticated;
update public.plans set is_active=true where id=pg_temp.pid(202);
reset role;
select pg_temp.plc_claim('member');
set local role authenticated;
select is((select count(*)::integer from public.plans),2,'PLC-001: reactivation restores visibility within transaction');
reset role;
select pg_temp.plc_claim('gym_manager',1,22,null);
set local role authenticated;
select is((select count(*)::integer from public.plans),3,'PLC-002: manager still sees all own plans');
reset role;
select pg_temp.plc_claim('front_desk',1,23,null);
set local role authenticated;
select is((select count(*)::integer from public.plans),3,'PLC-002: desk still sees all own plans');
reset role;
select pg_temp.plc_claim('trainer',1,24,null);
set local role authenticated;
select is((select count(*)::integer from public.plans),3,'PLC-002: real trainer still sees all own plans');
select is((select count(*)::integer from public.plans where tenant_id=pg_temp.pid(2)),0,'PLC-020: staff remains tenant scoped');
reset role;
select pg_temp.plc_claim('platform_support',null,null,null);
set local role authenticated;
select is((select count(*)::integer from public.plans where tenant_id in(pg_temp.pid(1),pg_temp.pid(2))),5,'PLC-002: platform support sees both tenant sets');
reset role;
select pg_temp.plc_claim('super_admin',null,null,null);
set local role authenticated;
select is((select count(*)::integer from public.plans where tenant_id in(pg_temp.pid(1),pg_temp.pid(2))),5,'PLC-002: super admin sees both tenant sets');
reset role;
select pg_temp.plc_claim('trainer',1,null,101);
set local role authenticated;
select is((select count(*)::integer from public.plans),0,'PLC-002: trainer word plus member id cannot impersonate either gate');
reset role;
select pg_temp.plc_claim(null);
set local role authenticated;
select is((select count(*)::integer from public.plans),0,'PLC-002: tenant and member claims without role reveal nothing');
reset role;
select set_config('request.jwt.claims','',true);
set local role authenticated;
select is((select count(*)::integer from public.plans),0,'PLC-002: no claims read succeeds with zero rows');
reset role;
select pg_temp.plc_claim('member',2,null,102);
set local role authenticated;
select results_eq($q$select id from public.plans$q$,$q$select pg_temp.pid(204)$q$,'PLC-020: isolation works in reverse');
reset role;
set local role anon;
select is((select count(*)::integer from public.plans),0,'PLC-020: anon sees no plans');
reset role;
select * from finish();
rollback;
