-- Independent ANC boundary suite from public frozen contract; no implementation read.
begin;
set local role postgres;
set local search_path=extensions,public;
select set_config('request.jwt.claims','',true);
select plan(250);
create function pg_temp.u(n integer) returns uuid language sql immutable as $$select ('75100000-0000-4000-8000-'||lpad(n::text,12,'0'))::uuid$$;
create function pg_temp.claim(r text,s integer,m integer,u integer,t integer) returns void language plpgsql as $$begin perform set_config('request.jwt.claims',jsonb_strip_nulls(jsonb_build_object('sub',pg_temp.u(u),'role','authenticated','app_role',r,'tenant_id',pg_temp.u(t),'staff_id',case when s is not null then pg_temp.u(s) end,'member_id',case when m is not null then pg_temp.u(m) end))::text,true);end$$;
create function pg_temp.refusal(q text) returns text language plpgsql as $$begin execute q; return 'OK'; exception when others then return sqlstate; end$$;
create temp table boundary_ids(t integer,k text,id uuid,primary key(t,k));
grant all on boundary_ids to authenticated,service_role;
insert into auth.users(id,email) values(pg_temp.u(999),'anc-boundary-platform@example.test'),(pg_temp.u(921),'anc-boundary-owner1@example.test'),(pg_temp.u(922),'anc-boundary-owner2@example.test');
insert into auth.users(id,email) select pg_temp.u(n+900),'anc-boundary-'||n||'@example.test' from generate_series(101,126)n;
insert into public.platform_users(user_id,role,full_name,email,is_active) values(pg_temp.u(999),'super_admin','Boundary platform','anc-boundary-platform@example.test',true);
-- Use the real active platform commercial-configuration guard for tenant and staff fixtures.
select pg_temp.claim('super_admin',null,null,999,null);
insert into public.organizations(id,name,gym_code,status,timezone) values
(pg_temp.u(1),'ANC Boundary West','AB751W','active','Etc/GMT+12'),
(pg_temp.u(2),'ANC Boundary East','AB751E','active','Pacific/Kiritimati');
insert into public.branches(id,tenant_id,name,is_default,timezone) values(pg_temp.u(11),pg_temp.u(1),'West',true,'Etc/GMT+12'),(pg_temp.u(12),pg_temp.u(2),'East',true,'Pacific/Kiritimati');
insert into public.staff(id,tenant_id,branch_id,user_id,role,full_name,is_active) values(pg_temp.u(21),pg_temp.u(1),pg_temp.u(11),pg_temp.u(921),'gym_owner','West owner',true),(pg_temp.u(22),pg_temp.u(2),pg_temp.u(12),pg_temp.u(922),'gym_owner','East owner',true);
select set_config('request.jwt.claims','',true);
insert into public.plans(id,tenant_id,name,duration_days,price_paise) values(pg_temp.u(41),pg_temp.u(1),'Boundary West',30,10000),(pg_temp.u(42),pg_temp.u(2),'Boundary East',30,10000);
create temp table boundary_cases(n integer primary key,t integer,scenario text,live boolean,standing boolean);
insert into boundary_cases values(101,1,'active_today',true,true);
insert into boundary_cases values(102,1,'frozen_today',true,true);
insert into boundary_cases values(103,1,'active_starts_tomorrow',false,true);
insert into boundary_cases values(104,1,'active_ended_yesterday',false,true);
insert into boundary_cases values(105,1,'frozen_starts_tomorrow',false,true);
insert into boundary_cases values(106,1,'frozen_ended_yesterday',false,true);
insert into boundary_cases values(107,1,'pending_null',false,true);
insert into boundary_cases values(108,1,'expired_today',false,true);
insert into boundary_cases values(109,1,'cancelled_today',false,true);
insert into boundary_cases values(110,1,'no_membership',false,true);
insert into boundary_cases values(111,1,'any_qualifying',true,true);
insert into boundary_cases values(112,1,'blocked_live',true,false);
insert into boundary_cases values(113,1,'erased_live',true,false);
insert into boundary_cases values(114,2,'active_today',true,true);
insert into boundary_cases values(115,2,'frozen_today',true,true);
insert into boundary_cases values(116,2,'active_starts_tomorrow',false,true);
insert into boundary_cases values(117,2,'active_ended_yesterday',false,true);
insert into boundary_cases values(118,2,'frozen_starts_tomorrow',false,true);
insert into boundary_cases values(119,2,'frozen_ended_yesterday',false,true);
insert into boundary_cases values(120,2,'pending_null',false,true);
insert into boundary_cases values(121,2,'expired_today',false,true);
insert into boundary_cases values(122,2,'cancelled_today',false,true);
insert into boundary_cases values(123,2,'no_membership',false,true);
insert into boundary_cases values(124,2,'any_qualifying',true,true);
insert into boundary_cases values(125,2,'blocked_live',true,false);
insert into boundary_cases values(126,2,'erased_live',true,false);
insert into public.members(id,tenant_id,branch_id,user_id,full_name,phone,status,erased_at)
select pg_temp.u(n),pg_temp.u(t),pg_temp.u(t+10),pg_temp.u(n+900),'Boundary '||scenario,'+91751000'||lpad(n::text,4,'0'),case when scenario='blocked_live' then 'blocked'::public.member_status else 'active'::public.member_status end,case when scenario='erased_live' then statement_timestamp() end from boundary_cases;
insert into public.memberships(id,tenant_id,member_id,plan_id,status,starts_on,ends_on,price_paise,currency)
select pg_temp.u(n+1000),pg_temp.u(t),pg_temp.u(n),pg_temp.u(t+40),
case when scenario like 'frozen%' then 'frozen'::public.membership_status when scenario='pending_null' then 'pending'::public.membership_status when scenario='expired_today' then 'expired'::public.membership_status when scenario='cancelled_today' then 'cancelled'::public.membership_status else 'active'::public.membership_status end,
case when scenario='pending_null' then null when scenario like '%starts_tomorrow' then app.gym_today(pg_temp.u(t))+1 when scenario like '%ended_yesterday' then app.gym_today(pg_temp.u(t))-30 else app.gym_today(pg_temp.u(t)) end,
case when scenario='pending_null' then null when scenario like '%starts_tomorrow' then app.gym_today(pg_temp.u(t))+30 when scenario like '%ended_yesterday' then app.gym_today(pg_temp.u(t))-1 else app.gym_today(pg_temp.u(t)) end,10000,'INR'
from boundary_cases where scenario<>'no_membership';
-- A nonqualifying history row cannot veto the qualifying inclusive-endpoint row.
insert into public.memberships(id,tenant_id,member_id,plan_id,status,starts_on,ends_on,price_paise,currency)
select pg_temp.u(n+2000),pg_temp.u(t),pg_temp.u(n),pg_temp.u(t+40),'expired',app.gym_today(pg_temp.u(t))-30,app.gym_today(pg_temp.u(t))-1,10000,'INR' from boundary_cases where scenario='any_qualifying';
select is(app.gym_today(pg_temp.u(1)),(statement_timestamp() at time zone 'Etc/GMT+12')::date,'ANC boundary: west uses actual gym-local today');
select is(app.gym_today(pg_temp.u(2)),(statement_timestamp() at time zone 'Pacific/Kiritimati')::date,'ANC boundary: east uses actual gym-local today');
select ok(app.gym_today(pg_temp.u(2))>app.gym_today(pg_temp.u(1)),'ANC boundary: opposite zones expose different current calendar days');
set local role authenticated;
select pg_temp.claim('gym_owner',21,null,921,1);
insert into boundary_ids values(1,'live',public.create_announcement_draft('transactional','live boundary','Membership dates','segment',array['active']::public.member_status[],'live',null,null));
select is((select audience_count from public.publish_announcement((select id from boundary_ids where t=1 and k='live'))),3,'ANC boundary: tenant 1 live publish uses same inclusive-date audience');
insert into boundary_ids values(1,'not_live',public.create_announcement_draft('transactional','not_live boundary','Membership dates','segment',array['active']::public.member_status[],'not_live',null,null));
select is((select audience_count from public.publish_announcement((select id from boundary_ids where t=1 and k='not_live'))),8,'ANC boundary: tenant 1 not_live publish uses same inclusive-date audience');
insert into boundary_ids values(1,'all',public.create_announcement_draft('transactional','all boundary','Membership dates','all_members',null,null,null,null));
select is((select audience_count from public.publish_announcement((select id from boundary_ids where t=1 and k='all'))),11,'ANC boundary: tenant 1 all publish uses same inclusive-date audience');
insert into boundary_ids values(1,'promo',public.create_announcement_draft('promotional','promo boundary','Membership dates','segment',array['active']::public.member_status[],'live',null,null));
select is((select audience_count from public.publish_announcement((select id from boundary_ids where t=1 and k='promo'))),0,'ANC boundary: tenant 1 promo publish uses same inclusive-date audience');
select is((select audience_count from public.list_announcements() where announcement_id=(select id from boundary_ids where t=1 and k='live')),3,'ANC boundary: tenant 1 live staff list matches audience');
select is((public.read_announcement((select id from boundary_ids where t=1 and k='live'))->'announcement'->>'audienceCount')::integer,3,'ANC boundary: tenant 1 live staff detail matches audience');
select is((select audience_count from public.list_announcements() where announcement_id=(select id from boundary_ids where t=1 and k='not_live')),8,'ANC boundary: tenant 1 not_live staff list matches audience');
select is((public.read_announcement((select id from boundary_ids where t=1 and k='not_live'))->'announcement'->>'audienceCount')::integer,8,'ANC boundary: tenant 1 not_live staff detail matches audience');
select is((select audience_count from public.list_announcements() where announcement_id=(select id from boundary_ids where t=1 and k='all')),11,'ANC boundary: tenant 1 all staff list matches audience');
select is((public.read_announcement((select id from boundary_ids where t=1 and k='all'))->'announcement'->>'audienceCount')::integer,11,'ANC boundary: tenant 1 all staff detail matches audience');
select is((select audience_count from public.list_announcements() where announcement_id=(select id from boundary_ids where t=1 and k='promo')),0,'ANC boundary: tenant 1 promo staff list matches audience');
select is((public.read_announcement((select id from boundary_ids where t=1 and k='promo'))->'announcement'->>'audienceCount')::integer,0,'ANC boundary: tenant 1 promo staff detail matches audience');
set local role postgres;
set local role authenticated;
select pg_temp.claim('gym_owner',22,null,922,2);
insert into boundary_ids values(2,'live',public.create_announcement_draft('transactional','live boundary','Membership dates','segment',array['active']::public.member_status[],'live',null,null));
select is((select audience_count from public.publish_announcement((select id from boundary_ids where t=2 and k='live'))),3,'ANC boundary: tenant 2 live publish uses same inclusive-date audience');
insert into boundary_ids values(2,'not_live',public.create_announcement_draft('transactional','not_live boundary','Membership dates','segment',array['active']::public.member_status[],'not_live',null,null));
select is((select audience_count from public.publish_announcement((select id from boundary_ids where t=2 and k='not_live'))),8,'ANC boundary: tenant 2 not_live publish uses same inclusive-date audience');
insert into boundary_ids values(2,'all',public.create_announcement_draft('transactional','all boundary','Membership dates','all_members',null,null,null,null));
select is((select audience_count from public.publish_announcement((select id from boundary_ids where t=2 and k='all'))),11,'ANC boundary: tenant 2 all publish uses same inclusive-date audience');
insert into boundary_ids values(2,'promo',public.create_announcement_draft('promotional','promo boundary','Membership dates','segment',array['active']::public.member_status[],'live',null,null));
select is((select audience_count from public.publish_announcement((select id from boundary_ids where t=2 and k='promo'))),0,'ANC boundary: tenant 2 promo publish uses same inclusive-date audience');
select is((select audience_count from public.list_announcements() where announcement_id=(select id from boundary_ids where t=2 and k='live')),3,'ANC boundary: tenant 2 live staff list matches audience');
select is((public.read_announcement((select id from boundary_ids where t=2 and k='live'))->'announcement'->>'audienceCount')::integer,3,'ANC boundary: tenant 2 live staff detail matches audience');
select is((select audience_count from public.list_announcements() where announcement_id=(select id from boundary_ids where t=2 and k='not_live')),8,'ANC boundary: tenant 2 not_live staff list matches audience');
select is((public.read_announcement((select id from boundary_ids where t=2 and k='not_live'))->'announcement'->>'audienceCount')::integer,8,'ANC boundary: tenant 2 not_live staff detail matches audience');
select is((select audience_count from public.list_announcements() where announcement_id=(select id from boundary_ids where t=2 and k='all')),11,'ANC boundary: tenant 2 all staff list matches audience');
select is((public.read_announcement((select id from boundary_ids where t=2 and k='all'))->'announcement'->>'audienceCount')::integer,11,'ANC boundary: tenant 2 all staff detail matches audience');
select is((select audience_count from public.list_announcements() where announcement_id=(select id from boundary_ids where t=2 and k='promo')),0,'ANC boundary: tenant 2 promo staff list matches audience');
select is((public.read_announcement((select id from boundary_ids where t=2 and k='promo'))->'announcement'->>'audienceCount')::integer,0,'ANC boundary: tenant 2 promo staff detail matches audience');
set local role postgres;
set local role postgres;
select pg_temp.claim('member',null,101,1001,1);
set local role authenticated;
select is((select count(*)::integer from public.read_member_announcements() where announcement_id=(select id from boundary_ids where t=1 and k='live')),1,'ANC boundary: 1 active_today live feed');
select is(public.mark_announcement_read((select id from boundary_ids where t=1 and k='live'),1),true,'ANC boundary: 1 active_today live marker matches current audience');
select is((select count(*)::integer from public.read_member_announcements() where announcement_id=(select id from boundary_ids where t=1 and k='not_live')),0,'ANC boundary: 1 active_today not_live feed');
select is(public.mark_announcement_read((select id from boundary_ids where t=1 and k='not_live'),1),false,'ANC boundary: 1 active_today not_live marker matches current audience');
select is((select count(*)::integer from public.read_member_announcements() where announcement_id=(select id from boundary_ids where t=1 and k='all')),1,'ANC boundary: 1 active_today all feed');
select is(public.mark_announcement_read((select id from boundary_ids where t=1 and k='all'),1),true,'ANC boundary: 1 active_today all marker matches current audience');
select is((select count(*)::integer from public.read_member_announcements() where announcement_id=(select id from boundary_ids where t=1 and k='promo')),0,'ANC boundary: 1 active_today promo feed');
select is(public.mark_announcement_read((select id from boundary_ids where t=1 and k='promo'),1),false,'ANC boundary: 1 active_today promo marker matches current audience');
set local role postgres;
select pg_temp.claim('member',null,102,1002,1);
set local role authenticated;
select is((select count(*)::integer from public.read_member_announcements() where announcement_id=(select id from boundary_ids where t=1 and k='live')),1,'ANC boundary: 1 frozen_today live feed');
select is(public.mark_announcement_read((select id from boundary_ids where t=1 and k='live'),1),true,'ANC boundary: 1 frozen_today live marker matches current audience');
select is((select count(*)::integer from public.read_member_announcements() where announcement_id=(select id from boundary_ids where t=1 and k='not_live')),0,'ANC boundary: 1 frozen_today not_live feed');
select is(public.mark_announcement_read((select id from boundary_ids where t=1 and k='not_live'),1),false,'ANC boundary: 1 frozen_today not_live marker matches current audience');
select is((select count(*)::integer from public.read_member_announcements() where announcement_id=(select id from boundary_ids where t=1 and k='all')),1,'ANC boundary: 1 frozen_today all feed');
select is(public.mark_announcement_read((select id from boundary_ids where t=1 and k='all'),1),true,'ANC boundary: 1 frozen_today all marker matches current audience');
select is((select count(*)::integer from public.read_member_announcements() where announcement_id=(select id from boundary_ids where t=1 and k='promo')),0,'ANC boundary: 1 frozen_today promo feed');
select is(public.mark_announcement_read((select id from boundary_ids where t=1 and k='promo'),1),false,'ANC boundary: 1 frozen_today promo marker matches current audience');
set local role postgres;
select pg_temp.claim('member',null,103,1003,1);
set local role authenticated;
select is((select count(*)::integer from public.read_member_announcements() where announcement_id=(select id from boundary_ids where t=1 and k='live')),0,'ANC boundary: 1 active_starts_tomorrow live feed');
select is(public.mark_announcement_read((select id from boundary_ids where t=1 and k='live'),1),false,'ANC boundary: 1 active_starts_tomorrow live marker matches current audience');
select is((select count(*)::integer from public.read_member_announcements() where announcement_id=(select id from boundary_ids where t=1 and k='not_live')),1,'ANC boundary: 1 active_starts_tomorrow not_live feed');
select is(public.mark_announcement_read((select id from boundary_ids where t=1 and k='not_live'),1),true,'ANC boundary: 1 active_starts_tomorrow not_live marker matches current audience');
select is((select count(*)::integer from public.read_member_announcements() where announcement_id=(select id from boundary_ids where t=1 and k='all')),1,'ANC boundary: 1 active_starts_tomorrow all feed');
select is(public.mark_announcement_read((select id from boundary_ids where t=1 and k='all'),1),true,'ANC boundary: 1 active_starts_tomorrow all marker matches current audience');
select is((select count(*)::integer from public.read_member_announcements() where announcement_id=(select id from boundary_ids where t=1 and k='promo')),0,'ANC boundary: 1 active_starts_tomorrow promo feed');
select is(public.mark_announcement_read((select id from boundary_ids where t=1 and k='promo'),1),false,'ANC boundary: 1 active_starts_tomorrow promo marker matches current audience');
set local role postgres;
select pg_temp.claim('member',null,104,1004,1);
set local role authenticated;
select is((select count(*)::integer from public.read_member_announcements() where announcement_id=(select id from boundary_ids where t=1 and k='live')),0,'ANC boundary: 1 active_ended_yesterday live feed');
select is(public.mark_announcement_read((select id from boundary_ids where t=1 and k='live'),1),false,'ANC boundary: 1 active_ended_yesterday live marker matches current audience');
select is((select count(*)::integer from public.read_member_announcements() where announcement_id=(select id from boundary_ids where t=1 and k='not_live')),1,'ANC boundary: 1 active_ended_yesterday not_live feed');
select is(public.mark_announcement_read((select id from boundary_ids where t=1 and k='not_live'),1),true,'ANC boundary: 1 active_ended_yesterday not_live marker matches current audience');
select is((select count(*)::integer from public.read_member_announcements() where announcement_id=(select id from boundary_ids where t=1 and k='all')),1,'ANC boundary: 1 active_ended_yesterday all feed');
select is(public.mark_announcement_read((select id from boundary_ids where t=1 and k='all'),1),true,'ANC boundary: 1 active_ended_yesterday all marker matches current audience');
select is((select count(*)::integer from public.read_member_announcements() where announcement_id=(select id from boundary_ids where t=1 and k='promo')),0,'ANC boundary: 1 active_ended_yesterday promo feed');
select is(public.mark_announcement_read((select id from boundary_ids where t=1 and k='promo'),1),false,'ANC boundary: 1 active_ended_yesterday promo marker matches current audience');
set local role postgres;
select pg_temp.claim('member',null,105,1005,1);
set local role authenticated;
select is((select count(*)::integer from public.read_member_announcements() where announcement_id=(select id from boundary_ids where t=1 and k='live')),0,'ANC boundary: 1 frozen_starts_tomorrow live feed');
select is(public.mark_announcement_read((select id from boundary_ids where t=1 and k='live'),1),false,'ANC boundary: 1 frozen_starts_tomorrow live marker matches current audience');
select is((select count(*)::integer from public.read_member_announcements() where announcement_id=(select id from boundary_ids where t=1 and k='not_live')),1,'ANC boundary: 1 frozen_starts_tomorrow not_live feed');
select is(public.mark_announcement_read((select id from boundary_ids where t=1 and k='not_live'),1),true,'ANC boundary: 1 frozen_starts_tomorrow not_live marker matches current audience');
select is((select count(*)::integer from public.read_member_announcements() where announcement_id=(select id from boundary_ids where t=1 and k='all')),1,'ANC boundary: 1 frozen_starts_tomorrow all feed');
select is(public.mark_announcement_read((select id from boundary_ids where t=1 and k='all'),1),true,'ANC boundary: 1 frozen_starts_tomorrow all marker matches current audience');
select is((select count(*)::integer from public.read_member_announcements() where announcement_id=(select id from boundary_ids where t=1 and k='promo')),0,'ANC boundary: 1 frozen_starts_tomorrow promo feed');
select is(public.mark_announcement_read((select id from boundary_ids where t=1 and k='promo'),1),false,'ANC boundary: 1 frozen_starts_tomorrow promo marker matches current audience');
set local role postgres;
select pg_temp.claim('member',null,106,1006,1);
set local role authenticated;
select is((select count(*)::integer from public.read_member_announcements() where announcement_id=(select id from boundary_ids where t=1 and k='live')),0,'ANC boundary: 1 frozen_ended_yesterday live feed');
select is(public.mark_announcement_read((select id from boundary_ids where t=1 and k='live'),1),false,'ANC boundary: 1 frozen_ended_yesterday live marker matches current audience');
select is((select count(*)::integer from public.read_member_announcements() where announcement_id=(select id from boundary_ids where t=1 and k='not_live')),1,'ANC boundary: 1 frozen_ended_yesterday not_live feed');
select is(public.mark_announcement_read((select id from boundary_ids where t=1 and k='not_live'),1),true,'ANC boundary: 1 frozen_ended_yesterday not_live marker matches current audience');
select is((select count(*)::integer from public.read_member_announcements() where announcement_id=(select id from boundary_ids where t=1 and k='all')),1,'ANC boundary: 1 frozen_ended_yesterday all feed');
select is(public.mark_announcement_read((select id from boundary_ids where t=1 and k='all'),1),true,'ANC boundary: 1 frozen_ended_yesterday all marker matches current audience');
select is((select count(*)::integer from public.read_member_announcements() where announcement_id=(select id from boundary_ids where t=1 and k='promo')),0,'ANC boundary: 1 frozen_ended_yesterday promo feed');
select is(public.mark_announcement_read((select id from boundary_ids where t=1 and k='promo'),1),false,'ANC boundary: 1 frozen_ended_yesterday promo marker matches current audience');
set local role postgres;
select pg_temp.claim('member',null,107,1007,1);
set local role authenticated;
select is((select count(*)::integer from public.read_member_announcements() where announcement_id=(select id from boundary_ids where t=1 and k='live')),0,'ANC boundary: 1 pending_null live feed');
select is(public.mark_announcement_read((select id from boundary_ids where t=1 and k='live'),1),false,'ANC boundary: 1 pending_null live marker matches current audience');
select is((select count(*)::integer from public.read_member_announcements() where announcement_id=(select id from boundary_ids where t=1 and k='not_live')),1,'ANC boundary: 1 pending_null not_live feed');
select is(public.mark_announcement_read((select id from boundary_ids where t=1 and k='not_live'),1),true,'ANC boundary: 1 pending_null not_live marker matches current audience');
select is((select count(*)::integer from public.read_member_announcements() where announcement_id=(select id from boundary_ids where t=1 and k='all')),1,'ANC boundary: 1 pending_null all feed');
select is(public.mark_announcement_read((select id from boundary_ids where t=1 and k='all'),1),true,'ANC boundary: 1 pending_null all marker matches current audience');
select is((select count(*)::integer from public.read_member_announcements() where announcement_id=(select id from boundary_ids where t=1 and k='promo')),0,'ANC boundary: 1 pending_null promo feed');
select is(public.mark_announcement_read((select id from boundary_ids where t=1 and k='promo'),1),false,'ANC boundary: 1 pending_null promo marker matches current audience');
set local role postgres;
select pg_temp.claim('member',null,108,1008,1);
set local role authenticated;
select is((select count(*)::integer from public.read_member_announcements() where announcement_id=(select id from boundary_ids where t=1 and k='live')),0,'ANC boundary: 1 expired_today live feed');
select is(public.mark_announcement_read((select id from boundary_ids where t=1 and k='live'),1),false,'ANC boundary: 1 expired_today live marker matches current audience');
select is((select count(*)::integer from public.read_member_announcements() where announcement_id=(select id from boundary_ids where t=1 and k='not_live')),1,'ANC boundary: 1 expired_today not_live feed');
select is(public.mark_announcement_read((select id from boundary_ids where t=1 and k='not_live'),1),true,'ANC boundary: 1 expired_today not_live marker matches current audience');
select is((select count(*)::integer from public.read_member_announcements() where announcement_id=(select id from boundary_ids where t=1 and k='all')),1,'ANC boundary: 1 expired_today all feed');
select is(public.mark_announcement_read((select id from boundary_ids where t=1 and k='all'),1),true,'ANC boundary: 1 expired_today all marker matches current audience');
select is((select count(*)::integer from public.read_member_announcements() where announcement_id=(select id from boundary_ids where t=1 and k='promo')),0,'ANC boundary: 1 expired_today promo feed');
select is(public.mark_announcement_read((select id from boundary_ids where t=1 and k='promo'),1),false,'ANC boundary: 1 expired_today promo marker matches current audience');
set local role postgres;
select pg_temp.claim('member',null,109,1009,1);
set local role authenticated;
select is((select count(*)::integer from public.read_member_announcements() where announcement_id=(select id from boundary_ids where t=1 and k='live')),0,'ANC boundary: 1 cancelled_today live feed');
select is(public.mark_announcement_read((select id from boundary_ids where t=1 and k='live'),1),false,'ANC boundary: 1 cancelled_today live marker matches current audience');
select is((select count(*)::integer from public.read_member_announcements() where announcement_id=(select id from boundary_ids where t=1 and k='not_live')),1,'ANC boundary: 1 cancelled_today not_live feed');
select is(public.mark_announcement_read((select id from boundary_ids where t=1 and k='not_live'),1),true,'ANC boundary: 1 cancelled_today not_live marker matches current audience');
select is((select count(*)::integer from public.read_member_announcements() where announcement_id=(select id from boundary_ids where t=1 and k='all')),1,'ANC boundary: 1 cancelled_today all feed');
select is(public.mark_announcement_read((select id from boundary_ids where t=1 and k='all'),1),true,'ANC boundary: 1 cancelled_today all marker matches current audience');
select is((select count(*)::integer from public.read_member_announcements() where announcement_id=(select id from boundary_ids where t=1 and k='promo')),0,'ANC boundary: 1 cancelled_today promo feed');
select is(public.mark_announcement_read((select id from boundary_ids where t=1 and k='promo'),1),false,'ANC boundary: 1 cancelled_today promo marker matches current audience');
set local role postgres;
select pg_temp.claim('member',null,110,1010,1);
set local role authenticated;
select is((select count(*)::integer from public.read_member_announcements() where announcement_id=(select id from boundary_ids where t=1 and k='live')),0,'ANC boundary: 1 no_membership live feed');
select is(public.mark_announcement_read((select id from boundary_ids where t=1 and k='live'),1),false,'ANC boundary: 1 no_membership live marker matches current audience');
select is((select count(*)::integer from public.read_member_announcements() where announcement_id=(select id from boundary_ids where t=1 and k='not_live')),1,'ANC boundary: 1 no_membership not_live feed');
select is(public.mark_announcement_read((select id from boundary_ids where t=1 and k='not_live'),1),true,'ANC boundary: 1 no_membership not_live marker matches current audience');
select is((select count(*)::integer from public.read_member_announcements() where announcement_id=(select id from boundary_ids where t=1 and k='all')),1,'ANC boundary: 1 no_membership all feed');
select is(public.mark_announcement_read((select id from boundary_ids where t=1 and k='all'),1),true,'ANC boundary: 1 no_membership all marker matches current audience');
select is((select count(*)::integer from public.read_member_announcements() where announcement_id=(select id from boundary_ids where t=1 and k='promo')),0,'ANC boundary: 1 no_membership promo feed');
select is(public.mark_announcement_read((select id from boundary_ids where t=1 and k='promo'),1),false,'ANC boundary: 1 no_membership promo marker matches current audience');
set local role postgres;
select pg_temp.claim('member',null,111,1011,1);
set local role authenticated;
select is((select count(*)::integer from public.read_member_announcements() where announcement_id=(select id from boundary_ids where t=1 and k='live')),1,'ANC boundary: 1 any_qualifying live feed');
select is(public.mark_announcement_read((select id from boundary_ids where t=1 and k='live'),1),true,'ANC boundary: 1 any_qualifying live marker matches current audience');
select is((select count(*)::integer from public.read_member_announcements() where announcement_id=(select id from boundary_ids where t=1 and k='not_live')),0,'ANC boundary: 1 any_qualifying not_live feed');
select is(public.mark_announcement_read((select id from boundary_ids where t=1 and k='not_live'),1),false,'ANC boundary: 1 any_qualifying not_live marker matches current audience');
select is((select count(*)::integer from public.read_member_announcements() where announcement_id=(select id from boundary_ids where t=1 and k='all')),1,'ANC boundary: 1 any_qualifying all feed');
select is(public.mark_announcement_read((select id from boundary_ids where t=1 and k='all'),1),true,'ANC boundary: 1 any_qualifying all marker matches current audience');
select is((select count(*)::integer from public.read_member_announcements() where announcement_id=(select id from boundary_ids where t=1 and k='promo')),0,'ANC boundary: 1 any_qualifying promo feed');
select is(public.mark_announcement_read((select id from boundary_ids where t=1 and k='promo'),1),false,'ANC boundary: 1 any_qualifying promo marker matches current audience');
set local role postgres;
select pg_temp.claim('member',null,112,1012,1);
set local role authenticated;
select is(pg_temp.refusal($q$select * from public.read_member_announcements()$q$),'42501','ANC boundary: 1 blocked_live live feed actor guard preserved');
select is(pg_temp.refusal($q$select public.mark_announcement_read((select id from boundary_ids where t=1 and k='live'),1)$q$),'42501','ANC boundary: 1 blocked_live live marker actor guard preserved');
select is(pg_temp.refusal($q$select * from public.read_member_announcements()$q$),'42501','ANC boundary: 1 blocked_live not_live feed actor guard preserved');
select is(pg_temp.refusal($q$select public.mark_announcement_read((select id from boundary_ids where t=1 and k='not_live'),1)$q$),'42501','ANC boundary: 1 blocked_live not_live marker actor guard preserved');
select is(pg_temp.refusal($q$select * from public.read_member_announcements()$q$),'42501','ANC boundary: 1 blocked_live all feed actor guard preserved');
select is(pg_temp.refusal($q$select public.mark_announcement_read((select id from boundary_ids where t=1 and k='all'),1)$q$),'42501','ANC boundary: 1 blocked_live all marker actor guard preserved');
select is(pg_temp.refusal($q$select * from public.read_member_announcements()$q$),'42501','ANC boundary: 1 blocked_live promo feed actor guard preserved');
select is(pg_temp.refusal($q$select public.mark_announcement_read((select id from boundary_ids where t=1 and k='promo'),1)$q$),'42501','ANC boundary: 1 blocked_live promo marker actor guard preserved');
set local role postgres;
select pg_temp.claim('member',null,113,1013,1);
set local role authenticated;
select is(pg_temp.refusal($q$select * from public.read_member_announcements()$q$),'42501','ANC boundary: 1 erased_live live feed actor guard preserved');
select is(pg_temp.refusal($q$select public.mark_announcement_read((select id from boundary_ids where t=1 and k='live'),1)$q$),'42501','ANC boundary: 1 erased_live live marker actor guard preserved');
select is(pg_temp.refusal($q$select * from public.read_member_announcements()$q$),'42501','ANC boundary: 1 erased_live not_live feed actor guard preserved');
select is(pg_temp.refusal($q$select public.mark_announcement_read((select id from boundary_ids where t=1 and k='not_live'),1)$q$),'42501','ANC boundary: 1 erased_live not_live marker actor guard preserved');
select is(pg_temp.refusal($q$select * from public.read_member_announcements()$q$),'42501','ANC boundary: 1 erased_live all feed actor guard preserved');
select is(pg_temp.refusal($q$select public.mark_announcement_read((select id from boundary_ids where t=1 and k='all'),1)$q$),'42501','ANC boundary: 1 erased_live all marker actor guard preserved');
select is(pg_temp.refusal($q$select * from public.read_member_announcements()$q$),'42501','ANC boundary: 1 erased_live promo feed actor guard preserved');
select is(pg_temp.refusal($q$select public.mark_announcement_read((select id from boundary_ids where t=1 and k='promo'),1)$q$),'42501','ANC boundary: 1 erased_live promo marker actor guard preserved');
set local role postgres;
select pg_temp.claim('member',null,114,1014,2);
set local role authenticated;
select is((select count(*)::integer from public.read_member_announcements() where announcement_id=(select id from boundary_ids where t=2 and k='live')),1,'ANC boundary: 2 active_today live feed');
select is(public.mark_announcement_read((select id from boundary_ids where t=2 and k='live'),1),true,'ANC boundary: 2 active_today live marker matches current audience');
select is((select count(*)::integer from public.read_member_announcements() where announcement_id=(select id from boundary_ids where t=2 and k='not_live')),0,'ANC boundary: 2 active_today not_live feed');
select is(public.mark_announcement_read((select id from boundary_ids where t=2 and k='not_live'),1),false,'ANC boundary: 2 active_today not_live marker matches current audience');
select is((select count(*)::integer from public.read_member_announcements() where announcement_id=(select id from boundary_ids where t=2 and k='all')),1,'ANC boundary: 2 active_today all feed');
select is(public.mark_announcement_read((select id from boundary_ids where t=2 and k='all'),1),true,'ANC boundary: 2 active_today all marker matches current audience');
select is((select count(*)::integer from public.read_member_announcements() where announcement_id=(select id from boundary_ids where t=2 and k='promo')),0,'ANC boundary: 2 active_today promo feed');
select is(public.mark_announcement_read((select id from boundary_ids where t=2 and k='promo'),1),false,'ANC boundary: 2 active_today promo marker matches current audience');
set local role postgres;
select pg_temp.claim('member',null,115,1015,2);
set local role authenticated;
select is((select count(*)::integer from public.read_member_announcements() where announcement_id=(select id from boundary_ids where t=2 and k='live')),1,'ANC boundary: 2 frozen_today live feed');
select is(public.mark_announcement_read((select id from boundary_ids where t=2 and k='live'),1),true,'ANC boundary: 2 frozen_today live marker matches current audience');
select is((select count(*)::integer from public.read_member_announcements() where announcement_id=(select id from boundary_ids where t=2 and k='not_live')),0,'ANC boundary: 2 frozen_today not_live feed');
select is(public.mark_announcement_read((select id from boundary_ids where t=2 and k='not_live'),1),false,'ANC boundary: 2 frozen_today not_live marker matches current audience');
select is((select count(*)::integer from public.read_member_announcements() where announcement_id=(select id from boundary_ids where t=2 and k='all')),1,'ANC boundary: 2 frozen_today all feed');
select is(public.mark_announcement_read((select id from boundary_ids where t=2 and k='all'),1),true,'ANC boundary: 2 frozen_today all marker matches current audience');
select is((select count(*)::integer from public.read_member_announcements() where announcement_id=(select id from boundary_ids where t=2 and k='promo')),0,'ANC boundary: 2 frozen_today promo feed');
select is(public.mark_announcement_read((select id from boundary_ids where t=2 and k='promo'),1),false,'ANC boundary: 2 frozen_today promo marker matches current audience');
set local role postgres;
select pg_temp.claim('member',null,116,1016,2);
set local role authenticated;
select is((select count(*)::integer from public.read_member_announcements() where announcement_id=(select id from boundary_ids where t=2 and k='live')),0,'ANC boundary: 2 active_starts_tomorrow live feed');
select is(public.mark_announcement_read((select id from boundary_ids where t=2 and k='live'),1),false,'ANC boundary: 2 active_starts_tomorrow live marker matches current audience');
select is((select count(*)::integer from public.read_member_announcements() where announcement_id=(select id from boundary_ids where t=2 and k='not_live')),1,'ANC boundary: 2 active_starts_tomorrow not_live feed');
select is(public.mark_announcement_read((select id from boundary_ids where t=2 and k='not_live'),1),true,'ANC boundary: 2 active_starts_tomorrow not_live marker matches current audience');
select is((select count(*)::integer from public.read_member_announcements() where announcement_id=(select id from boundary_ids where t=2 and k='all')),1,'ANC boundary: 2 active_starts_tomorrow all feed');
select is(public.mark_announcement_read((select id from boundary_ids where t=2 and k='all'),1),true,'ANC boundary: 2 active_starts_tomorrow all marker matches current audience');
select is((select count(*)::integer from public.read_member_announcements() where announcement_id=(select id from boundary_ids where t=2 and k='promo')),0,'ANC boundary: 2 active_starts_tomorrow promo feed');
select is(public.mark_announcement_read((select id from boundary_ids where t=2 and k='promo'),1),false,'ANC boundary: 2 active_starts_tomorrow promo marker matches current audience');
set local role postgres;
select pg_temp.claim('member',null,117,1017,2);
set local role authenticated;
select is((select count(*)::integer from public.read_member_announcements() where announcement_id=(select id from boundary_ids where t=2 and k='live')),0,'ANC boundary: 2 active_ended_yesterday live feed');
select is(public.mark_announcement_read((select id from boundary_ids where t=2 and k='live'),1),false,'ANC boundary: 2 active_ended_yesterday live marker matches current audience');
select is((select count(*)::integer from public.read_member_announcements() where announcement_id=(select id from boundary_ids where t=2 and k='not_live')),1,'ANC boundary: 2 active_ended_yesterday not_live feed');
select is(public.mark_announcement_read((select id from boundary_ids where t=2 and k='not_live'),1),true,'ANC boundary: 2 active_ended_yesterday not_live marker matches current audience');
select is((select count(*)::integer from public.read_member_announcements() where announcement_id=(select id from boundary_ids where t=2 and k='all')),1,'ANC boundary: 2 active_ended_yesterday all feed');
select is(public.mark_announcement_read((select id from boundary_ids where t=2 and k='all'),1),true,'ANC boundary: 2 active_ended_yesterday all marker matches current audience');
select is((select count(*)::integer from public.read_member_announcements() where announcement_id=(select id from boundary_ids where t=2 and k='promo')),0,'ANC boundary: 2 active_ended_yesterday promo feed');
select is(public.mark_announcement_read((select id from boundary_ids where t=2 and k='promo'),1),false,'ANC boundary: 2 active_ended_yesterday promo marker matches current audience');
set local role postgres;
select pg_temp.claim('member',null,118,1018,2);
set local role authenticated;
select is((select count(*)::integer from public.read_member_announcements() where announcement_id=(select id from boundary_ids where t=2 and k='live')),0,'ANC boundary: 2 frozen_starts_tomorrow live feed');
select is(public.mark_announcement_read((select id from boundary_ids where t=2 and k='live'),1),false,'ANC boundary: 2 frozen_starts_tomorrow live marker matches current audience');
select is((select count(*)::integer from public.read_member_announcements() where announcement_id=(select id from boundary_ids where t=2 and k='not_live')),1,'ANC boundary: 2 frozen_starts_tomorrow not_live feed');
select is(public.mark_announcement_read((select id from boundary_ids where t=2 and k='not_live'),1),true,'ANC boundary: 2 frozen_starts_tomorrow not_live marker matches current audience');
select is((select count(*)::integer from public.read_member_announcements() where announcement_id=(select id from boundary_ids where t=2 and k='all')),1,'ANC boundary: 2 frozen_starts_tomorrow all feed');
select is(public.mark_announcement_read((select id from boundary_ids where t=2 and k='all'),1),true,'ANC boundary: 2 frozen_starts_tomorrow all marker matches current audience');
select is((select count(*)::integer from public.read_member_announcements() where announcement_id=(select id from boundary_ids where t=2 and k='promo')),0,'ANC boundary: 2 frozen_starts_tomorrow promo feed');
select is(public.mark_announcement_read((select id from boundary_ids where t=2 and k='promo'),1),false,'ANC boundary: 2 frozen_starts_tomorrow promo marker matches current audience');
set local role postgres;
select pg_temp.claim('member',null,119,1019,2);
set local role authenticated;
select is((select count(*)::integer from public.read_member_announcements() where announcement_id=(select id from boundary_ids where t=2 and k='live')),0,'ANC boundary: 2 frozen_ended_yesterday live feed');
select is(public.mark_announcement_read((select id from boundary_ids where t=2 and k='live'),1),false,'ANC boundary: 2 frozen_ended_yesterday live marker matches current audience');
select is((select count(*)::integer from public.read_member_announcements() where announcement_id=(select id from boundary_ids where t=2 and k='not_live')),1,'ANC boundary: 2 frozen_ended_yesterday not_live feed');
select is(public.mark_announcement_read((select id from boundary_ids where t=2 and k='not_live'),1),true,'ANC boundary: 2 frozen_ended_yesterday not_live marker matches current audience');
select is((select count(*)::integer from public.read_member_announcements() where announcement_id=(select id from boundary_ids where t=2 and k='all')),1,'ANC boundary: 2 frozen_ended_yesterday all feed');
select is(public.mark_announcement_read((select id from boundary_ids where t=2 and k='all'),1),true,'ANC boundary: 2 frozen_ended_yesterday all marker matches current audience');
select is((select count(*)::integer from public.read_member_announcements() where announcement_id=(select id from boundary_ids where t=2 and k='promo')),0,'ANC boundary: 2 frozen_ended_yesterday promo feed');
select is(public.mark_announcement_read((select id from boundary_ids where t=2 and k='promo'),1),false,'ANC boundary: 2 frozen_ended_yesterday promo marker matches current audience');
set local role postgres;
select pg_temp.claim('member',null,120,1020,2);
set local role authenticated;
select is((select count(*)::integer from public.read_member_announcements() where announcement_id=(select id from boundary_ids where t=2 and k='live')),0,'ANC boundary: 2 pending_null live feed');
select is(public.mark_announcement_read((select id from boundary_ids where t=2 and k='live'),1),false,'ANC boundary: 2 pending_null live marker matches current audience');
select is((select count(*)::integer from public.read_member_announcements() where announcement_id=(select id from boundary_ids where t=2 and k='not_live')),1,'ANC boundary: 2 pending_null not_live feed');
select is(public.mark_announcement_read((select id from boundary_ids where t=2 and k='not_live'),1),true,'ANC boundary: 2 pending_null not_live marker matches current audience');
select is((select count(*)::integer from public.read_member_announcements() where announcement_id=(select id from boundary_ids where t=2 and k='all')),1,'ANC boundary: 2 pending_null all feed');
select is(public.mark_announcement_read((select id from boundary_ids where t=2 and k='all'),1),true,'ANC boundary: 2 pending_null all marker matches current audience');
select is((select count(*)::integer from public.read_member_announcements() where announcement_id=(select id from boundary_ids where t=2 and k='promo')),0,'ANC boundary: 2 pending_null promo feed');
select is(public.mark_announcement_read((select id from boundary_ids where t=2 and k='promo'),1),false,'ANC boundary: 2 pending_null promo marker matches current audience');
set local role postgres;
select pg_temp.claim('member',null,121,1021,2);
set local role authenticated;
select is((select count(*)::integer from public.read_member_announcements() where announcement_id=(select id from boundary_ids where t=2 and k='live')),0,'ANC boundary: 2 expired_today live feed');
select is(public.mark_announcement_read((select id from boundary_ids where t=2 and k='live'),1),false,'ANC boundary: 2 expired_today live marker matches current audience');
select is((select count(*)::integer from public.read_member_announcements() where announcement_id=(select id from boundary_ids where t=2 and k='not_live')),1,'ANC boundary: 2 expired_today not_live feed');
select is(public.mark_announcement_read((select id from boundary_ids where t=2 and k='not_live'),1),true,'ANC boundary: 2 expired_today not_live marker matches current audience');
select is((select count(*)::integer from public.read_member_announcements() where announcement_id=(select id from boundary_ids where t=2 and k='all')),1,'ANC boundary: 2 expired_today all feed');
select is(public.mark_announcement_read((select id from boundary_ids where t=2 and k='all'),1),true,'ANC boundary: 2 expired_today all marker matches current audience');
select is((select count(*)::integer from public.read_member_announcements() where announcement_id=(select id from boundary_ids where t=2 and k='promo')),0,'ANC boundary: 2 expired_today promo feed');
select is(public.mark_announcement_read((select id from boundary_ids where t=2 and k='promo'),1),false,'ANC boundary: 2 expired_today promo marker matches current audience');
set local role postgres;
select pg_temp.claim('member',null,122,1022,2);
set local role authenticated;
select is((select count(*)::integer from public.read_member_announcements() where announcement_id=(select id from boundary_ids where t=2 and k='live')),0,'ANC boundary: 2 cancelled_today live feed');
select is(public.mark_announcement_read((select id from boundary_ids where t=2 and k='live'),1),false,'ANC boundary: 2 cancelled_today live marker matches current audience');
select is((select count(*)::integer from public.read_member_announcements() where announcement_id=(select id from boundary_ids where t=2 and k='not_live')),1,'ANC boundary: 2 cancelled_today not_live feed');
select is(public.mark_announcement_read((select id from boundary_ids where t=2 and k='not_live'),1),true,'ANC boundary: 2 cancelled_today not_live marker matches current audience');
select is((select count(*)::integer from public.read_member_announcements() where announcement_id=(select id from boundary_ids where t=2 and k='all')),1,'ANC boundary: 2 cancelled_today all feed');
select is(public.mark_announcement_read((select id from boundary_ids where t=2 and k='all'),1),true,'ANC boundary: 2 cancelled_today all marker matches current audience');
select is((select count(*)::integer from public.read_member_announcements() where announcement_id=(select id from boundary_ids where t=2 and k='promo')),0,'ANC boundary: 2 cancelled_today promo feed');
select is(public.mark_announcement_read((select id from boundary_ids where t=2 and k='promo'),1),false,'ANC boundary: 2 cancelled_today promo marker matches current audience');
set local role postgres;
select pg_temp.claim('member',null,123,1023,2);
set local role authenticated;
select is((select count(*)::integer from public.read_member_announcements() where announcement_id=(select id from boundary_ids where t=2 and k='live')),0,'ANC boundary: 2 no_membership live feed');
select is(public.mark_announcement_read((select id from boundary_ids where t=2 and k='live'),1),false,'ANC boundary: 2 no_membership live marker matches current audience');
select is((select count(*)::integer from public.read_member_announcements() where announcement_id=(select id from boundary_ids where t=2 and k='not_live')),1,'ANC boundary: 2 no_membership not_live feed');
select is(public.mark_announcement_read((select id from boundary_ids where t=2 and k='not_live'),1),true,'ANC boundary: 2 no_membership not_live marker matches current audience');
select is((select count(*)::integer from public.read_member_announcements() where announcement_id=(select id from boundary_ids where t=2 and k='all')),1,'ANC boundary: 2 no_membership all feed');
select is(public.mark_announcement_read((select id from boundary_ids where t=2 and k='all'),1),true,'ANC boundary: 2 no_membership all marker matches current audience');
select is((select count(*)::integer from public.read_member_announcements() where announcement_id=(select id from boundary_ids where t=2 and k='promo')),0,'ANC boundary: 2 no_membership promo feed');
select is(public.mark_announcement_read((select id from boundary_ids where t=2 and k='promo'),1),false,'ANC boundary: 2 no_membership promo marker matches current audience');
set local role postgres;
select pg_temp.claim('member',null,124,1024,2);
set local role authenticated;
select is((select count(*)::integer from public.read_member_announcements() where announcement_id=(select id from boundary_ids where t=2 and k='live')),1,'ANC boundary: 2 any_qualifying live feed');
select is(public.mark_announcement_read((select id from boundary_ids where t=2 and k='live'),1),true,'ANC boundary: 2 any_qualifying live marker matches current audience');
select is((select count(*)::integer from public.read_member_announcements() where announcement_id=(select id from boundary_ids where t=2 and k='not_live')),0,'ANC boundary: 2 any_qualifying not_live feed');
select is(public.mark_announcement_read((select id from boundary_ids where t=2 and k='not_live'),1),false,'ANC boundary: 2 any_qualifying not_live marker matches current audience');
select is((select count(*)::integer from public.read_member_announcements() where announcement_id=(select id from boundary_ids where t=2 and k='all')),1,'ANC boundary: 2 any_qualifying all feed');
select is(public.mark_announcement_read((select id from boundary_ids where t=2 and k='all'),1),true,'ANC boundary: 2 any_qualifying all marker matches current audience');
select is((select count(*)::integer from public.read_member_announcements() where announcement_id=(select id from boundary_ids where t=2 and k='promo')),0,'ANC boundary: 2 any_qualifying promo feed');
select is(public.mark_announcement_read((select id from boundary_ids where t=2 and k='promo'),1),false,'ANC boundary: 2 any_qualifying promo marker matches current audience');
set local role postgres;
select pg_temp.claim('member',null,125,1025,2);
set local role authenticated;
select is(pg_temp.refusal($q$select * from public.read_member_announcements()$q$),'42501','ANC boundary: 2 blocked_live live feed actor guard preserved');
select is(pg_temp.refusal($q$select public.mark_announcement_read((select id from boundary_ids where t=2 and k='live'),1)$q$),'42501','ANC boundary: 2 blocked_live live marker actor guard preserved');
select is(pg_temp.refusal($q$select * from public.read_member_announcements()$q$),'42501','ANC boundary: 2 blocked_live not_live feed actor guard preserved');
select is(pg_temp.refusal($q$select public.mark_announcement_read((select id from boundary_ids where t=2 and k='not_live'),1)$q$),'42501','ANC boundary: 2 blocked_live not_live marker actor guard preserved');
select is(pg_temp.refusal($q$select * from public.read_member_announcements()$q$),'42501','ANC boundary: 2 blocked_live all feed actor guard preserved');
select is(pg_temp.refusal($q$select public.mark_announcement_read((select id from boundary_ids where t=2 and k='all'),1)$q$),'42501','ANC boundary: 2 blocked_live all marker actor guard preserved');
select is(pg_temp.refusal($q$select * from public.read_member_announcements()$q$),'42501','ANC boundary: 2 blocked_live promo feed actor guard preserved');
select is(pg_temp.refusal($q$select public.mark_announcement_read((select id from boundary_ids where t=2 and k='promo'),1)$q$),'42501','ANC boundary: 2 blocked_live promo marker actor guard preserved');
set local role postgres;
select pg_temp.claim('member',null,126,1026,2);
set local role authenticated;
select is(pg_temp.refusal($q$select * from public.read_member_announcements()$q$),'42501','ANC boundary: 2 erased_live live feed actor guard preserved');
select is(pg_temp.refusal($q$select public.mark_announcement_read((select id from boundary_ids where t=2 and k='live'),1)$q$),'42501','ANC boundary: 2 erased_live live marker actor guard preserved');
select is(pg_temp.refusal($q$select * from public.read_member_announcements()$q$),'42501','ANC boundary: 2 erased_live not_live feed actor guard preserved');
select is(pg_temp.refusal($q$select public.mark_announcement_read((select id from boundary_ids where t=2 and k='not_live'),1)$q$),'42501','ANC boundary: 2 erased_live not_live marker actor guard preserved');
select is(pg_temp.refusal($q$select * from public.read_member_announcements()$q$),'42501','ANC boundary: 2 erased_live all feed actor guard preserved');
select is(pg_temp.refusal($q$select public.mark_announcement_read((select id from boundary_ids where t=2 and k='all'),1)$q$),'42501','ANC boundary: 2 erased_live all marker actor guard preserved');
select is(pg_temp.refusal($q$select * from public.read_member_announcements()$q$),'42501','ANC boundary: 2 erased_live promo feed actor guard preserved');
select is(pg_temp.refusal($q$select public.mark_announcement_read((select id from boundary_ids where t=2 and k='promo'),1)$q$),'42501','ANC boundary: 2 erased_live promo marker actor guard preserved');
set local role postgres;
select set_config('request.jwt.claims','',true);
-- Missing marketing consent withheld promotional exposure above; a latest grant
-- now admits the live endpoint member without changing membership or service consent.
insert into public.consents(id,tenant_id,member_id,purpose,granted,version,source,recorded_at) values(pg_temp.u(401),pg_temp.u(1),pg_temp.u(101),'marketing',true,'v1','signup',statement_timestamp());
select pg_temp.claim('member',null,101,1001,1);
set local role authenticated;
select is((select count(*)::integer from public.read_member_announcements() where announcement_id=(select id from boundary_ids where t=1 and k='promo')),1,'ANC boundary: granted marketing preserves live promotional exposure');
select ok(public.mark_announcement_read((select id from boundary_ids where t=1 and k='promo'),1),'ANC boundary: granted marketing permits read marker');
set local role postgres;
select set_config('request.jwt.claims','',true);
insert into public.consents(id,tenant_id,member_id,purpose,granted,version,source,recorded_at) values(pg_temp.u(402),pg_temp.u(1),pg_temp.u(101),'marketing',false,'v2','signup',statement_timestamp()+interval '1 second');
select pg_temp.claim('member',null,101,1001,1);
set local role authenticated;
select is((select count(*)::integer from public.read_member_announcements() where announcement_id=(select id from boundary_ids where t=1 and k='promo')),0,'ANC boundary: latest withdrawal still removes live promotional exposure');
select ok(not public.mark_announcement_read((select id from boundary_ids where t=1 and k='promo'),1),'ANC boundary: withdrawal still refuses marker');
set local role postgres;
select pg_temp.claim('gym_owner',21,null,921,1);
set local role authenticated;
select is((select read_current from public.list_announcements() where announcement_id=(select id from boundary_ids where t=1 and k='live')),3,'ANC boundary: live current receipt count follows inclusive audience');
select is((select read_current from public.list_announcements() where announcement_id=(select id from boundary_ids where t=1 and k='not_live')),8,'ANC boundary: inverse current receipt count follows audience');
select is((select read_current from public.list_announcements() where announcement_id=(select id from boundary_ids where t=1 and k='promo')),0,'ANC boundary: withdrawn prior promotional reader excluded from aggregate');
-- Positive active/frozen null dates are legacy compatibility only: current schema
-- disallows those rows. This suite never disables guards to counterfeit eligibility.
set local role postgres;
select is((select count(*)::integer from app.announcement_audience((select id from boundary_ids where t=1 and k='live'))),3,'ANC boundary: tenant 1 live shared delivery audience matches current dates');
select is((select count(*)::integer from app.announcement_audience((select id from boundary_ids where t=1 and k='not_live'))),8,'ANC boundary: tenant 1 not_live shared delivery audience matches current dates');
select is((select count(*)::integer from app.announcement_audience((select id from boundary_ids where t=1 and k='all'))),11,'ANC boundary: tenant 1 all shared delivery audience matches current dates');
select is((select count(*)::integer from app.announcement_audience((select id from boundary_ids where t=1 and k='promo'))),0,'ANC boundary: tenant 1 promo shared delivery audience matches current dates');
select is((select count(*)::integer from app.announcement_audience((select id from boundary_ids where t=2 and k='live'))),3,'ANC boundary: tenant 2 live shared delivery audience matches current dates');
select is((select count(*)::integer from app.announcement_audience((select id from boundary_ids where t=2 and k='not_live'))),8,'ANC boundary: tenant 2 not_live shared delivery audience matches current dates');
select is((select count(*)::integer from app.announcement_audience((select id from boundary_ids where t=2 and k='all'))),11,'ANC boundary: tenant 2 all shared delivery audience matches current dates');
select is((select count(*)::integer from app.announcement_audience((select id from boundary_ids where t=2 and k='promo'))),0,'ANC boundary: tenant 2 promo shared delivery audience matches current dates');
select * from finish();
rollback;
