-- ANC-001..025 independent visible contract. No cross-session concurrency claimed.
begin;
set local role postgres;
set local search_path=extensions,public;
select set_config('request.jwt.claims','',true);
select plan(157);
create function pg_temp.aid(n integer) returns uuid language sql immutable as $$select ('75000000-0000-4000-8000-'||lpad(n::text,12,'0'))::uuid$$;
create function pg_temp.anc_claim(r text default 'gym_owner',s integer default 21,m integer default null,u integer default 901,t integer default 1,p boolean default false) returns void language plpgsql as $$begin perform set_config('request.jwt.claims',jsonb_strip_nulls(jsonb_build_object('sub',pg_temp.aid(u),'role','authenticated','app_role',r,'tenant_id',pg_temp.aid(t),'staff_id',case when s is not null then pg_temp.aid(s) end,'member_id',case when m is not null then pg_temp.aid(m) end,'impersonation_session_id',case when p then pg_temp.aid(999) end))::text,true); end$$;
create function pg_temp.anc_refusal(q text) returns text language plpgsql as $$declare detail text; begin begin execute q; raise exception using errcode='Z7500'; exception when others then if sqlstate='Z7500' then return 'SUCCESS'; end if; get stacked diagnostics detail=PG_EXCEPTION_DETAIL; return sqlstate||case when detail<>'' then ':'||detail else '' end; end; end$$;
create temp table anc_ids(k text primary key,id uuid not null);
grant all on anc_ids to authenticated,service_role;
grant execute on function pg_temp.aid(integer),pg_temp.anc_claim(text,integer,integer,integer,integer,boolean),pg_temp.anc_refusal(text) to authenticated,anon,service_role;
select enum_has_labels('public','announcement_kind',array['transactional','promotional']::name[],'ANC-016: canonical announcement_kind');
select enum_has_labels('public','announcement_status',array['draft','published','unpublished','discarded']::name[],'ANC-016: canonical announcement_status');
select enum_has_labels('public','announcement_audience',array['all_members','segment']::name[],'ANC-016: canonical announcement_audience');
select enum_has_labels('public','announcement_membership_filter',array['any','live','not_live']::name[],'ANC-016: canonical announcement_membership_filter');
select ok(exists(select 1 from pg_enum e join pg_type t on t.oid=e.enumtypid where t.typname='message_category' and e.enumlabel='announcement'),'ANC-022: prelude category exists');
select results_eq($q$select attname::text collate "default" from pg_attribute where attrelid='public.announcements'::regclass and attnum>0 and not attisdropped order by attname::text collate "default"$q$,$q$select * from (values('audience' collate "default"),('closed_at' collate "default"),('created_at' collate "default"),('created_by_staff_id' collate "default"),('current_version' collate "default"),('expires_at' collate "default"),('id' collate "default"),('kind' collate "default"),('published_at' collate "default"),('segment_member_statuses' collate "default"),('segment_membership' collate "default"),('status' collate "default"),('tenant_id' collate "default"),('updated_at' collate "default")) as expected order by column1 collate "default"$q$,'ANC-016: exact announcements columns');
select ok((select relrowsecurity from pg_class where oid='public.announcements'::regclass) and has_table_privilege('authenticated','public.announcements','SELECT') and not has_table_privilege('authenticated','public.announcements','INSERT') and not has_table_privilege('authenticated','public.announcements','UPDATE') and not has_table_privilege('authenticated','public.announcements','DELETE'),'ANC-016: announcements read-only grants and RLS');
select results_eq($q$select polname::text collate "default" from pg_policy where polrelid='public.announcements'::regclass order by polname$q$,$q$select * from (values('announcements_tenant_select' collate "default")) as expected$q$,'ANC-016: announcements only contract policy');
select results_eq($q$select attname::text collate "default" from pg_attribute where attrelid='public.announcement_versions'::regclass and attnum>0 and not attisdropped order by attname$q$,$q$select * from (values('announcement_id' collate "default"),('body' collate "default"),('change_note' collate "default"),('created_at' collate "default"),('created_by_staff_id' collate "default"),('id' collate "default"),('image_asset_id' collate "default"),('tenant_id' collate "default"),('title' collate "default"),('version_no' collate "default")) as expected$q$,'ANC-016: exact announcement_versions columns');
select ok((select relrowsecurity from pg_class where oid='public.announcement_versions'::regclass) and has_table_privilege('authenticated','public.announcement_versions','SELECT') and not has_table_privilege('authenticated','public.announcement_versions','INSERT') and not has_table_privilege('authenticated','public.announcement_versions','UPDATE') and not has_table_privilege('authenticated','public.announcement_versions','DELETE'),'ANC-016: announcement_versions read-only grants and RLS');
select results_eq($q$select polname::text collate "default" from pg_policy where polrelid='public.announcement_versions'::regclass order by polname$q$,$q$select * from (values('announcement_versions_tenant_select' collate "default")) as expected$q$,'ANC-016: announcement_versions only contract policy');
select results_eq($q$select attname::text collate "default" from pg_attribute where attrelid='public.announcement_receipts'::regclass and attnum>0 and not attisdropped order by attname$q$,$q$select * from (values('created_at' collate "default"),('id' collate "default"),('member_id' collate "default"),('read_at' collate "default"),('tenant_id' collate "default"),('version_id' collate "default")) as expected$q$,'ANC-016: exact announcement_receipts columns');
select ok((select relrowsecurity from pg_class where oid='public.announcement_receipts'::regclass) and has_table_privilege('authenticated','public.announcement_receipts','SELECT') and not has_table_privilege('authenticated','public.announcement_receipts','INSERT') and not has_table_privilege('authenticated','public.announcement_receipts','UPDATE') and not has_table_privilege('authenticated','public.announcement_receipts','DELETE'),'ANC-016: announcement_receipts read-only grants and RLS');
select results_eq($q$select polname::text collate "default" from pg_policy where polrelid='public.announcement_receipts'::regclass order by polname$q$,$q$select * from (values('announcement_receipts_member_select' collate "default")) as expected$q$,'ANC-016: announcement_receipts only contract policy');
select is_empty($q$with expected(sig,vol) as(values('public.create_announcement_draft(public.announcement_kind,text,text,public.announcement_audience,public.member_status[],public.announcement_membership_filter,timestamp with time zone,uuid)','v'),('public.update_announcement_draft(uuid,public.announcement_kind,text,text,public.announcement_audience,public.member_status[],public.announcement_membership_filter,timestamp with time zone,uuid)','v'),('public.discard_announcement_draft(uuid)','v'),('public.publish_announcement(uuid)','v'),('public.edit_announcement(uuid,integer,text,text,uuid,timestamp with time zone,text)','v'),('public.unpublish_announcement(uuid)','v'),('public.list_announcements(timestamp with time zone,uuid)','s'),('public.read_announcement(uuid)','s'),('public.read_member_announcements()','s'),('public.mark_announcement_read(uuid,integer)','v')) select sig from expected e left join pg_proc p on p.oid=to_regprocedure(e.sig) where p.oid is null or not p.prosecdef or p.provolatile::text<>e.vol or pg_get_userbyid(p.proowner)<>'postgres' or not coalesce(p.proconfig @> array['search_path=""'],false) or not has_function_privilege('authenticated',p.oid,'EXECUTE') or has_function_privilege('anon',p.oid,'EXECUTE') or has_function_privilege('service_role',p.oid,'EXECUTE')$q$,'ANC-016: ten exact RPC postures');
select ok(has_function_privilege('service_role','app.announcement_audience(uuid,uuid)','EXECUTE') and not has_function_privilege('authenticated','app.announcement_audience(uuid,uuid)','EXECUTE'),'ANC-006: targeting helper NTF-only');
select ok((select pg_get_functiondef('public.publish_announcement(uuid)'::regprocedure) like '%pg_advisory_xact_lock%' and pg_get_functiondef('public.publish_announcement(uuid)'::regprocedure) like '%announcements:%'),'ANC-004: exact tenant-lock namespace present; live race still requires two sessions');
select ok(exists(select 1 from pg_trigger t join pg_proc p on p.oid=t.tgfoid where t.tgrelid='public.announcements'::regclass and t.tgname='announcements_touch_updated_at' and t.tgtype=23 and t.tgenabled='O' and not p.prosecdef and p.proname='enforce_announcement'),'ANC-025: announcements fused invariant trigger');
select ok(exists(select 1 from pg_trigger t join pg_proc p on p.oid=t.tgfoid where t.tgrelid='public.announcement_versions'::regclass and t.tgname='announcement_versions_touch_updated_at' and t.tgtype=27 and t.tgenabled='O' and not p.prosecdef and p.proname='enforce_announcement_version'),'ANC-025: announcement_versions fused invariant trigger');
select is_empty($q$select proargnames::text from pg_proc where oid='public.read_member_announcements()'::regprocedure and (proargnames::text ~* 'object_key|etag|mime')$q$,'ANC-017: public member feed projects asset id only, no private media metadata');
insert into public.organizations(id,name,gym_code,status) values(pg_temp.aid(1),'ANC A','ANC75A','active'),(pg_temp.aid(2),'ANC B','ANC75B','active');
insert into public.branches(id,tenant_id,name,is_default) values(pg_temp.aid(11),pg_temp.aid(1),'A',true),(pg_temp.aid(12),pg_temp.aid(2),'B',true);
insert into auth.users(id) select pg_temp.aid(n) from generate_series(901,914) n;
insert into public.staff(id,tenant_id,user_id,branch_id,role,full_name) values(pg_temp.aid(21),pg_temp.aid(1),pg_temp.aid(901),pg_temp.aid(11),'gym_owner','Owner'),(pg_temp.aid(22),pg_temp.aid(1),pg_temp.aid(902),pg_temp.aid(11),'gym_manager','Manager'),(pg_temp.aid(23),pg_temp.aid(1),pg_temp.aid(903),pg_temp.aid(11),'front_desk','Desk'),(pg_temp.aid(24),pg_temp.aid(1),pg_temp.aid(904),pg_temp.aid(11),'trainer','Trainer'),(pg_temp.aid(25),pg_temp.aid(2),pg_temp.aid(905),pg_temp.aid(12),'gym_owner','Other');
insert into public.members(id,tenant_id,branch_id,user_id,full_name,phone,date_of_birth,status,erased_at) values
(pg_temp.aid(101),pg_temp.aid(1),pg_temp.aid(11),pg_temp.aid(906),'PRIVATE_MEMBER_101','+917500000101','1990-01-01','active',null),(pg_temp.aid(102),pg_temp.aid(1),pg_temp.aid(11),pg_temp.aid(907),'PRIVATE_MEMBER_102','+917500000102','1990-01-01','paused',null),(pg_temp.aid(103),pg_temp.aid(1),pg_temp.aid(11),pg_temp.aid(908),'PRIVATE_MEMBER_103','+917500000103','1990-01-01','expired',null),(pg_temp.aid(104),pg_temp.aid(1),pg_temp.aid(11),pg_temp.aid(909),'PRIVATE_MEMBER_104','+917500000104','1990-01-01','blocked',null),(pg_temp.aid(105),pg_temp.aid(1),pg_temp.aid(11),pg_temp.aid(910),'PRIVATE_MEMBER_105','+917500000105','1990-01-01','cancelled',null),(pg_temp.aid(106),pg_temp.aid(1),pg_temp.aid(11),pg_temp.aid(911),'PRIVATE_MEMBER_106','+917500000106','1990-01-01','active',now()),
(pg_temp.aid(107),pg_temp.aid(2),pg_temp.aid(12),pg_temp.aid(912),'PRIVATE_FOREIGN_MEMBER','+917500000107','1990-01-01','active',null);
insert into public.plans(id,tenant_id,name,duration_days,price_paise) values(pg_temp.aid(201),pg_temp.aid(1),'ANC plan',30,100000);
insert into public.memberships(id,tenant_id,member_id,plan_id,status,starts_on,ends_on,price_paise,currency) values(pg_temp.aid(301),pg_temp.aid(1),pg_temp.aid(101),pg_temp.aid(201),'active',app.gym_today(pg_temp.aid(1))-1,app.gym_today(pg_temp.aid(1))+30,100000,'INR'),(pg_temp.aid(302),pg_temp.aid(1),pg_temp.aid(102),pg_temp.aid(201),'frozen',app.gym_today(pg_temp.aid(1))-1,app.gym_today(pg_temp.aid(1))+30,100000,'INR');
insert into public.consents(id,tenant_id,member_id,purpose,granted,version,source,recorded_at) values(pg_temp.aid(401),pg_temp.aid(1),pg_temp.aid(101),'marketing',true,'v1','signup',now()-interval '1 day'),(pg_temp.aid(402),pg_temp.aid(1),pg_temp.aid(102),'marketing',true,'v1','signup',now()-interval '1 day'),(pg_temp.aid(403),pg_temp.aid(1),pg_temp.aid(102),'marketing',false,'v2','signup',now()),(pg_temp.aid(404),pg_temp.aid(1),pg_temp.aid(101),'service',false,'v1','signup',now());
reset role;
select pg_temp.anc_claim('front_desk',23,null,903,1,false);
set local role authenticated;
insert into anc_ids values('notice',public.create_announcement_draft('transactional',' Notice title ',' Body plain https://example.test ','all_members',null,null,null,null)),('promo',public.create_announcement_draft('promotional',' Notice title ',' Body plain https://example.test ','all_members',null,null,null,null)),('discard',public.create_announcement_draft('transactional',' Notice title ',' Body plain https://example.test ','all_members',null,null,null,null));
select is((select count(*)::integer from public.announcements),3,'ANC-001: desk drafts readable in own tenant');
select is((select title from public.announcement_versions where announcement_id=(select id from anc_ids where k='notice')),'Notice title','ANC-001: draft text trimmed');
select is(pg_temp.anc_refusal($q$select public.publish_announcement((select id from anc_ids where k='notice'))$q$),'42501','ANC-003: desk publish denied');
select lives_ok($q$select public.update_announcement_draft((select id from anc_ids where k='discard'),'promotional','Changed','Changed body','all_members',null,null,null,null)$q$,'ANC-002: front desk full draft replacement');
select lives_ok($q$select public.discard_announcement_draft((select id from anc_ids where k='discard'))$q$,'ANC-002: front desk can discard');
select is(pg_temp.anc_refusal($q$select public.read_announcement((select id from anc_ids where k='discard'))$q$),'42501','ANC-014: discarded detail invisible');
select is((select count(*)::integer from public.list_announcements()),2,'ANC-014: discarded omitted from list');
reset role;
select pg_temp.anc_claim('gym_owner',21,null,901,1,false);
set local role authenticated;
select is(pg_temp.anc_refusal($q$select public.create_announcement_draft('transactional','',' Body plain https://example.test ','all_members',null,null,null,null)$q$),'22023','ANC-001: blank title');
select is(pg_temp.anc_refusal($q$select public.create_announcement_draft('transactional',repeat('x',81),' Body plain https://example.test ','all_members',null,null,null,null)$q$),'22023','ANC-001: title over bound');
select is(pg_temp.anc_refusal($q$select public.create_announcement_draft('transactional','t',repeat('x',1501),'all_members',null,null,null,null)$q$),'22023','ANC-001: body over bound');
select is(pg_temp.anc_refusal($q$select public.create_announcement_draft('transactional','t','b','all_members',array['active']::public.member_status[],'any',null,null)$q$),'22023','ANC-001: all-members segment contradiction');
select is(pg_temp.anc_refusal($q$select public.create_announcement_draft('transactional','t','b','segment',array['active','active']::public.member_status[],'any',null,null)$q$),'22023','ANC-001: duplicate statuses');
select is(pg_temp.anc_refusal($q$select public.create_announcement_draft('transactional','t','b','segment',array['blocked']::public.member_status[],'any',null,null)$q$),'22023','ANC-001: blocked segment');
select lives_ok($q$select public.create_announcement_draft('transactional',repeat('字',80),repeat('字',1500),'all_members',null,null,null,null)$q$,'ANC-001: Unicode character boundaries accepted');
select is(pg_temp.anc_refusal($q$select public.create_announcement_draft('transactional','t','b','all_members',null,null,null,pg_temp.aid(9999))$q$),'GL088:image_unavailable','ANC-017: missing image refused atomically');
create temp table anc_notice_publish as select * from public.publish_announcement((select id from anc_ids where k='notice'));
select is((select audience_count from anc_notice_publish),3,'ANC-005/006: notices reach active paused expired without service grant');
create temp table anc_promo_publish as select * from public.publish_announcement((select id from anc_ids where k='promo'));
select is((select audience_count from anc_promo_publish),1,'ANC-005: promotion count grants only latest marketing true');
select ok((select published_at >= transaction_timestamp() and expires_at is null from anc_notice_publish),'ANC-004: server time and no expiry preserved');
select is(pg_temp.anc_refusal($q$select public.publish_announcement((select id from anc_ids where k='notice'))$q$),'GL088:not_draft','ANC-004: cannot republish');
select is(pg_temp.anc_refusal($q$select public.update_announcement_draft((select id from anc_ids where k='notice'),'promotional','t','b','all_members',null,null,null,null)$q$),'GL088:not_draft','ANC-002: cannot draft-edit published kind');
reset role;
select pg_temp.anc_claim('trainer',24,null,904,1,false);
set local role authenticated;
select is(pg_temp.anc_refusal($q$select public.create_announcement_draft('transactional',' Notice title ',' Body plain https://example.test ','all_members',null,null,null,null)$q$),'42501','ANC-003/014: trainer create refused');
select is(pg_temp.anc_refusal($q$select public.publish_announcement((select id from anc_ids where k='notice'))$q$),'42501','ANC-003/014: trainer publish refused');
select is(pg_temp.anc_refusal($q$select public.list_announcements()$q$),'42501','ANC-003/014: trainer list refused');
select is(pg_temp.anc_refusal($q$select public.edit_announcement((select id from anc_ids where k='notice'),1,'t','b',null,null,'note')$q$),'42501','ANC-003/014: trainer edit refused');
select is(pg_temp.anc_refusal($q$select public.unpublish_announcement((select id from anc_ids where k='notice'))$q$),'42501','ANC-003/014: trainer take down refused');
reset role;
select pg_temp.anc_claim('member',null,101,906,1,false);
set local role authenticated;
select is(pg_temp.anc_refusal($q$select public.create_announcement_draft('transactional',' Notice title ',' Body plain https://example.test ','all_members',null,null,null,null)$q$),'42501','ANC-003/014: member create refused');
select is(pg_temp.anc_refusal($q$select public.publish_announcement((select id from anc_ids where k='notice'))$q$),'42501','ANC-003/014: member publish refused');
select is(pg_temp.anc_refusal($q$select public.list_announcements()$q$),'42501','ANC-003/014: member list refused');
select is(pg_temp.anc_refusal($q$select public.edit_announcement((select id from anc_ids where k='notice'),1,'t','b',null,null,'note')$q$),'42501','ANC-003/014: member edit refused');
select is(pg_temp.anc_refusal($q$select public.unpublish_announcement((select id from anc_ids where k='notice'))$q$),'42501','ANC-003/014: member take down refused');
reset role;
select pg_temp.anc_claim('platform_support',null,null,913,1,false);
set local role authenticated;
select is(pg_temp.anc_refusal($q$select public.create_announcement_draft('transactional',' Notice title ',' Body plain https://example.test ','all_members',null,null,null,null)$q$),'42501','ANC-003/014: platform_support create refused');
select is(pg_temp.anc_refusal($q$select public.publish_announcement((select id from anc_ids where k='notice'))$q$),'42501','ANC-003/014: platform_support publish refused');
select is(pg_temp.anc_refusal($q$select public.list_announcements()$q$),'42501','ANC-003/014: platform_support list refused');
select is(pg_temp.anc_refusal($q$select public.edit_announcement((select id from anc_ids where k='notice'),1,'t','b',null,null,'note')$q$),'42501','ANC-003/014: platform_support edit refused');
select is(pg_temp.anc_refusal($q$select public.unpublish_announcement((select id from anc_ids where k='notice'))$q$),'42501','ANC-003/014: platform_support take down refused');
reset role;
select pg_temp.anc_claim('super_admin',null,null,914,1,false);
set local role authenticated;
select is(pg_temp.anc_refusal($q$select public.create_announcement_draft('transactional',' Notice title ',' Body plain https://example.test ','all_members',null,null,null,null)$q$),'42501','ANC-003/014: super_admin create refused');
select is(pg_temp.anc_refusal($q$select public.publish_announcement((select id from anc_ids where k='notice'))$q$),'42501','ANC-003/014: super_admin publish refused');
select is(pg_temp.anc_refusal($q$select public.list_announcements()$q$),'42501','ANC-003/014: super_admin list refused');
select is(pg_temp.anc_refusal($q$select public.edit_announcement((select id from anc_ids where k='notice'),1,'t','b',null,null,'note')$q$),'42501','ANC-003/014: super_admin edit refused');
select is(pg_temp.anc_refusal($q$select public.unpublish_announcement((select id from anc_ids where k='notice'))$q$),'42501','ANC-003/014: super_admin take down refused');
reset role;
select pg_temp.anc_claim('gym_owner',null,null,914,1,true);
set local role authenticated;
select is(pg_temp.anc_refusal($q$select public.create_announcement_draft('transactional',' Notice title ',' Body plain https://example.test ','all_members',null,null,null,null)$q$),'42501','ANC-003: support-preview mutation denied');
select lives_ok($q$select public.list_announcements()$q$,'ANC-014: preview aggregate reads allowed');
reset role;
select pg_temp.anc_claim('gym_owner',25,null,905,2,false);
set local role authenticated;
select is(pg_temp.anc_refusal($q$select public.read_announcement((select id from anc_ids where k='notice'))$q$),'42501','ANC-016: foreign detail indistinguishable');
select is(pg_temp.anc_refusal($q$select public.edit_announcement((select id from anc_ids where k='notice'),null,null,null,pg_temp.aid(9999),null,null)$q$),'42501','ANC-018: foreign resolution before malformed input');
reset role;
select pg_temp.anc_claim('gym_owner',21,null,901,1,false);
set local role authenticated;
select is(pg_temp.anc_refusal($q$select public.edit_announcement(pg_temp.aid(9999),null,null,null,null,null,null)$q$),'42501','ANC-018: unknown resolution before malformed input');
select is(pg_temp.anc_refusal($q$select public.edit_announcement((select id from anc_ids where k='notice'),99,'t','b',pg_temp.aid(9999),now()-interval '1 day','note')$q$),'GL088:version_conflict','ANC-018: stale version before image/expiry');
select is(pg_temp.anc_refusal($q$select public.edit_announcement((select id from anc_ids where k='notice'),1,'t','b',pg_temp.aid(9999),now()-interval '1 day','note')$q$),'GL088:image_unavailable','ANC-018: image before expiry');
select is(pg_temp.anc_refusal($q$select public.edit_announcement((select id from anc_ids where k='notice'),1,'t','b',null,null,' x ')$q$),'22023','ANC-008: content edit requires three trimmed note characters');
reset role;
select pg_temp.anc_claim('member',null,101,906,1,false);
set local role authenticated;
select is((select count(*)::integer from public.read_member_announcements()),2,'ANC-005: granted member sees notice and promotion');
select is((select read_state from public.read_member_announcements() where announcement_id=(select id from anc_ids where k='notice')),'unread','ANC-012: new card unread');
select ok(public.mark_announcement_read((select id from anc_ids where k='notice'),1),'ANC-011: opening stamps first receipt');
select ok(public.mark_announcement_read((select id from anc_ids where k='notice'),1),'ANC-011: duplicate opening idempotently true');
select is((select count(*)::integer from public.announcement_receipts),1,'ANC-013: only one own receipt');
select is((select read_state from public.read_member_announcements() where announcement_id=(select id from anc_ids where k='notice')),'read','ANC-012: current receipt read');
select ok(not public.mark_announcement_read(pg_temp.aid(9999),1) and not public.mark_announcement_read((select id from anc_ids where k='notice'),999),'ANC-011: unknown announcement/version false without oracle');
reset role;
select pg_temp.anc_claim('member',null,102,907,1,false);
set local role authenticated;
select is((select count(*)::integer from public.read_member_announcements()),1,'ANC-005: withdrawn member still sees transactional notice');
select ok(not public.mark_announcement_read((select id from anc_ids where k='promo'),1),'ANC-005: withdrawn cannot mark promotion read');
select is((select count(*)::integer from public.announcement_receipts),0,'ANC-013: another member receipt invisible');
reset role;
select pg_temp.anc_claim('member',null,103,908,1,false);
set local role authenticated;
select is((select count(*)::integer from public.read_member_announcements()),1,'ANC-005: never asked sees notice only');
reset role;
select pg_temp.anc_claim('gym_owner',21,null,901,1,false);
set local role authenticated;
create temp table anc_edit as select * from public.edit_announcement((select id from anc_ids where k='notice'),1,'Updated title','Updated body',null,null,'Opening time corrected');
select results_eq($q$select version_no,new_version from anc_edit$q$,$q$select 2,true$q$,'ANC-008: edit inserts version two');
select is((select count(*)::integer from public.announcement_versions where announcement_id=(select id from anc_ids where k='notice')),2,'ANC-008: both versions retained');
select is((public.read_announcement((select id from anc_ids where k='notice'))->'versions'->0->>'changeNote'),'Opening time corrected','ANC-014: latest version note first');
select ok(public.read_announcement((select id from anc_ids where k='notice'))::text not like '%PRIVATE_MEMBER_%' and public.read_announcement((select id from anc_ids where k='notice'))::text not like '%'||pg_temp.aid(101)::text||'%','ANC-013: staff detail aggregate-only no receipt identities');
select is((select count(*)::integer from public.announcement_receipts),0,'ANC-013: owner cannot directly inspect receipt rows');
reset role;
select pg_temp.anc_claim('member',null,101,906,1,false);
set local role authenticated;
select is((select read_state from public.read_member_announcements() where announcement_id=(select id from anc_ids where k='notice')),'updated','ANC-012: earlier reader sees Updated');
select is((select change_note from public.read_member_announcements() where announcement_id=(select id from anc_ids where k='notice')),'Opening time corrected','ANC-012: Updated carries owner note');
select ok(public.mark_announcement_read((select id from anc_ids where k='notice'),1),'ANC-011: older version remains markable');
select ok(public.mark_announcement_read((select id from anc_ids where k='notice'),2),'ANC-011: current version receipt separate');
reset role;
select pg_temp.anc_claim('member',null,102,907,1,false);
set local role authenticated;
select is((select read_state from public.read_member_announcements() where announcement_id=(select id from anc_ids where k='notice')),'unread','ANC-012: member never opening v1 sees New after edit');
select ok((select edited_at is not null from public.read_member_announcements() where announcement_id=(select id from anc_ids where k='notice')),'ANC-012: Edited visible even to never-reader');
reset role;
select pg_temp.anc_claim('gym_owner',21,null,901,1,false);
set local role authenticated;
create temp table anc_expiry_edit as select * from public.edit_announcement((select id from anc_ids where k='notice'),2,'Updated title','Updated body',null,now()+interval '1 day',null);
select results_eq($q$select version_no,new_version from anc_expiry_edit$q$,$q$select 2,false$q$,'ANC-009: expiry-only change adds no version or note');
select is(pg_temp.anc_refusal($q$select public.edit_announcement((select id from anc_ids where k='notice'),2,'Updated title','Updated body',null,(select expires_at from public.announcements where id=(select id from anc_ids where k='notice')),null)$q$),'GL088:no_change','ANC-008: exact no-op refused');
reset role;
select set_config('request.jwt.claims','',true);
insert into public.consents(id,tenant_id,member_id,purpose,granted,version,source,recorded_at) values(pg_temp.aid(405),pg_temp.aid(1),pg_temp.aid(101),'marketing',false,'v2','signup',now()+interval '1 second'),(pg_temp.aid(406),pg_temp.aid(1),pg_temp.aid(102),'marketing',true,'v3','signup',now()+interval '1 second');
reset role;
select pg_temp.anc_claim('member',null,101,906,1,false);
set local role authenticated;
select is((select count(*)::integer from public.read_member_announcements() where announcement_id=(select id from anc_ids where k='promo')),0,'ANC-005: later withdrawal immediately removes promotion');
select ok(not public.mark_announcement_read((select id from anc_ids where k='promo'),1),'ANC-005: withdrawal removes read-marker exposure too');
reset role;
select pg_temp.anc_claim('member',null,102,907,1,false);
set local role authenticated;
select is((select count(*)::integer from public.read_member_announcements() where announcement_id=(select id from anc_ids where k='promo')),1,'ANC-005: later grant restores live promotion');
reset role;
select pg_temp.anc_claim('gym_owner',21,null,901,1,false);
set local role authenticated;
select ok((select bool_and(read_current<=audience_count and read_any<=audience_count) from public.list_announcements() where display_status in('draft','live')),'ANC-013: live aggregate counts bounded by current reach');
reset role;
select set_config('request.jwt.claims','',true);
select is(pg_temp.anc_refusal($q$update public.announcements set kind='promotional' where id=(select id from anc_ids where k='notice')$q$),'GL088:field_frozen','ANC-025: postgres published kind frozen');
select is(pg_temp.anc_refusal($q$update public.announcements set tenant_id=pg_temp.aid(2) where id=(select id from anc_ids where k='notice')$q$),'GL088:field_frozen','ANC-025: postgres tenant frozen');
select is(pg_temp.anc_refusal($q$update public.announcements set current_version=current_version+2 where id=(select id from anc_ids where k='notice')$q$),'GL088:invalid_transition','ANC-025: postgres version skip refused');
select is(pg_temp.anc_refusal($q$update public.announcements set status='draft' where id=(select id from anc_ids where k='notice')$q$),'GL088:invalid_transition','ANC-025: postgres published cannot revert');
select is(pg_temp.anc_refusal($q$update public.announcement_versions set title='silent' where announcement_id=(select id from anc_ids where k='notice') and version_no=1$q$),'GL088:version_immutable','ANC-025: postgres historic version update refused');
select is(pg_temp.anc_refusal($q$delete from public.announcement_versions where announcement_id=(select id from anc_ids where k='notice')$q$),'GL088:version_immutable','ANC-025: postgres every historic version DELETE refused');
reset role;
select pg_temp.anc_claim('gym_manager',22,null,902,1,false);
set local role authenticated;
select lives_ok($q$select public.unpublish_announcement((select id from anc_ids where k='notice'))$q$,'ANC-010: manager takes down a published row');
select is(pg_temp.anc_refusal($q$select public.publish_announcement((select id from anc_ids where k='notice'))$q$),'GL088:not_draft','ANC-010: take-down irreversible');
select is(pg_temp.anc_refusal($q$select public.edit_announcement((select id from anc_ids where k='notice'),2,'t','b',null,null,'note')$q$),'GL088:not_live','ANC-010: taken-down content cannot edit');
select ok((public.read_announcement((select id from anc_ids where k='notice'))->'announcement'->>'audienceCount') is null and (public.read_announcement((select id from anc_ids where k='notice'))->'announcement'->>'readAny')::integer=1,'ANC-013: ended counts retain receipts without audience count');
reset role;
select pg_temp.anc_claim('member',null,101,906,1,false);
set local role authenticated;
select is((select count(*)::integer from public.read_member_announcements() where announcement_id=(select id from anc_ids where k='notice')),0,'ANC-010: member feed removes taken down immediately');
select ok(not public.mark_announcement_read((select id from anc_ids where k='notice'),2),'ANC-011: taken down receipt marker false');
reset role;
select set_config('request.jwt.claims','',true);
select is((select count(*)::integer from public.notifications where tenant_id=pg_temp.aid(1)),0,'ANC-022: draft/publish/edit/read writes no notification fanout');
select ok(not exists(select 1 from public.audit_log where tenant_id=pg_temp.aid(1) and action like 'announcement.%' and (coalesce(before::text,'')||coalesce(after::text,'')) ~ 'Notice title|Body plain|Updated title|Updated body|PRIVATE_MEMBER'),'ANC-015: audit contains no content or individual read details');
select ok(exists(select 1 from public.audit_log where tenant_id=pg_temp.aid(1) and action='announcement.edited' and actor_user_id=pg_temp.aid(901) and actor_role='gym_owner' and record_type='announcement' and reason='Opening time corrected' and after->>'content_changed'='true'),'ANC-015: edit audit attributed with note and content-change fact');
select ok(exists(select 1 from public.audit_log where tenant_id=pg_temp.aid(1) and action='announcement.edited' and reason is null and after->>'content_changed'='false'),'ANC-009/015: expiry-only audit truthful');
-- Segmentation is checked through the shared predicate without consuming the
-- live cap: the audience helper is the canonical NTF/count/read seam.
-- MEDIA setup is a credential-trusted finalizer fixture, not R2 verification.
-- Byte verification and concurrent published-object races belong to SHP/live CI.
select pg_temp.anc_claim();
set local role authenticated;
insert into anc_ids values('image',public.register_media_asset('announcement',pg_temp.aid(1)::text||'/staging/announcement/'||pg_temp.aid(501)::text||'.png','image/png',100));
reset role;
select set_config('request.jwt.claims','{"role":"service_role"}',true);
set local role service_role;
select ok(public.finalize_media_asset((select id from anc_ids where k='image'),pg_temp.aid(901),pg_temp.aid(21),'gym_owner',pg_temp.aid(1),'announcement','image/png',100,pg_temp.aid(1)::text||'/staging/announcement/'||pg_temp.aid(501)::text||'.png','source-etag',pg_temp.aid(1)::text||'/published/announcement/'||pg_temp.aid(601)::text||'.png','published-etag'),'ANC-017: eligible credential-trusted media fixture confirmed');
reset role;
select pg_temp.anc_claim();
set local role authenticated;
select lives_ok($q$select public.edit_announcement((select id from anc_ids where k='promo'),1,'Image promotion','Image body',(select id from anc_ids where k='image'),null,'Added decorative image')$q$,'ANC-017: content edit attaches confirmed own image');
reset role;
select ok((select attached_to_id=(select id from anc_ids where k='promo') from public.media_assets where id=(select id from anc_ids where k='image')),'ANC-017: actual parent attachment recorded');
select pg_temp.anc_claim('member',null,102,907);
set local role authenticated;
select is((select image_asset_id from public.read_member_announcements() where announcement_id=(select id from anc_ids where k='promo')),(select id from anc_ids where k='image'),'ANC-017: currently consented visible card exposes only opaque current asset id');
reset role;
select set_config('request.jwt.claims','',true);
insert into public.consents(id,tenant_id,member_id,purpose,granted,version,source,recorded_at) values(pg_temp.aid(407),pg_temp.aid(1),pg_temp.aid(102),'marketing',false,'v4','signup',now()+interval '2 seconds');
select pg_temp.anc_claim('member',null,102,907);
set local role authenticated;
select is((select count(*)::integer from public.read_member_announcements() where image_asset_id=(select id from anc_ids where k='image')),0,'ANC-005/017: withdrawal removes image exposure to signer caller RPC');
reset role;
select set_config('request.jwt.claims','',true);
insert into public.consents(id,tenant_id,member_id,purpose,granted,version,source,recorded_at) values(pg_temp.aid(408),pg_temp.aid(1),pg_temp.aid(102),'marketing',true,'v5','signup',now()+interval '3 seconds');
select pg_temp.anc_claim();
set local role authenticated;
select lives_ok($q$select public.edit_announcement((select id from anc_ids where k='promo'),2,'Removed image','No image body',null,null,'Removed decorative image')$q$,'ANC-017: image removal creates new version');
reset role;
select ok((select deleted_at is not null and attached_to_id is null from public.media_assets where id=(select id from anc_ids where k='image')),'ANC-017: released image metadata tombstoned and detached');
select is((select image_asset_id from public.announcement_versions where announcement_id=(select id from anc_ids where k='promo') and version_no=2),(select id from anc_ids where k='image'),'ANC-017: historic immutable version keeps media FK');
select is(pg_temp.anc_refusal($q$delete from public.media_assets where id=(select id from anc_ids where k='image')$q$),'GL086:media_verification_invariant','ANC-017: object-only pruning never physically deletes historic media metadata');
select pg_temp.anc_claim('member',null,102,907);
set local role authenticated;
select ok((select image_asset_id is null from public.read_member_announcements() where announcement_id=(select id from anc_ids where k='promo')),'ANC-017: old released historic image never revived in current feed');
reset role;
select set_config('request.jwt.claims','',true);
select is((select count(*)::integer from public.announcement_versions where announcement_id=(select id from anc_ids where k='promo')),3,'ANC-017: image add/remove retain all three versions');
select pg_temp.anc_claim();
set local role authenticated;
insert into anc_ids values
('any',public.create_announcement_draft('transactional','Any','Body','segment',array['active','paused','expired']::public.member_status[],'any',null,null)),
('live',public.create_announcement_draft('transactional','Live','Body','segment',array['active','paused','expired']::public.member_status[],'live',null,null)),
('not_live',public.create_announcement_draft('transactional','No live','Body','segment',array['active','paused','expired']::public.member_status[],'not_live',null,null));
reset role;
select results_eq($q$select * from app.announcement_audience((select id from anc_ids where k='any')) order by 1$q$,$q$select * from (values(pg_temp.aid(101)),(pg_temp.aid(102)),(pg_temp.aid(103))) as expected$q$,'ANC-006: all three good-standing statuses, excluding blocked/cancelled/erased/foreign');
select results_eq($q$select * from app.announcement_audience((select id from anc_ids where k='live')) order by 1$q$,$q$select * from (values(pg_temp.aid(101)),(pg_temp.aid(102))) as expected$q$,'ANC-006: active and frozen membership are live');
select results_eq($q$select * from app.announcement_audience((select id from anc_ids where k='not_live')) order by 1$q$,$q$select pg_temp.aid(103)$q$,'ANC-006: no-live filter complement');
select is((select count(*)::integer from app.announcement_audience((select id from anc_ids where k='any'),pg_temp.aid(107))),0,'ANC-006: explicit foreign audience member absent');
-- Sequential cap boundaries are meaningful here. Simultaneous publishes
-- require the separately authored post-CI two-session acceptance test.
select set_config('request.jwt.claims','',true);
select pg_temp.anc_claim();
set local role authenticated;
insert into anc_ids select 'cap'||n,public.create_announcement_draft('transactional','Cap '||n,'Body','all_members',null,null,null,null) from generate_series(1,10) n;
select public.publish_announcement(id) from anc_ids where k like 'cap%' and k<>'cap10' order by k;
select is(pg_temp.anc_refusal($q$select public.publish_announcement((select id from anc_ids where k='cap10'))$q$),'GL088:live_limit','ANC-004: eleventh live rejected');
select is((select count(*)::integer from public.list_announcements() where display_status='live'),10,'ANC-004: cap refusal leaves exactly ten live');
select public.unpublish_announcement(id) from anc_ids where k like 'cap%' and k<>'cap10' order by k;
select lives_ok($q$select public.publish_announcement((select id from anc_ids where k='cap10'))$q$,'ANC-004: taking down frees live capacity');
insert into anc_ids select 'rate'||n,public.create_announcement_draft('transactional','Rate '||n,'Body','all_members',null,null,null,null) from generate_series(1,9) n;
select public.publish_announcement(id) from anc_ids where k like 'rate%' and k<>'rate9' order by k;
select public.unpublish_announcement(id) from anc_ids where k like 'rate%' and k<>'rate9' order by k;
-- Notice + promotion + nine cap publishes + cap10 + eight rate publishes = 20.
select is(pg_temp.anc_refusal($q$select public.publish_announcement((select id from anc_ids where k='rate9'))$q$),'GL088:publish_rate_limited','ANC-004: twenty-first rolling-day publish refused although live capacity is available');
select is((select count(*)::integer from public.announcements where published_at>=statement_timestamp()-interval '24 hours'),20,'ANC-004: twenty accepted publish stamps retained');
insert into anc_ids values('expired_draft',public.create_announcement_draft('transactional','Expired draft','Body','all_members',null,null,now()-interval '1 day',null)),('long_expiry',public.create_announcement_draft('transactional','Long expiry','Body','all_members',null,null,now()+interval '366 days',null));
select is(pg_temp.anc_refusal($q$select public.publish_announcement((select id from anc_ids where k='expired_draft'))$q$),'GL088:expiry_invalid','ANC-004/018: past draft expiry accepted at save, refused before rate limit at publish');
select is(pg_temp.anc_refusal($q$select public.publish_announcement((select id from anc_ids where k='long_expiry'))$q$),'GL088:expiry_invalid','ANC-004: expiry above year refused before rate limit');
-- Version cap uses already live promotion, with content changes distinct each time.
select public.edit_announcement((select id from anc_ids where k='promo'),n,'Version '||(n+1),'Body '||(n+1),null,null,'Meaningful note') from generate_series(3,9) n order by n;
select is((select current_version from public.announcements where id=(select id from anc_ids where k='promo')),10,'ANC-008: ten total versions accepted');
select is(pg_temp.anc_refusal($q$select public.edit_announcement((select id from anc_ids where k='promo'),10,'Eleventh','Body eleven',null,null,'Meaningful note')$q$),'GL088:version_limit','ANC-008: eleventh content version refused');
select lives_ok($q$select public.edit_announcement((select id from anc_ids where k='promo'),10,'Version 10','Body 10',null,now()+interval '1 day',null)$q$,'ANC-009: expiry-only change still possible at version cap');
reset role;
select set_config('request.jwt.claims','',true);
select is((select count(*)::integer from public.announcement_versions where announcement_id=(select id from anc_ids where k='promo')),10,'ANC-008: failed cap adds no historic row');
select is(pg_temp.anc_refusal($q$select app.announcement_audit(pg_temp.aid(1),null,null,'unknown.action',pg_temp.aid(9999),null,null,null)$q$),'22023','ANC-015: private audit action allowlist refuses anything else');
select ok(exists(select 1 from pg_constraint c where c.conrelid='public.announcement_versions'::regclass and c.confrelid='public.media_assets'::regclass and c.contype='f' and c.confdeltype='a' and c.confupdtype='a'),'ANC-017: historic media FK never cascades or sets null');
select is((select count(*)::integer from public.audit_log where tenant_id=pg_temp.aid(1) and action like 'announcement.%' and record_type<>'announcement'),0,'ANC-015: every accepted content action uses announcement record type');
-- Convention conformance is a synthetic trusted notice, not ANC fan-out.
select lives_ok($q$insert into public.notifications(id,tenant_id,member_id,channel,status,category,template_key,dedupe_key,related_type,related_id,scheduled_for,payload) values(pg_temp.aid(801),pg_temp.aid(1),pg_temp.aid(102),'in_app','scheduled','announcement',null,'announcement:conformance:75000000-0000-4000-8000-000000000802:75000000-0000-4000-8000-000000000102','announcement',pg_temp.aid(802),statement_timestamp(),'{"body":"Synthetic notice"}'); update public.notifications set status='sent' where id=pg_temp.aid(801)$q$,'ANC-022: committed announcement category passes unchanged trusted scheduled-to-sent lifecycle');
select pg_temp.anc_claim('member',null,102,907);
set local role authenticated;
select lives_ok($q$select public.acknowledge_notification(pg_temp.aid(801))$q$,'ANC-022: real member acknowledges synthetic announcement notice');
select is((select status::text from public.notifications where id=pg_temp.aid(801)),'delivered','ANC-022: notice member acknowledgement has existing delivered state');
reset role;
-- Remaining catalog boundaries are exact names/shapes, not implementation text.
select results_eq($q$select conname::text collate "default" from pg_constraint where conrelid in('public.announcements'::regclass,'public.announcement_versions'::regclass) and contype='c' order by conname$q$,$q$select * from (values('announcement_versions_body_chk' collate "default"),('announcement_versions_change_note_chk' collate "default"),('announcement_versions_title_chk' collate "default"),('announcement_versions_version_no_chk' collate "default"),('announcements_expiry_chk' collate "default"),('announcements_segment_shape_chk' collate "default"),('announcements_state_chk' collate "default"),('announcements_version_chk' collate "default")) as expected$q$,'ANC-016: exactly eight canonical content/state checks');
select is((select count(*)::integer from pg_constraint c where c.conrelid in('public.announcements'::regclass,'public.announcement_versions'::regclass,'public.announcement_receipts'::regclass) and c.contype='f' and c.confrelid in('public.staff'::regclass,'public.announcements'::regclass,'public.media_assets'::regclass,'public.announcement_versions'::regclass,'public.members'::regclass) and cardinality(c.conkey)=2 and cardinality(c.confkey)=2),6,'ANC-016: all six reference edges are composite tenant/id FKs');
select is((select count(*)::integer from pg_constraint where contype='u' and conname in('announcements_tenant_id_id_key','announcement_versions_tenant_id_id_key','announcement_versions_announcement_version_key','announcement_receipts_version_member_key')),4,'ANC-016: four exact unique tenant/version/receipt keys');
select ok(not has_function_privilege('authenticated','app.announcement_audit(uuid,uuid,public.app_role,text,uuid,jsonb,jsonb,text)','EXECUTE') and not has_function_privilege('service_role','app.announcement_audit(uuid,uuid,public.app_role,text,uuid,jsonb,jsonb,text)','EXECUTE'),'ANC-015: audit helper has no end-user or service execute grant');
select pg_temp.anc_claim();
set local role authenticated;
insert into anc_ids values('status_active',public.create_announcement_draft('transactional','Status active','Body','segment',array['active']::public.member_status[],'any',null,null));
reset role;
select is((select count(*)::integer from app.announcement_audience((select id from anc_ids where k='status_active'))),1,'ANC-006: active status filter independently restricts audience');
select pg_temp.anc_claim();
set local role authenticated;
insert into anc_ids values('status_paused',public.create_announcement_draft('transactional','Status paused','Body','segment',array['paused']::public.member_status[],'any',null,null));
reset role;
select is((select count(*)::integer from app.announcement_audience((select id from anc_ids where k='status_paused'))),1,'ANC-006: paused status filter independently restricts audience');
select pg_temp.anc_claim();
set local role authenticated;
insert into anc_ids values('status_expired',public.create_announcement_draft('transactional','Status expired','Body','segment',array['expired']::public.member_status[],'any',null,null));
reset role;
select is((select count(*)::integer from app.announcement_audience((select id from anc_ids where k='status_expired'))),1,'ANC-006: expired status filter independently restricts audience');
select pg_temp.anc_claim('trainer',24,null,904);
set local role authenticated;
select is((select count(*)::integer from public.announcement_receipts),0,'ANC-013: trainer directly sees no receipt identity');
reset role;
select pg_temp.anc_claim('platform_support',null,null,913);
set local role authenticated;
select is((select count(*)::integer from public.announcement_receipts),0,'ANC-013: platform_support directly sees no receipt identity');
reset role;
select pg_temp.anc_claim('super_admin',null,null,914);
set local role authenticated;
select is((select count(*)::integer from public.announcement_receipts),0,'ANC-013: super_admin directly sees no receipt identity');
reset role;
select set_config('request.jwt.claims','',true);
set local role authenticated;
select is(pg_temp.anc_refusal($q$select public.create_announcement_draft('transactional',null,null,'all_members',null,null,null,null)$q$),'42501','ANC-018: missing actor precedes malformed draft');
reset role;
select set_config('request.jwt.claims','',true);
-- Bounded historical import: only this synthetic published row is backdated.
-- CHECKs remain enabled: published state, null closed_at and expiry > publication.
create temp table anc_expiry_checks as
select conname,pg_get_constraintdef(oid) as definition from pg_constraint
where conrelid='public.announcements'::regclass and conname in('announcements_state_chk','announcements_expiry_chk');
set local session_replication_role=replica;
update public.announcements set published_at=statement_timestamp()-interval '2 days',expires_at=statement_timestamp()-interval '1 day'
where id=(select id from anc_ids where k='promo');
set local session_replication_role=origin;
do $$begin
  if (select count(*) from anc_expiry_checks)<>2 or exists(
    select 1 from anc_expiry_checks saved left join pg_constraint c
    on c.conrelid='public.announcements'::regclass and c.conname=saved.conname
    where c.oid is null or pg_get_constraintdef(c.oid) is distinct from saved.definition)
  then raise exception 'Historical expiry fixture changed canonical checks'; end if;
end$$;
select pg_temp.anc_claim('member',null,102,907);
set local role authenticated;
select is((select count(*)::integer from public.read_member_announcements() where announcement_id=(select id from anc_ids where k='promo')),0,'ANC-007: expiry derives ended feed without sweeper');
select ok(not public.mark_announcement_read((select id from anc_ids where k='promo'),10),'ANC-011: expired read marker returns false');
reset role;
select * from finish();
rollback;
