-- Source-blind metadata supplement for frozen prepared-command-declaration.md.
begin;
SET LOCAL ROLE postgres;
SET LOCAL search_path = public, extensions;
SELECT plan(18);
SELECT ok(EXISTS(SELECT 1 FROM pg_catalog.pg_class c JOIN pg_catalog.pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname='app' AND c.relname='slf_freeze_preparations' AND c.relkind='r'),'private preparation relation exists');
SELECT is((SELECT string_agg(a.attname::text || ':' || pg_catalog.format_type(a.atttypid,a.atttypmod),',' ORDER BY a.attnum) FROM pg_catalog.pg_attribute a JOIN pg_catalog.pg_class c ON c.oid=a.attrelid JOIN pg_catalog.pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname='app' AND c.relname='slf_freeze_preparations' AND a.attnum>0 AND NOT a.attisdropped),'transaction_id:text,tenant_id:uuid,actor_user_id:uuid,command_key:uuid,request_id:uuid,action:text,expected_revision:bigint,facts:jsonb,prepared_at:timestamp with time zone,source_pause_id:uuid','exact capability columns and full-transaction text identity');
SELECT is((SELECT string_agg(a.attname::text || ':' || a.attnotnull::text,',' ORDER BY a.attnum) FROM pg_catalog.pg_attribute a JOIN pg_catalog.pg_class c ON c.oid=a.attrelid JOIN pg_catalog.pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname='app' AND c.relname='slf_freeze_preparations' AND a.attnum>0 AND NOT a.attisdropped),'transaction_id:true,tenant_id:true,actor_user_id:true,command_key:true,request_id:true,action:true,expected_revision:true,facts:true,prepared_at:true,source_pause_id:false','only optional source binding is nullable');
SELECT is((SELECT string_agg(a.attname::text,',' ORDER BY k.ord) FROM pg_catalog.pg_constraint x JOIN pg_catalog.pg_class c ON c.oid=x.conrelid JOIN pg_catalog.pg_namespace n ON n.oid=c.relnamespace CROSS JOIN LATERAL unnest(x.conkey) WITH ORDINALITY k(attnum,ord) JOIN pg_catalog.pg_attribute a ON a.attrelid=c.oid AND a.attnum=k.attnum WHERE n.nspname='app' AND c.relname='slf_freeze_preparations' AND x.contype='p'),'transaction_id,tenant_id,actor_user_id,command_key','primary key binds full transaction tenant actor and command');
SELECT ok(EXISTS(SELECT 1 FROM pg_catalog.pg_constraint x JOIN pg_catalog.pg_class c ON c.oid=x.conrelid JOIN pg_catalog.pg_namespace n ON n.oid=c.relnamespace JOIN pg_catalog.pg_class p ON p.oid=x.confrelid JOIN pg_catalog.pg_namespace pn ON pn.oid=p.relnamespace WHERE n.nspname='app' AND c.relname='slf_freeze_preparations' AND x.contype='f' AND pn.nspname='public' AND p.relname='organizations' AND (SELECT string_agg(a.attname::text,',' ORDER BY k.ord) FROM unnest(x.conkey) WITH ORDINALITY k(attnum,ord) JOIN pg_catalog.pg_attribute a ON a.attrelid=c.oid AND a.attnum=k.attnum)='tenant_id' AND (SELECT string_agg(a.attname::text,',' ORDER BY k.ord) FROM unnest(x.confkey) WITH ORDINALITY k(attnum,ord) JOIN pg_catalog.pg_attribute a ON a.attrelid=p.oid AND a.attnum=k.attnum)='id'),'tenant capability references real organization');
SELECT ok(EXISTS(SELECT 1 FROM pg_catalog.pg_constraint x JOIN pg_catalog.pg_class c ON c.oid=x.conrelid JOIN pg_catalog.pg_namespace n ON n.oid=c.relnamespace JOIN pg_catalog.pg_class p ON p.oid=x.confrelid JOIN pg_catalog.pg_namespace pn ON pn.oid=p.relnamespace WHERE n.nspname='app' AND c.relname='slf_freeze_preparations' AND x.contype='f' AND pn.nspname='public' AND p.relname='member_freeze_requests' AND (SELECT string_agg(a.attname::text,',' ORDER BY k.ord) FROM unnest(x.conkey) WITH ORDINALITY k(attnum,ord) JOIN pg_catalog.pg_attribute a ON a.attrelid=c.oid AND a.attnum=k.attnum)='tenant_id,request_id' AND (SELECT string_agg(a.attname::text,',' ORDER BY k.ord) FROM unnest(x.confkey) WITH ORDINALITY k(attnum,ord) JOIN pg_catalog.pg_attribute a ON a.attrelid=p.oid AND a.attnum=k.attnum)='tenant_id,id'),'request capability has tenant preserving composite FK');
SELECT ok(EXISTS(SELECT 1 FROM pg_catalog.pg_index i JOIN pg_catalog.pg_class c ON c.oid=i.indrelid JOIN pg_catalog.pg_namespace n ON n.oid=c.relnamespace JOIN pg_catalog.pg_class ix ON ix.oid=i.indexrelid JOIN pg_catalog.pg_am am ON am.oid=ix.relam WHERE n.nspname='app' AND c.relname='slf_freeze_preparations' AND ix.relname='slf_freeze_preparations_tenant_request_transaction_idx' AND am.amname='btree' AND i.indisvalid AND i.indpred IS NULL AND i.indexprs IS NULL AND (SELECT string_agg(a.attname::text,',' ORDER BY k.ord) FROM unnest(i.indkey) WITH ORDINALITY k(attnum,ord) JOIN pg_catalog.pg_attribute a ON a.attrelid=c.oid AND a.attnum=k.attnum WHERE k.ord<=i.indnkeyatts)='tenant_id,request_id,transaction_id'),'scoped nonpartial index leads with tenant and request');
SELECT ok(EXISTS(SELECT 1 FROM pg_catalog.pg_class c JOIN pg_catalog.pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname='app' AND c.relname='slf_freeze_preparations' AND c.relrowsecurity),'private preparations enable RLS');
SELECT ok(EXISTS(SELECT 1 FROM pg_catalog.pg_class c JOIN pg_catalog.pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname='app' AND c.relname='slf_freeze_preparations' AND NOT EXISTS(SELECT 1 FROM pg_catalog.pg_policy p WHERE p.polrelid=c.oid)),'private preparations have no session policies');
SELECT ok(EXISTS(SELECT 1 FROM pg_catalog.pg_class c JOIN pg_catalog.pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname='app' AND c.relname='slf_freeze_preparations' AND NOT EXISTS(SELECT 1 FROM pg_catalog.aclexplode(coalesce(c.relacl,pg_catalog.acldefault('r',c.relowner))) a WHERE a.grantee=0)),'PUBLIC has no preparation relation privileges');
SELECT ok(EXISTS(SELECT 1 FROM pg_catalog.pg_class c JOIN pg_catalog.pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname='app' AND c.relname='slf_freeze_preparations' AND NOT pg_catalog.has_table_privilege('anon',c.oid,'SELECT,INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER') AND NOT pg_catalog.has_any_column_privilege('anon',c.oid,'SELECT,INSERT,UPDATE,REFERENCES')),'anon has no table or column preparation privileges');
SELECT ok(EXISTS(SELECT 1 FROM pg_catalog.pg_class c JOIN pg_catalog.pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname='app' AND c.relname='slf_freeze_preparations' AND NOT pg_catalog.has_table_privilege('authenticated',c.oid,'SELECT,INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER') AND NOT pg_catalog.has_any_column_privilege('authenticated',c.oid,'SELECT,INSERT,UPDATE,REFERENCES')),'authenticated has no table or column preparation privileges');
SELECT ok(EXISTS(SELECT 1 FROM pg_catalog.pg_class c JOIN pg_catalog.pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname='app' AND c.relname='slf_freeze_preparations' AND NOT pg_catalog.has_table_privilege('service_role',c.oid,'SELECT,INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER') AND NOT pg_catalog.has_any_column_privilege('service_role',c.oid,'SELECT,INSERT,UPDATE,REFERENCES')),'service_role has no table or column preparation privileges');
SELECT ok(EXISTS(SELECT 1 FROM pg_catalog.pg_trigger t JOIN pg_catalog.pg_class c ON c.oid=t.tgrelid JOIN pg_catalog.pg_namespace n ON n.oid=c.relnamespace JOIN pg_catalog.pg_proc p ON p.oid=t.tgfoid JOIN pg_catalog.pg_namespace pn ON pn.oid=p.pronamespace WHERE n.nspname='public' AND c.relname='membership_pauses' AND t.tgname='membership_pauses_freeze_source_lock' AND NOT t.tgisinternal AND t.tgenabled='O' AND t.tgtype=31 AND pn.nspname='app' AND p.proname='enforce_freeze_source_consistency' AND p.pronargs=0 AND t.tgdeferrable=false AND t.tginitdeferred=false AND t.tgconstraint=0),'membership_pauses_freeze_source_lock has exact row timing events and existing helper');
SELECT ok(EXISTS(SELECT 1 FROM pg_catalog.pg_trigger t JOIN pg_catalog.pg_class c ON c.oid=t.tgrelid JOIN pg_catalog.pg_namespace n ON n.oid=c.relnamespace JOIN pg_catalog.pg_proc p ON p.oid=t.tgfoid JOIN pg_catalog.pg_namespace pn ON pn.oid=p.pronamespace WHERE n.nspname='public' AND c.relname='member_freeze_requests' AND t.tgname='member_freeze_requests_source_consistency' AND NOT t.tgisinternal AND t.tgenabled='O' AND t.tgtype=23 AND pn.nspname='app' AND p.proname='enforce_freeze_source_consistency' AND p.pronargs=0 AND t.tgdeferrable=false AND t.tginitdeferred=false AND t.tgconstraint=0),'member_freeze_requests_source_consistency has exact row timing events and existing helper');
SELECT ok(EXISTS(SELECT 1 FROM pg_catalog.pg_trigger t JOIN pg_catalog.pg_class c ON c.oid=t.tgrelid JOIN pg_catalog.pg_namespace n ON n.oid=c.relnamespace JOIN pg_catalog.pg_proc p ON p.oid=t.tgfoid JOIN pg_catalog.pg_namespace pn ON pn.oid=p.pronamespace WHERE n.nspname='public' AND c.relname='membership_pauses' AND t.tgname='membership_pauses_freeze_source_deferred' AND NOT t.tgisinternal AND t.tgenabled='O' AND t.tgtype=29 AND pn.nspname='app' AND p.proname='enforce_freeze_source_consistency' AND p.pronargs=0 AND t.tgdeferrable=true AND t.tginitdeferred=true AND t.tgconstraint<>0),'membership_pauses_freeze_source_deferred has exact row timing events and existing helper with initially deferred constraint');
SELECT ok(EXISTS(SELECT 1 FROM pg_catalog.pg_trigger t JOIN pg_catalog.pg_class c ON c.oid=t.tgrelid JOIN pg_catalog.pg_namespace n ON n.oid=c.relnamespace JOIN pg_catalog.pg_proc p ON p.oid=t.tgfoid JOIN pg_catalog.pg_namespace pn ON pn.oid=p.pronamespace WHERE n.nspname='public' AND c.relname='member_freeze_requests' AND t.tgname='member_freeze_requests_source_deferred' AND NOT t.tgisinternal AND t.tgenabled='O' AND t.tgtype=21 AND pn.nspname='app' AND p.proname='enforce_freeze_source_consistency' AND p.pronargs=0 AND t.tgdeferrable=true AND t.tginitdeferred=true AND t.tgconstraint<>0),'member_freeze_requests_source_deferred has exact row timing events and existing helper with initially deferred constraint');
SELECT ok(EXISTS(SELECT 1 FROM pg_catalog.pg_proc p JOIN pg_catalog.pg_namespace n ON n.oid=p.pronamespace JOIN pg_catalog.pg_roles r ON r.oid=p.proowner WHERE n.nspname='app' AND p.proname='enforce_freeze_source_consistency' AND p.pronargs=0 AND r.rolname='postgres' AND EXISTS(SELECT 1 FROM unnest(p.proconfig) cfg WHERE cfg IN ('search_path=""','search_path='))),'existing consistency helper retains postgres ownership and empty search path');
select * from finish();
rollback;

