'use client';
import { useCallback } from 'react';
import Image from 'next/image';
import { useRouter } from 'next/navigation';
import { trainerProfileRequestSchema, ownTrainerProfileRequestSchema, trainerAvailabilityRequestSchema, trainerTimeOffRequestSchema, trainerTimeOffRemoveRequestSchema, formatMinuteOfDay, parseMinuteOfDay, windowsOverlap, PT_BOOKING_LIMITS, DAYS_PER_WEEK, MINUTES_PER_HOUR, UI_TOKENS, AVATAR_INITIALS_MAX, toLocalDate, formatDateTime, type TrainerWindow, type PtReadSection, type BusinessNouns } from '@gymloop/shared';
import type { ConsoleViewer, TrainerChoice, TrainerProfile, TimeOff, StaffBooking } from '../../../../../lib/training-console';
import { usePtCommand } from '../../../../../lib/use-pt-command';
import { uploadMediaFile } from '../../../../../lib/media-upload';
import { Field, inputClass } from '../../../field';
import { useControlState } from '../../control-state';
import { managers, ownTrainer, postCommand, commandData } from '../../command';

export function TrainerProfileForm({ trainer, profile, imageUrl, viewer, nouns }: { trainer: TrainerChoice; profile: TrainerProfile | null; imageUrl: string | null; viewer: ConsoleViewer; nouns: BusinessNouns }) {
  const router = useRouter();
  const local = useControlState({ bio: profile?.bio ?? '', specialities: profile?.specialities.join(', ') ?? '', photoAssetId: profile?.photo_asset_id ?? null, isListed: profile?.is_listed ?? false, stage: '', uploadError: '', saved: false }, JSON.stringify([trainer, profile, imageUrl]), viewer);
  const state = local.value;
  const editable = ownTrainer(viewer, trainer.staffId);
  const full = managers(viewer);
  const send = useCallback((body: unknown) => postCommand(full ? '/api/trainer-profiles' : '/api/trainer-profiles/own', body), [full]);
  const accepted = useCallback((result: unknown) => typeof commandData(result)?.profileId === 'string', []);
  const command = usePtCommand({ viewer, operationKey: local.key, nouns, canSubmit: current => ownTrainer(current, trainer.staffId), send, accepted, refresh: router.refresh });
  const own = { bio: state.bio, specialities: state.specialities.split(',') };
  const parsed = full ? trainerProfileRequestSchema.safeParse({ ...own, staffId: trainer.staffId, photoAssetId: state.photoAssetId, isListed: state.isListed }) : ownTrainerProfileRequestSchema.safeParse(own);
  async function upload(file: File | undefined) {
    if (!file || !local.current(state) || !full || command.pending || state.stage) return;
    if (!navigator.onLine) { local.set(old => ({ ...old, uploadError: 'Reconnect and try again.' })); return; }
    local.set(old => ({ ...old, stage: 'uploading', uploadError: '', saved: false }));
    try { const result = await uploadMediaFile(file, 'trainer', stage => { if (local.current()) local.set(old => ({ ...old, stage })); }); if (local.current()) local.set(old => ({ ...old, photoAssetId: result.assetId, stage: '' })); }
    catch { if (local.current()) local.set(old => ({ ...old, stage: '', uploadError: 'Photo could not be uploaded. Please try again.' })); }
  }
  async function save() { if (!local.current(state) || !editable || state.stage || !parsed.success) return; const result = await command.submit(parsed.data); if (local.current() && accepted(result)) local.set(old => ({ ...old, saved: true })); }
  return <section className="class-editor"><h2 className="cl-section-title">Profile</h2>{imageUrl ? <Image src={imageUrl} alt={trainer.displayName} width={UI_TOKENS.geometry.media.avatarSize} height={UI_TOKENS.geometry.media.avatarSize} unoptimized /> : <span className="check-in-member-initial" aria-label={`${trainer.displayName}, no photo`}>{trainer.displayName.split(' ').filter(Boolean).slice(0, AVATAR_INITIALS_MAX).map(part => part.charAt(0)).join('')}</span>}{editable && profile?.bio ? <p>{profile.bio}</p> : null}
    {editable ? <><Field label="Bio"><textarea className={inputClass} maxLength={PT_BOOKING_LIMITS.bioMaxChars} value={state.bio} onChange={event => local.set(old => ({ ...old, bio: event.target.value, saved: false }))} /></Field><Field label="Specialities, separated by commas"><input className={inputClass} value={state.specialities} onChange={event => local.set(old => ({ ...old, specialities: event.target.value, saved: false }))} /></Field>{full ? <><Field label="Listed for members"><input type="checkbox" checked={state.isListed} onChange={event => local.set(old => ({ ...old, isListed: event.target.checked, saved: false }))} /></Field><Field label="Trainer photo"><input type="file" accept="image/jpeg,image/png,image/webp" disabled={Boolean(state.stage) || command.pending} onChange={event => { void upload(event.target.files?.[0]); }} /></Field>{state.photoAssetId ? <button type="button" className="cl-btn" disabled={Boolean(state.stage) || command.pending} onClick={() => local.set(old => ({ ...old, photoAssetId: null, saved: false }))}>Clear photo</button> : null}</> : null}<button className="cl-btn" type="button" disabled={command.pending || Boolean(state.stage) || !parsed.success} onClick={save}>Save profile</button>{!parsed.success ? <p className="cl-alert">Check the bio and specialities.</p> : null}</> : <><p>{profile?.bio || 'No bio yet.'}</p><p>{profile?.specialities.join(', ') || 'No specialities yet.'}</p><p>{profile?.is_listed ? 'Listed' : 'Unlisted'}</p></>}
    {state.stage ? <p role="status">{state.stage === 'verifying' ? 'Verifying photo…' : 'Uploading photo…'}</p> : null}{state.uploadError ? <p className="cl-alert" role="alert">{state.uploadError}</p> : null}{command.error ? <p className="cl-alert" role="alert">{command.error}</p> : null}{state.saved ? <p role="status">Profile saved.</p> : null}</section>;
}

export function TrainerAvailabilityEditor({ trainer, windows, viewer, nouns }: { trainer: TrainerChoice; windows: TrainerWindow[]; viewer: ConsoleViewer; nouns: BusinessNouns }) {
  const router = useRouter();
  const local = useControlState({ windows, saved: false }, JSON.stringify([trainer, windows]), viewer);
  const editable = ownTrainer(viewer, trainer.staffId);
  const send = useCallback((body: unknown) => postCommand('/api/trainer-availability', body), []);
  const accepted = useCallback((result: unknown) => Number.isInteger(commandData(result)?.windows), []);
  const command = usePtCommand({ viewer, operationKey: local.key, nouns, canSubmit: current => ownTrainer(current, trainer.staffId), send, accepted, refresh: router.refresh });
  const parsed = trainerAvailabilityRequestSchema.safeParse({ staffId: trainer.staffId, windows: local.value.windows });
  async function save() { if (!local.current(local.value) || !editable || !parsed.success) return; const result = await command.submit(parsed.data); if (local.current() && accepted(result)) local.set(old => ({ ...old, saved: true })); }
  function change(index: number, patch: Partial<TrainerWindow>) { local.set(old => ({ windows: old.windows.map((window, position) => position === index ? { ...window, ...patch } : window), saved: false })); }
  return <section className="class-editor"><h2 className="cl-section-title">Weekly availability</h2><p>Times are in {trainer.timezone}. Availability changes do not cancel existing bookings.</p>{local.value.windows.length === 0 ? <p>No weekly windows yet.</p> : null}{local.value.windows.map((window, index) => <fieldset className="cl-surface" key={index}><legend>Window {index + 1}</legend><Field label="Weekday"><select className={inputClass} disabled={!editable} value={window.weekday} onChange={event => change(index, { weekday: Number(event.target.value) })}>{Array.from({ length: DAYS_PER_WEEK }, (_, weekday) => <option key={weekday} value={weekday}>{(() => { const date = new Date(); date.setUTCDate(date.getUTCDate() - date.getUTCDay() + weekday); return new Intl.DateTimeFormat('en', { weekday: 'long', timeZone: 'UTC' }).format(date); })()}</option>)}</select></Field><Field label="Start time"><input className={inputClass} type="time" disabled={!editable} value={formatMinuteOfDay(window.startMinute)} onChange={event => change(index, { startMinute: parseMinuteOfDay(event.target.value) ?? -1 })} /></Field><Field label="End time"><input className={inputClass} type="time" disabled={!editable} value={formatMinuteOfDay(window.endMinute)} onChange={event => change(index, { endMinute: parseMinuteOfDay(event.target.value) ?? -1 })} /></Field>{local.value.windows.some((other, position) => position !== index && windowsOverlap(window, other)) ? <p className="cl-alert" role="alert">These availability windows overlap.</p> : null}{window.endMinute <= window.startMinute || window.startMinute < 0 ? <p className="cl-alert">End time must follow start time.</p> : null}{editable ? <button className="cl-btn" type="button" onClick={() => local.set(old => ({ windows: old.windows.filter((_, position) => position !== index), saved: false }))}>Remove window</button> : null}</fieldset>)}{editable ? <div className="cl-actions"><button className="cl-btn" type="button" disabled={command.pending || local.value.windows.length >= PT_BOOKING_LIMITS.availabilityWindowsMax} onClick={() => local.set(old => ({ windows: [...old.windows, { weekday: 0, startMinute: 0, endMinute: MINUTES_PER_HOUR }], saved: false }))}>Add window</button><button className="cl-btn" type="button" disabled={command.pending || !parsed.success} onClick={save}>Save availability</button></div> : null}{command.error ? <p className="cl-alert" role="alert">{command.error}</p> : null}{local.value.saved ? <p role="status">Availability saved.</p> : null}</section>;
}

export function TrainerTimeOffPanel({ trainer, entries, bookings, viewer, nouns }: { trainer: TrainerChoice; entries: TimeOff[]; bookings: PtReadSection<StaffBooking>; viewer: ConsoleViewer; nouns: BusinessNouns }) {
  const router = useRouter();
  const local = useControlState({ startsOn: '', endsOn: '', reason: '', saved: false }, JSON.stringify([trainer, entries, bookings]), viewer);
  const editable = ownTrainer(viewer, trainer.staffId);
  const send = useCallback((body: { timeOffId: string } | { staffId: string; startsOn: string; endsOn: string; reason?: string | undefined }) => postCommand('timeOffId' in body ? '/api/trainer-time-off/remove' : '/api/trainer-time-off', body), []);
  const accepted = useCallback((result: unknown) => { const data = commandData(result); return typeof data?.timeOffId === 'string' || data?.removed === true; }, []);
  const command = usePtCommand({ viewer, operationKey: local.key, nouns, canSubmit: current => ownTrainer(current, trainer.staffId), send, accepted, refresh: router.refresh });
  const parsed = trainerTimeOffRequestSchema.safeParse({ staffId: trainer.staffId, startsOn: local.value.startsOn, endsOn: local.value.endsOn, ...(local.value.reason.trim() ? { reason: local.value.reason } : {}) });
  async function add() { if (!local.current(local.value) || !editable || !parsed.success) return; const result = await command.submit(parsed.data); if (local.current() && accepted(result)) local.set(old => ({ ...old, saved: true })); }
  async function remove(timeOffId: string) { if (!local.current() || !editable) return; const parsedRemove = trainerTimeOffRemoveRequestSchema.safeParse({ timeOffId }); if (parsedRemove.success) await command.submit(parsedRemove.data); }
  return <section className="class-editor"><h2 className="cl-section-title">Time off</h2><p>Existing booked {nouns.sessions} remain booked. Adding time off does not cancel them.</p>{bookings.error || bookings.data === null ? <p className="cl-alert" role="alert">Please try again to load standing bookings.</p> : null}{entries.filter(entry => entry.removed_at === null).length === 0 ? <p>No time off yet.</p> : <ul className="class-ledger">{entries.filter(entry => entry.removed_at === null).map(entry => <li key={entry.id} className="class-entry"><div><h3>{entry.starts_on} – {entry.ends_on} · {trainer.timezone}</h3><p>{entry.reason}</p>{bookings.data ? <ul>{bookings.data.filter(booking => { const day = toLocalDate(new Date(booking.starts_at), trainer.timezone); return day >= entry.starts_on && day <= entry.ends_on; }).map(booking => <li key={booking.session_id}>{booking.member_name} · {formatDateTime(booking.starts_at, booking.timezone)} · remains booked</li>)}</ul> : null}</div>{editable ? <button className="cl-btn" type="button" disabled={command.pending} onClick={() => remove(entry.id)}>Remove time off</button> : null}</li>)}</ul>}{editable ? <><Field label="Start date"><input className={inputClass} type="date" value={local.value.startsOn} onChange={event => local.set(old => ({ ...old, startsOn: event.target.value, saved: false }))} /></Field><Field label="End date"><input className={inputClass} type="date" value={local.value.endsOn} onChange={event => local.set(old => ({ ...old, endsOn: event.target.value, saved: false }))} /></Field><Field label="Reason (optional)"><textarea className={inputClass} maxLength={PT_BOOKING_LIMITS.timeOffReasonMaxChars} value={local.value.reason} onChange={event => local.set(old => ({ ...old, reason: event.target.value, saved: false }))} /></Field><button className="cl-btn" type="button" disabled={command.pending || !parsed.success} onClick={add}>Add time off</button>{local.value.startsOn && local.value.endsOn && !parsed.success ? <p className="cl-alert">Check the date range.</p> : null}</> : null}{command.error ? <p className="cl-alert" role="alert">{command.error}</p> : null}{local.value.saved ? <p role="status">Time off saved. Existing sessions remain booked.</p> : null}</section>;
}
