import { beforeEach, describe, expect, it, vi } from 'vitest';
const state = vi.hoisted(() => ({ claims: null as Record<string, unknown> | null, calls: [] as Array<{ name: string; args: Record<string, unknown> }>, result: { data: null as unknown, error: null as unknown }, sign: vi.fn(), events: [] as string[] }));
const client = () => ({ auth: { getClaims: async () => { state.events.push('caller'); return { data: { claims: state.claims }, error: null }; }, getUser: async () => ({ data: { user: state.claims && { id: state.claims.sub } }, error: null }) }, rpc: async (name: string, args: Record<string, unknown>) => { state.calls.push({ name, args }); return name === 'delete_media_asset' ? { data: null, error: null } : state.result; } });
vi.mock('../../lib/supabase/server', () => ({ createServerSupabase: async () => client() }));
vi.mock('../../lib/supabase/request', () => ({ createRequestSupabase: async () => ({ supabase: client(), bearer: 'original-caller' }) }));
vi.mock('../../lib/media', () => ({ createMediaStorage: () => ({ presignPut: state.sign }) }));
const id = '72000000-0000-4000-8000-000000000001';
const owner = { sub: id, role: 'authenticated', app_role: 'gym_owner', tenant_id: id, staff_id: id };
function req(body: unknown) { const request = new Request('https://gym.example/api/media/upload-url', { method: 'POST', headers: { authorization: 'Bearer original-caller', 'content-type': 'application/json' }, body: JSON.stringify(body) }); const read = request.json.bind(request); vi.spyOn(request, 'json').mockImplementation(async () => { state.events.push('body'); return read(); }); return request; }
beforeEach(() => { state.claims = owner; state.calls = []; state.events = []; state.result = { data: id, error: null }; state.sign.mockReset().mockResolvedValue('https://upload.test/staging/upload'); });
describe('MED-006 upload URL real HTTP entrypoint', () => {
  it('server derives claim-tenant staging key and returns only upload capability', async () => {
    const { POST } = await import('../api/media/upload-url/route'); const response = await POST(req({ kind: 'product', mime: 'image/jpeg', bytes: 12 })); expect(response.status).toBe(200); expect(response.headers.get('cache-control')).toBe('no-store');
    expect(state.calls).toHaveLength(1); expect(state.calls[0]).toMatchObject({ name: 'register_media_asset', args: { p_kind: 'product', p_mime: 'image/jpeg', p_bytes: 12 } }); expect(state.calls[0]?.args.p_object_key).toMatch(new RegExp(`^${id}/staging/product/[a-f0-9-]+\\.jpg$`));
    const payload = await response.json(); expect(Object.keys(payload.data).sort()).toEqual(['assetId', 'expiresAt', 'headers', 'uploadUrl']); expect(payload.data.headers).toEqual({ 'content-type': 'image/jpeg' }); expect(payload.data.assetId).toBe(id); expect(state.events.indexOf('caller')).toBeLessThan(state.events.indexOf('body'));
  });
  it.each([{ tenantId: id }, { objectKey: `${id}/published/product/${id}.jpg` }, { actorStaffId: id }, { headers: { authorization: 'private' } }])('refuses injected signing input %j', async extra => { const { POST } = await import('../api/media/upload-url/route'); const response = await POST(req({ kind: 'product', mime: 'image/jpeg', bytes: 12, ...extra })); expect(response.status).toBe(400); expect(state.calls).toEqual([]); expect(state.sign).not.toHaveBeenCalled(); });
  it.each([['GL086', 'media_limit', 429, 'upload_rate_limited'], ['42501', '', 403, 'not_permitted'], ['22023', '', 400, 'invalid_request'], ['XX000', '', 500, 'upload_failed']])('maps registration %s without signing', async (code, details, status, errorCode) => { state.result = { data: null, error: { code, details, message: 'RAW_STORAGE_SECRET' } }; const { POST } = await import('../api/media/upload-url/route'); const response = await POST(req({ kind: 'announcement', mime: 'image/jpeg', bytes: 12 })); expect(response.status).toBe(status); const payload = await response.json(); expect(payload.error.code).toBe(errorCode); expect(JSON.stringify(payload)).not.toContain('RAW_STORAGE_SECRET'); expect(state.sign).not.toHaveBeenCalled(); });
  it('signing failure soft-deletes registered asset and remains a storage refusal', async () => { state.sign.mockRejectedValue(new Error('RAW_STORAGE_SECRET')); const { POST } = await import('../api/media/upload-url/route'); const response = await POST(req({ kind: 'product', mime: 'image/jpeg', bytes: 12 })); expect(response.status).toBe(500); expect((await response.json()).error.code).toBe('storage_unavailable'); expect(state.calls.at(-1)).toMatchObject({ name: 'delete_media_asset', args: { p_asset_id: id } }); });
});
