import { beforeEach, describe, expect, it, vi } from 'vitest';
import { renderToStaticMarkup } from 'react-dom/server';
const state = vi.hoisted(() => ({ response: null as unknown, failed: false }));
const id = '72000000-0000-4000-8000-000000000001';
vi.mock('../../lib/identity-session', () => ({ requireAudience: async () => ({ identity: { kind: 'member', userId: id, tenantId: id, memberId: id }, supabase: { from: () => { const query = { select: () => query, eq: () => query, single: async () => ({ data: { name: 'Iron Box', timezone: 'Asia/Kolkata', business_type: 'gym' }, error: null }), maybeSingle: async () => ({ data: { name: 'Iron Box', timezone: 'Asia/Kolkata', business_type: 'gym' }, error: null }), then: (resolve: (value: unknown) => unknown) => Promise.resolve({ data: [{ name: 'Iron Box', timezone: 'Asia/Kolkata', business_type: 'gym' }], error: null }).then(resolve) }; return query; } } }) }));
vi.mock('../../lib/shop', () => ({ loadMemberShop: async () => { if (state.failed) throw new Error('private DB error'); return state.response; } }));
vi.mock('next/navigation', () => ({ useRouter: () => ({ refresh: () => {}, push: () => {} }), useSearchParams: () => new URLSearchParams(), redirect: (path: string) => { throw new Error(`redirect:${path}`); } }));
vi.mock('next/link', async () => { const { createElement } = await import('react'); return { default: (props: Record<string, unknown>) => createElement('a', props) }; });
const item = { itemId: id, section: 'products', name: 'Protein visible fixture', description: 'A tub of protein', pricePaise: '199900', currency: 'INR', gstRateBp: 1800, validityDays: 30, cancellationTerms: 'Ask the desk', quoteVersion: id, categoryId: null, categoryName: null, imageUrl: null, availability: 'available', availableQuantity: 2 };
beforeEach(() => { state.failed = false; state.response = { items: [], reservations: [], truncated: false, serverTime: '2026-10-02T04:30:00Z' }; });
async function render() { const { default: Page } = await import('../member/shop/page'); return renderToStaticMarkup(await Page({ searchParams: Promise.resolve({}) })); }
describe('SHP member page real entrypoint', () => {
  it('empty catalogue names the gym and gives an honest empty state', async () => expect(await render()).toContain("hasn&#x27;t added anything to the shop yet."));
  it('failed load renders retry instead of the empty-catalogue fallback', async () => { state.failed = true; const html = await render(); expect(html).toContain("couldn&#x27;t be loaded."); expect(html).toContain('Retry'); expect(html).not.toContain('private DB error'); expect(html).not.toContain('added anything'); });
  it('tile contains real name, price and availability without stock disclosure', async () => { state.response = { items: [item], reservations: [], truncated: false, serverTime: '2026-10-02T04:30:00Z' }; const html = await render(); expect(html).toContain('Protein visible fixture'); expect(html).toMatch(/Available|available/); expect(html).toMatch(/1,999|1999/); expect(html).not.toMatch(/only 2 left|2 in stock/i); });
  it.each([['reserved', 'Reserved'], ['expired', 'Expired'], ['fulfilled', 'Collected'], ['cancelled_by_member', 'Cancelled'], ['cancelled_by_gym', 'Cancelled by the gym']])('shows honest %s history state', async (status, word) => {
    state.response = { items: [], reservations: [{ reservationId: id, itemId: id, itemName: 'Snapshot protein name', section: 'products', quantity: 1, unitPricePaise: '199900', totalPaise: '199900', currency: 'INR', state: status, createdAt: '2026-10-02T04:30:00Z', expiresAt: '2026-10-03T04:30:00Z', cancelReason: status === 'cancelled_by_gym' ? 'Sold out at desk' : null, termsChanged: false, orderId: status === 'fulfilled' ? id : null, imageUrl: null }], truncated: false, serverTime: '2026-10-02T04:30:00Z' };
    const html = await render(); expect(html).toContain(word); expect(html).toContain('Snapshot protein name'); if (status === 'cancelled_by_gym') expect(html).toContain('Sold out at desk');
  });
  it('truncation notice is explicit and decorative image has empty alt', async () => { state.response = { items: [{ ...item, imageUrl: 'https://images.test/published/photo' }], reservations: [], truncated: true, serverTime: '2026-10-02T04:30:00Z' }; const html = await render(); expect(html).toContain('Showing the first 200 items.'); expect(html).toMatch(/alt=""/); });
});
