import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import { isValidElement, type ReactElement, type ReactNode } from 'react';
import type { Database } from '@gymloop/db';
import { shopProductDisplayRequestSchema } from '@gymloop/shared';

type PublicProps = Record<string, unknown>;
type NodeElement = ReactElement<PublicProps>;
type Stage = 'uploading' | 'verifying';
const fixture = vi.hoisted(() => ({ cells: [] as unknown[], position: 0, uploadCalls: [] as File[], stage: null as ((stage: Stage) => void) | null, resolveUpload: null as ((value: { assetId: string }) => void) | null, rejectUpload: null as ((error: Error) => void) | null, requests: [] as Array<{ url: string; method: string | undefined; body: unknown }>, resolveSave: null as (() => void) | null, waitSave: false, response: {} as unknown, preview: false }));
vi.mock('react', async original => { const real = await original<typeof import('react')>(); return { ...real,
  useState: <T,>(initial: T | (() => T)) => { const position = fixture.position++; if (!(position in fixture.cells)) fixture.cells[position] = typeof initial === 'function' ? (initial as () => T)() : initial; return [fixture.cells[position] as T, (value: T | ((previous: T) => T)) => { fixture.cells[position] = typeof value === 'function' ? (value as (previous: T) => T)(fixture.cells[position] as T) : value; }]; },
  useRef: <T,>(initial: T) => { const position = fixture.position++; if (!(position in fixture.cells)) fixture.cells[position] = { current: initial }; return fixture.cells[position]; }, useEffect: () => {}, useMemo: <T,>(factory: () => T) => factory(), useCallback: <T,>(callback: T) => callback };
});
vi.mock('next/navigation', () => ({ useRouter: () => ({ refresh: vi.fn(), push: vi.fn() }) }));
vi.mock('../preview-context', () => ({ usePreviewReadOnly: () => fixture.preview }));
vi.mock('../(console)/shop/image-upload', () => ({ uploadProductImage: (file: File, onStage?: (stage: Stage) => void) => { fixture.uploadCalls.push(file); fixture.stage = onStage ?? null; onStage?.('uploading'); return new Promise<{ assetId: string }>((resolve, reject) => { fixture.resolveUpload = resolve; fixture.rejectUpload = reject; }); } }));
const productId = '72000000-0000-4000-8000-000000000071';
const assetId = '72000000-0000-4000-8000-000000000072';
const product: Omit<Database['public']['Tables']['addon_products']['Row'], 'price_paise'> & { price_paise: string; heldQuantity: number | null; imageUrl: string | null; imageAssetId: string | null } = { id: productId, tenant_id: productId, name: 'Visible photo product', kind: 'product', price_paise: '10000', currency: 'INR', gst_rate_bp: 0, cancellation_terms: 'Ask the desk', category_id: null, created_at: '2026-10-03T00:00:00Z', updated_at: '2026-10-03T00:00:00Z', description: 'Visible test product', is_active: true, quote_version: productId, session_count: null, sort_order: 0, stock_quantity: 1, trainer_qualification: null, trainer_staff_id: null, validity_days: 30, heldQuantity: null, imageUrl: null, imageAssetId: null };
async function view(): Promise<ReactNode> { fixture.position = 0; const { ProductDisplayPanel } = await import('../(console)/shop/product-display-panel'); return ProductDisplayPanel({ product, categories: [] }); }
function elements(node: ReactNode): NodeElement[] { if (Array.isArray(node)) return node.flatMap(elements); if (!isValidElement<PublicProps>(node)) return []; if (typeof node.type === 'function') return [node, ...elements((node.type as (props: PublicProps) => ReactNode)(node.props))]; return [node, ...elements(node.props.children as ReactNode)]; }
function words(node: ReactNode): string { if (Array.isArray(node)) return node.map(words).join(' '); if (isValidElement<PublicProps>(node)) { if (typeof node.type === 'function') return words((node.type as (props: PublicProps) => ReactNode)(node.props)); return words(node.props.children as ReactNode); } return typeof node === 'string' || typeof node === 'number' ? String(node) : ''; }
async function choose(): Promise<void> { const open = elements(await view()).find(el => el.type === 'button' && /Photo and category/i.test(words(el))); await (open?.props.onClick as (() => unknown) | undefined)?.(); const file = new File(['visible image fixture'], 'visible-product.png', { type: 'image/png' }); const field = elements(await view()).find(el => el.type === 'input' && el.props.type === 'file'); expect(field).toBeDefined(); (field!.props.onChange as (event: { target: { files: File[] }; currentTarget: { files: File[] } }) => void)({ target: { files: [file] }, currentTarget: { files: [file] } }); }
async function order(value: string): Promise<void> { const field = elements(await view()).find(el => el.type === 'input' && el.props.type === 'number'); expect(field, 'Public display order input').toBeDefined(); (field!.props.onChange as (event: { target: { value: string }; currentTarget: { value: string } }) => void)({ target: { value }, currentTarget: { value } }); }
async function saveAction(): Promise<() => unknown> { const tree = await view(); const button = elements(tree).find(el => el.type === 'button' && /^(Save|Retry)$/i.test(words(el).trim())); expect(button, 'One public Save or Retry action').toBeDefined(); expect(button!.props.disabled).not.toBe(true); if (button!.props.onClick) return button!.props.onClick as () => unknown; const form = elements(tree).find(el => el.type === 'form'); expect(form).toBeDefined(); return () => (form!.props.onSubmit as (event: { preventDefault: () => void }) => unknown)({ preventDefault: () => {} }); }
function displayCommand(index = 0) { const request = fixture.requests[index]; expect(request?.url).toBe(`/api/shop/products/${productId}`); expect(request?.method).toBe('PATCH'); return shopProductDisplayRequestSchema.parse(request?.body); }
beforeEach(() => { fixture.cells = []; fixture.position = 0; fixture.uploadCalls = []; fixture.stage = null; fixture.resolveUpload = null; fixture.rejectUpload = null; fixture.requests = []; fixture.resolveSave = null; fixture.waitSave = false; fixture.preview = false; fixture.response = { ok: true, data: { productId } }; vi.stubGlobal('navigator', { onLine: true }); vi.stubGlobal('window', { addEventListener: vi.fn(), removeEventListener: vi.fn() }); vi.stubGlobal('fetch', async (url: string, init: RequestInit) => { fixture.requests.push({ url, method: init.method, body: JSON.parse(String(init.body)) as unknown }); if (fixture.waitSave) await new Promise<void>(resolve => { fixture.resolveSave = resolve; }); return new Response(JSON.stringify(fixture.response), { status: 200, headers: { 'Content-Type': 'application/json' } }); }); });
afterEach(() => vi.unstubAllGlobals());
describe('SHP-Q4 real product photo form sequence', () => {
  it('invalid order with a valid selected photo never PATCHes or reports false Saving', async () => { await choose(); await order('-1'); const save = await saveAction(); const pending = save(); await Promise.resolve(); await Promise.resolve(); if (fixture.uploadCalls.length) { fixture.stage?.('verifying'); fixture.resolveUpload?.({ assetId }); } await pending; expect(fixture.requests).toHaveLength(0); const copy = words(await view()); expect(copy).not.toMatch(/saving/i); expect(copy).toMatch(/order|invalid|valid|choose|try|error/i); });
  it('retained same-render Save twice runs exactly one upload and PATCH with truthful stages', async () => { await choose(); const activate = await saveAction(); const first = activate(); await vi.waitUntil(() => fixture.uploadCalls.length === 1); expect(words(await view())).toMatch(/uploading/i); const duplicate = activate(); await Promise.resolve(); expect(fixture.uploadCalls).toHaveLength(1); expect(fixture.requests).toHaveLength(0); fixture.stage?.('verifying'); expect(words(await view())).toMatch(/verifying/i); expect(words(await view())).not.toMatch(/saving/i); fixture.waitSave = true; fixture.resolveUpload?.({ assetId }); await vi.waitUntil(() => fixture.requests.length === 1); expect(words(await view())).toMatch(/saving/i); expect(displayCommand().imageAssetId).toBe(assetId); fixture.waitSave = false; fixture.resolveSave?.(); await first; await duplicate; expect(fixture.uploadCalls).toHaveLength(1); expect(fixture.requests).toHaveLength(1); expect(words(await view())).toMatch(/saved/i); expect(words(await view())).not.toMatch(/uploading|verifying|saving/i); });
  it('failed verification shows the refusal and never reports Saving or PATCH', async () => { await choose(); const pending = (await saveAction())(); await vi.waitUntil(() => fixture.uploadCalls.length === 1); fixture.stage?.('verifying'); fixture.rejectUpload?.(new Error('The photo could not be verified. Choose another photo and try again.')); await pending; const copy = words(await view()); expect(copy).toMatch(/could not be verified/i); expect(copy).not.toMatch(/saving/i); expect(fixture.requests).toHaveLength(0); });
  it('failed display save reuses its confirmed asset on the next deliberate Save', async () => { await choose(); fixture.response = { ok: false, error: { code: 'save_failed', message: 'The display could not be saved. Try again.' } }; const pending = (await saveAction())(); await vi.waitUntil(() => fixture.uploadCalls.length === 1); fixture.stage?.('verifying'); fixture.resolveUpload?.({ assetId }); await pending; expect(displayCommand().imageAssetId).toBe(assetId); expect(words(await view())).toMatch(/could not be saved|try again/i); expect(words(await view())).not.toMatch(/saving/i); fixture.response = { ok: true, data: { productId } }; const retry = (await saveAction())(); await Promise.resolve(); if (fixture.uploadCalls.length > 1) fixture.resolveUpload?.({ assetId }); await retry; expect(fixture.uploadCalls).toHaveLength(1); expect(displayCommand(1)).toEqual(displayCommand()); });
});
