'use client';
import { useState, type FormEvent } from 'react';
import { CLASS_LIMITS, DAYS_PER_WEEK, MS_PER_HOUR, MINUTES_PER_HOUR, formatDateTime, humanize, type BusinessNouns, type ClassTimetableSession } from '@gymloop/shared';
import { ClassCommandStatus, ClassConfirmation, useClassCommand } from '../../member/classes/class-actions';
import { deskTime } from '../../../lib/time';
import type { loadServices, loadClassRules, loadClassSettings } from '../../../lib/classes';
type Service = NonNullable<Awaited<ReturnType<typeof loadServices>>>[number];
type Rule = NonNullable<Awaited<ReturnType<typeof loadClassRules>>>[number];
type Branch = { id: string; name: string; timezone: string | null };
type Trainer = { id: string; full_name: string; branch_id: string | null };
const weekdays = ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'];
function value(form: FormData, key: string): string { return String(form.get(key) ?? ''); }
function number(form: FormData, key: string): number { return Number(value(form, key)); }
function TrainerField({ trainers, selected, nouns }: { trainers: Trainer[]; selected?: string | null; nouns: BusinessNouns }) { return <label>{humanize(nouns.trainer)}<select className="cl-input" name="trainerStaffId" defaultValue={selected ?? ''}><option value="">Unassigned</option>{trainers.map((row) => <option key={row.id} value={row.id}>{row.full_name}</option>)}</select></label>; }
export function ServiceEditor({ service, nouns }: { service?: Service; nouns: BusinessNouns }) {
  const command = useClassCommand();
  async function save(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); if (await command.send(service ? `/api/services/${service.id}` : '/api/services', { name: value(form, 'name'), description: value(form, 'description'), defaultDurationMinutes: number(form, 'duration'), defaultCapacity: number(form, 'capacity'), sortOrder: number(form, 'order') }, service ? 'PUT' : 'POST')) command.setMessage('Service saved. Existing rules and sessions retain their settings.'); }
  return <section className="cl-panel"><h2 className="cl-section-title">{service ? `Edit ${service.name}` : `Add a ${nouns.class}`}</h2><form className="class-editor" onSubmit={save}><fieldset disabled={command.disabled}><label>Name<input className="cl-input" name="name" required maxLength={CLASS_LIMITS.nameMax} defaultValue={service?.name} /></label><label>Description<textarea className="cl-input" name="description" maxLength={CLASS_LIMITS.descriptionMax} defaultValue={service?.description ?? ''} /></label><label>Default duration (minutes)<input className="cl-input" type="number" name="duration" required min={CLASS_LIMITS.durationMinMinutes} max={CLASS_LIMITS.durationMaxMinutes} defaultValue={service?.default_duration_minutes} /></label><label>Default capacity<input className="cl-input" type="number" name="capacity" required min={CLASS_LIMITS.capacityMin} max={CLASS_LIMITS.capacityMax} defaultValue={service?.default_capacity} /></label><label>Sort order<input className="cl-input" type="number" name="order" min={0} max={CLASS_LIMITS.sortOrderMax} defaultValue={service?.sort_order ?? 0} /></label><button className="cl-btn">Save service</button></fieldset></form><ClassCommandStatus command={command} />{service ? <><p>Disabling stops new bookings and generation. Existing bookings and sessions stand; disabling sends no cancellation notice.</p><button className="cl-btn cl-btn--quiet" disabled={command.disabled} onClick={async () => { const result = await command.send(`/api/services/${service.id}/active`, { isActive: !service.is_active }); if (result) command.setMessage(result.changed ? service.is_active ? 'Service disabled. Existing commitments remain.' : 'Service enabled. Missing sessions will be generated.' : 'The service state was already set.'); }}>{service.is_active ? 'Disable service' : 'Enable service'}</button></> : null}</section>;
}
export function ScheduleEditor({ services, branches, trainers, rule, nouns }: { services: Service[]; branches: Branch[]; trainers: Trainer[]; rule?: Rule; nouns: BusinessNouns }) {
  const command = useClassCommand();
  const [serviceId, setServiceId] = useState(rule?.service_id ?? services.find((row) => row.is_active)?.id ?? '');
  const service = services.find((row) => row.id === serviceId);
  async function save(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); const common = { durationMinutes: number(form, 'duration'), capacity: number(form, 'capacity'), trainerStaffId: value(form, 'trainerStaffId') || null, validUntil: value(form, 'validUntil') || null }; const body = rule ? { ...common, isActive: form.has('isActive') } : { ...common, trainerStaffId: common.trainerStaffId ?? undefined, validUntil: common.validUntil ?? undefined, serviceId, branchId: value(form, 'branchId'), weekdays: form.getAll('weekdays').map(Number), startTime: value(form, 'startTime'), validFrom: value(form, 'validFrom') || undefined }; const result = await command.send(rule ? `/api/class-rules/${rule.id}` : '/api/class-rules', body, rule ? 'PUT' : 'POST'); if (result) command.setMessage(rule ? `Created ${result.sessionsCreated}; updated ${result.sessionsUpdated}; removed ${result.sessionsRemoved}; kept ${result.sessionsKept} because of bookings.` : Array.isArray(result.rules) ? result.rules.map((r: { weekday: number; sessionsCreated: number }) => `${weekdays[r.weekday]}: ${r.sessionsCreated} sessions created`).join('. ') : 'The rule result was unavailable. Refresh the timetable.'); }
  return <section className="cl-panel"><h2 className="cl-section-title">{rule ? `Edit ${weekdays[rule.weekday]} rule` : 'Weekly timetable'}</h2><p>{rule ? 'This changes future scheduled sessions that have not been edited individually. To move a weekday, start time, service or branch, end this rule and create another. Booked commitments are kept.' : 'Choose the weekly days. Each occurrence starts on its branch-local day; a midnight end still belongs to its start day.'}</p><form className="class-editor" onSubmit={save}><fieldset disabled={command.disabled || !service}><label>Service<select className="cl-input" disabled={!!rule} value={serviceId} onChange={(event) => setServiceId(event.target.value)}>{services.filter((row) => row.is_active || row.id === rule?.service_id).map((row) => <option key={row.id} value={row.id}>{row.name}</option>)}</select></label>{rule ? <p>{weekdays[rule.weekday]} · {rule.start_time} · {branches.find((row) => row.id === rule.branch_id)?.name}</p> : <><label>Branch<select className="cl-input" name="branchId" required>{branches.map((row) => <option key={row.id} value={row.id}>{row.name} · {row.timezone ?? 'Organisation timezone'}</option>)}</select></label><fieldset><legend>Weekdays</legend>{Array.from({ length: DAYS_PER_WEEK }, (_, day) => <label key={day}><input type="checkbox" name="weekdays" value={day} />{weekdays[day]}</label>)}</fieldset><label>Local start time<input className="cl-input" type="time" name="startTime" required /></label><label>Valid from<input className="cl-input" type="date" name="validFrom" /></label></>}
    <label key={`duration:${serviceId}`}>Duration (minutes)<input className="cl-input" type="number" name="duration" min={CLASS_LIMITS.durationMinMinutes} max={CLASS_LIMITS.durationMaxMinutes} required defaultValue={rule?.duration_minutes ?? service?.default_duration_minutes} /></label><label key={`capacity:${serviceId}`}>Capacity<input className="cl-input" type="number" name="capacity" min={CLASS_LIMITS.capacityMin} max={CLASS_LIMITS.capacityMax} required defaultValue={rule?.capacity ?? service?.default_capacity} /></label><TrainerField trainers={trainers} selected={rule?.trainer_staff_id ?? null} nouns={nouns} /><label>Valid until (inclusive)<input className="cl-input" type="date" name="validUntil" defaultValue={rule?.valid_until ?? ''} /></label>{rule ? <label><input type="checkbox" name="isActive" defaultChecked={rule.is_active} />Active rule</label> : null}<button className="cl-btn">{rule ? 'Save rule' : 'Create weekly rules'}</button></fieldset></form><ClassCommandStatus command={command} /></section>;
}
export function SessionEditor({ services, branches, trainers, session, bookingsToCancel, nouns }: { services: Service[]; branches: Branch[]; trainers: Trainer[]; session?: ClassTimetableSession; bookingsToCancel?: number; nouns: BusinessNouns }) {
  const command = useClassCommand(); const [serviceId, setServiceId] = useState(session?.serviceId ?? services.find((row) => row.is_active)?.id ?? ''); const service = services.find((row) => row.id === serviceId); const [cancel, setCancel] = useState(false); const [reason, setReason] = useState('');
  const local = session ? deskTime(session.startsAt, session.timezone).split(' ') : null;
  async function save(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); const common = { sessionDate: session?.ruleId ? session.sessionDate : value(form, 'date'), startTime: value(form, 'time'), durationMinutes: number(form, 'duration'), capacity: number(form, 'capacity'), trainerStaffId: value(form, 'trainerStaffId') || null }; const result = await command.send(session ? `/api/class-sessions/${session.sessionId}` : '/api/class-sessions', session ? common : { ...common, trainerStaffId: common.trainerStaffId ?? undefined, serviceId, branchId: value(form, 'branchId') }, session ? 'PUT' : 'POST'); if (result) command.setMessage('Session saved. This occurrence is separate from future weekly edits.'); }
  return <section className="cl-panel"><h2 className="cl-section-title">{session ? 'Edit this occurrence' : 'One-off session'}</h2><p>{session ? 'Capacity and trainer can change. Holding bookings prevent changes to date, time or duration. A cancelled occurrence stays cancelled.' : 'One session on a chosen local date, including a holiday. Membership covers booking.'}</p><form className="class-editor" onSubmit={save}><fieldset disabled={command.disabled || !service || session?.sessionStatus === 'cancelled'}>{!session ? <><label>Service<select className="cl-input" value={serviceId} onChange={(event) => setServiceId(event.target.value)}>{services.filter((row) => row.is_active).map((row) => <option key={row.id} value={row.id}>{row.name}</option>)}</select></label><label>Branch<select className="cl-input" name="branchId" required>{branches.map((row) => <option key={row.id} value={row.id}>{row.name} · {row.timezone ?? 'Organisation timezone'}</option>)}</select></label></> : null}<label>Local date<input className="cl-input" type="date" name="date" required disabled={!!session?.ruleId} defaultValue={local?.[0]} /></label><label>Local start time<input className="cl-input" type="time" name="time" required defaultValue={local?.[1]} /></label><label key={`duration:${serviceId}`}>Duration (minutes)<input className="cl-input" type="number" name="duration" required min={CLASS_LIMITS.durationMinMinutes} max={CLASS_LIMITS.durationMaxMinutes} defaultValue={session ? (Date.parse(session.endsAt) - Date.parse(session.startsAt)) / (MS_PER_HOUR / MINUTES_PER_HOUR) : service?.default_duration_minutes} /></label><label key={`capacity:${serviceId}`}>Capacity<input className="cl-input" type="number" name="capacity" required min={CLASS_LIMITS.capacityMin} max={CLASS_LIMITS.capacityMax} defaultValue={session?.capacity ?? service?.default_capacity} /></label><TrainerField trainers={trainers} selected={session?.trainerStaffId ?? null} nouns={nouns} /><button className="cl-btn">Save session</button></fieldset></form><ClassCommandStatus command={command} />{session?.sessionStatus === 'scheduled' ? <button className="cl-btn cl-btn--quiet" disabled={command.disabled} onClick={() => setCancel(true)}>Cancel session</button> : null}
    <ClassConfirmation open={cancel} close={() => setCancel(false)} title="Cancel this session?"><p>{session?.serviceName}{session ? ` · ${formatDateTime(session.startsAt, session.timezone)}` : ''}</p><p>{bookingsToCancel} booked members will have their bookings cancelled. Eligible linked members receive an in-app notice. Members without the app need a call. The result will give the exact counts.</p><label>Reason shown in the notice<textarea className="cl-input" required minLength={CLASS_LIMITS.reasonMin} maxLength={CLASS_LIMITS.reasonMax} value={reason} onChange={(event) => setReason(event.target.value)} /></label><ClassCommandStatus command={command} /><button className="cl-btn" disabled={command.disabled || reason.trim().length < CLASS_LIMITS.reasonMin} onClick={async () => { if (!session) return; const result = await command.send(`/api/class-sessions/${session.sessionId}/cancel`, { reason }); if (result) { setCancel(false); command.setMessage(`${result.bookingsCancelled} bookings cancelled; ${result.noticesWritten} in-app notices written; ${result.noticesWithheld} withheld; ${result.membersWithoutApp} members without an app need a phone call.`); } }}>Confirm session cancellation</button><button className="cl-btn cl-btn--quiet" onClick={() => setCancel(false)}>Keep session</button></ClassConfirmation>
  </section>;
}
export function ClassSettingsEditor({ settings }: { settings: NonNullable<Awaited<ReturnType<typeof loadClassSettings>>> }) {
 const command = useClassCommand(); return <section className="cl-panel"><h2 className="cl-section-title">Booking settings</h2><p>A window change applies to cancellations immediately. Review the hours before saving.</p><form className="class-editor" onSubmit={async (event) => { event.preventDefault(); const form = new FormData(event.currentTarget); const result = await command.send('/api/class-settings', { cancelWindowHours: number(form, 'hours'), allowCrossBranch: form.has('cross') }, 'PUT'); if (result) command.setMessage(`Cancellation window: ${result.cancelWindowHours} hours. Cross-branch booking ${result.allowCrossBranch ? 'allowed' : 'disabled'}.`); }}><fieldset disabled={command.disabled}><label>Free-cancel window (hours)<input className="cl-input" type="number" name="hours" min={0} max={CLASS_LIMITS.cancelWindowMaxHours} defaultValue={settings.class_cancel_window_hours} required /></label><label><input type="checkbox" name="cross" defaultChecked={settings.class_allow_cross_branch} />Allow booking across branches</label><button className="cl-btn">Save booking settings</button></fieldset></form><ClassCommandStatus command={command} /></section>;
}
