import { beforeEach, describe, expect, it, vi } from 'vitest';
import type { Session } from '@supabase/supabase-js';
import type { GymloopIdentity } from '@gymloop/shared';
import { MobileProvider, useMobile } from '../mobile-context';
import { nativeShopCache, readShopCache, shopCacheCurrent, writeShopCache } from '../shop-cache';
import { loadAnnouncementCache, saveAnnouncementCache } from '../announcements';

const h = vi.hoisted(() => ({ slots: [] as unknown[], cursor: 0, effects: [] as Array<() => void | (() => void)>, cleanups: [] as Array<() => void>, context: undefined as unknown, listener: undefined as undefined | ((event: string, session: Session | null) => void), session: null as Session | null, tokenPause: null as null | Promise<void>, resolutions: [] as Array<{ identity: GymloopIdentity; wait?: Promise<void> }>, storage: new Map<string, string>(), removalFailure: false, logout: vi.fn(), fetch: vi.fn() }));
vi.mock('react', async (original) => {
  const actual = await original<typeof import('react')>();
  return { ...actual, createContext: () => ({ Provider: 'provider' }), useContext: () => h.context,
    useState: (initial: unknown) => { const index = h.cursor++; if (!(index in h.slots)) h.slots[index] = typeof initial === 'function' ? (initial as () => unknown)() : initial; return [h.slots[index], (value: unknown) => { h.slots[index] = typeof value === 'function' ? (value as (old: unknown) => unknown)(h.slots[index]) : value; }]; },
    useRef: (initial: unknown) => { const index = h.cursor++; if (!(index in h.slots)) h.slots[index] = { current: initial }; return h.slots[index]; },
    useMemo: (factory: () => unknown, dependencies: unknown[]) => { const index = h.cursor++; const previous = h.slots[index] as { dependencies: unknown[]; value: unknown } | undefined; if (!previous || dependencies.some((value, i) => value !== previous.dependencies[i])) h.slots[index] = { dependencies, value: factory() }; return (h.slots[index] as { value: unknown }).value; },
    useCallback: (callback: unknown, dependencies: unknown[]) => { const index = h.cursor++; const previous = h.slots[index] as { dependencies: unknown[]; value: unknown } | undefined; if (!previous || dependencies.some((value, i) => value !== previous.dependencies[i])) h.slots[index] = { dependencies, value: callback }; return (h.slots[index] as { value: unknown }).value; }, useEffect: (effect: () => void | (() => void), dependencies: unknown[]) => { const index = h.cursor++; const previous = h.slots[index] as unknown[] | undefined; if (!previous || dependencies.some((value, i) => value !== previous[i])) { h.slots[index] = dependencies; h.effects.push(effect); } },
  };
});
vi.mock('@expo-google-fonts/archivo', () => ({ useFonts: () => [true, null], Archivo_400Regular: 1, Archivo_500Medium: 1, Archivo_600SemiBold: 1, Archivo_700Bold: 1 }));
vi.mock('../../assets/fonts/ArchivoExtraCondensed-ExtraBold.ttf', () => ({ default: 1 }));
vi.mock('../../assets/fonts/ArchivoExtraCondensed-Bold.ttf', () => ({ default: 1 }));
vi.mock('expo-splash-screen', () => ({ preventAutoHideAsync: vi.fn(async () => undefined), hideAsync: vi.fn(async () => undefined) }));
vi.mock('react-native', () => ({ StatusBar: 'statusbar', useColorScheme: () => 'light', AppState: { addEventListener: () => ({ remove: vi.fn() }) } }));
vi.mock('@gymloop/shared', async (original) => ({ ...await original<typeof import('@gymloop/shared')>(), mobileClientEnv: () => ({ EXPO_PUBLIC_SUPABASE_URL: 'https://supabase.example.com', EXPO_PUBLIC_SUPABASE_ANON_KEY: 'public-placeholder', EXPO_PUBLIC_API_BASE_URL: 'https://api.example.com', EXPO_PUBLIC_WEB_URL: 'https://web.example.com' }) }));
vi.mock('expo-secure-store', () => ({ getItemAsync: async (key: string) => h.storage.get(key) ?? null, setItemAsync: async (key: string, value: string) => { h.storage.set(key, value); }, deleteItemAsync: async (key: string) => { if (h.removalFailure) throw new Error('Storage unavailable'); h.storage.delete(key); } }));
vi.mock('../offline-check-in', () => ({ clearOfflineCheckIns: vi.fn(async () => undefined) }));
vi.mock('../native-session', () => ({ createMobileSupabase: () => ({ from: () => ({ select: () => ({ eq: () => ({ maybeSingle: async () => ({ data: { business_type: 'gym' }, error: null }) }) }) }), auth: { getSession: async () => { await h.tokenPause; return { data: { session: h.session }, error: null }; }, onAuthStateChange: (callback: typeof h.listener) => { h.listener = callback; return { data: { subscription: { unsubscribe: vi.fn() } } }; }, signOut: h.logout } }), resolveNativeMobileSession: async () => { const next = h.resolutions.shift(); if (!next) throw new Error('Missing independent session fixture'); await next.wait; return { identity: next.identity, queueScope: next.identity.kind === 'member' ? next.identity : null, replay: 'ready' }; }, signOutMobile: async () => { await h.logout(); } }));
const owner: Extract<GymloopIdentity, { kind: 'member' }> = { kind: 'member', userId: '20000000-0000-4000-8000-000000000001', tenantId: '10000000-0000-4000-8000-000000000001', memberId: '30000000-0000-4000-8000-000000000001' };
const other: Extract<GymloopIdentity, { kind: 'member' }> = { ...owner, userId: '20000000-0000-4000-8000-000000000002', tenantId: '10000000-0000-4000-8000-000000000002', memberId: '30000000-0000-4000-8000-000000000002' };
function session(token: string): Session { return { access_token: token, refresh_token: 'refresh', expires_in: 1, token_type: 'bearer', user: { id: owner.userId, app_metadata: {}, user_metadata: {}, aud: 'authenticated', created_at: '2026-10-03T00:00:00Z' } }; }
function deferred() { let resolve!: () => void; const promise = new Promise<void>((done) => { resolve = done; }); return { promise, resolve }; }
function render() { h.cursor = 0; const element = MobileProvider({ children: null }); if (element) h.context = element.props.value; for (const effect of h.effects.splice(0)) { const cleanup = effect(); if (cleanup) h.cleanups.push(cleanup); } return h.context ? useMobile() : undefined as unknown as ReturnType<typeof useMobile>; }
async function settle() { for (const ignored of Array.from({ length: 30 })) { void ignored; await Promise.resolve(); render(); } return render(); }
async function start(identity: GymloopIdentity = owner) { h.session = session('jwt-A'); h.resolutions.push({ identity }); render(); return settle(); }
async function seed() { await writeShopCache(nativeShopCache, owner.memberId, { items: [], reservations: [], truncated: false, serverTime: '2026-10-03T00:00:00Z' }); await saveAnnouncementCache({ scope: owner, fetchedAt: '2026-10-03T00:00:00Z', announcements: [], pendingReads: [] }); }
function replace(identity: GymloopIdentity, wait?: Promise<void>) { h.session = session('jwt-B'); h.resolutions.push(wait ? { identity, wait } : { identity }); h.listener?.('SIGNED_IN', h.session); }
describe('actual native provider current caller and private cache boundary', () => {
  beforeEach(() => { h.slots = []; h.cursor = 0; h.effects = []; h.cleanups = []; h.context = undefined; h.listener = undefined; h.session = null; h.tokenPause = null; h.resolutions = []; h.storage.clear(); h.removalFailure = false; h.logout.mockReset().mockResolvedValue(undefined); h.fetch.mockReset().mockResolvedValue({ json: async () => ({ ok: true, data: {} }) }); vi.stubGlobal('fetch', h.fetch); });
  it('Auth replacement immediately revokes retained API and Shop lease before ownership resolves', async () => { const old = await start(); await seed(); const lease = shopCacheCurrent(nativeShopCache); const wait = deferred(); replace(other, wait.promise); expect(lease()).toBe(false); await old.api.post('/api/probe', {}).catch(() => undefined); expect(h.fetch).not.toHaveBeenCalled(); wait.resolve(); const current = await settle(); expect(current.identity).toEqual(other); expect(await readShopCache(nativeShopCache, owner.memberId)).toBeNull(); expect(await loadAnnouncementCache(owner)).toBeNull(); await current.api.post('/api/probe', {}); expect(h.fetch).toHaveBeenCalled(); });
  it('different verified ownership publishes only after old Shop and announcement caches are empty', async () => { await start(); await seed(); replace(other); const current = await settle(); expect(current.identity).toEqual(other); expect(await readShopCache(nativeShopCache, owner.memberId)).toBeNull(); expect(await loadAnnouncementCache(owner)).toBeNull(); });
  it('successful signout synchronously revokes preceding cache lease and removes private caches', async () => { const current = await start(); await seed(); const lease = shopCacheCurrent(nativeShopCache); const signingOut = current.signOut(); expect(lease()).toBe(false); await signingOut; expect(await loadAnnouncementCache(owner)).toBeNull(); });
  it('deferred token acquisition never lets old capability transmit replacement JWT', async () => { const old = await start(); const token = deferred(); h.tokenPause = token.promise; const pending = old.api.post('/api/probe', {}).catch(() => undefined); replace(other); token.resolve(); await pending; await settle(); expect(h.fetch).not.toHaveBeenCalled(); });
  it('A to B to A does not resurrect a retained A capability', async () => { const old = await start(); replace(other); await settle(); replace(owner); await settle(); await old.api.post('/api/probe', {}).catch(() => undefined); expect(h.fetch).not.toHaveBeenCalled(); });
  it('unresolved ownership revokes earlier work and clears private caches', async () => { const old = await start(); await seed(); replace({ kind: 'unlinked' }); await settle(); await old.api.post('/api/probe', {}).catch(() => undefined); expect(h.fetch).not.toHaveBeenCalled(); expect(await loadAnnouncementCache(owner)).toBeNull(); });
  it('signout attempts Auth even when private storage cleanup fails', async () => { const old = await start(); await seed(); h.removalFailure = true; await old.signOut().catch(() => undefined); expect(h.logout).toHaveBeenCalled(); await old.api.post('/api/probe', {}).catch(() => undefined); expect(h.fetch).not.toHaveBeenCalled(); });
  it('cleanup failure blocks publication of another linked owner', async () => { await start(); await seed(); h.removalFailure = true; replace(other); const current = await settle(); expect(current.identity).not.toEqual(other); });
  it('unmount synchronously revokes retained transport and cache work', async () => { const old = await start(); const lease = shopCacheCurrent(nativeShopCache); for (const cleanup of h.cleanups) cleanup(); expect(lease()).toBe(false); await old.api.post('/api/probe', {}).catch(() => undefined); expect(h.fetch).not.toHaveBeenCalled(); });
  it('authenticated unlinked current caller retains invite recovery capability', async () => { const current = await start({ kind: 'unlinked' }); await current.api.post('/api/invites/accept', { token: 'invite-fixture' }); expect(h.fetch).toHaveBeenCalled(); });
});
