'use client';
import { useState } from 'react';
import { CLASS_LIMITS, MS_PER_HOUR, MINUTES_PER_HOUR, formatDateTime, humanize, type ClassTimetableSession, type ClassRosterBooking, type BusinessNouns } from '@gymloop/shared';
import { ClassCommandStatus, ClassConfirmation, useClassCommand } from '../../../member/classes/class-actions';
import { StatusWord } from '../../../status-word';
type SearchMember = { id: string; full_name: string; phone: string; status: string; erased_at: string | null };
export function RosterActions({ session, bookings, members, role, staffId, nouns }: { session: ClassTimetableSession; bookings: ClassRosterBooking[]; members: SearchMember[]; role: string; staffId: string | null; nouns: BusinessNouns }) {
  const command = useClassCommand();
  const [cancel, setCancel] = useState<string | null>(null);
  const [reason, setReason] = useState('');
  const [selected, setSelected] = useState<SearchMember | null>(null);
  const desk = ['gym_owner', 'gym_manager', 'front_desk'].includes(role);
  const open = session.sessionStatus === 'scheduled';
  const mayMark = open && (desk || (role === 'trainer' && session.trainerStaffId === staffId));
  const now = Date.now();
  const grace = Date.parse(session.endsAt) + CLASS_LIMITS.markGraceHours * MS_PER_HOUR;
  async function act(path: string, body: unknown, message: string) { if (await command.send(path, body)) command.setMessage(message); }
  return <section className="classes-workspace"><ClassCommandStatus command={command} />{!open ? <p className="cl-alert">Cancelled session. The roster is read-only.</p> : null}{open && role === 'trainer' && session.trainerStaffId !== staffId ? <p>Only the assigned {nouns.trainer} can mark this roster.</p> : null}{mayMark && now > grace ? <p>The marking window has closed. This roster is read-only for outcomes.</p> : null}{mayMark && now < Date.parse(session.startsAt) - CLASS_LIMITS.markLeadMinutes * MS_PER_HOUR / MINUTES_PER_HOUR ? <p>Attendance marking opens {formatDateTime(new Date(Date.parse(session.startsAt) - CLASS_LIMITS.markLeadMinutes * MS_PER_HOUR / MINUTES_PER_HOUR).toISOString(), session.timezone)}.</p> : null}{bookings.length === 0 ? <p className="cl-empty">Nobody is booked yet.</p> : <ul className="class-ledger">{bookings.map((row) => <li className="class-entry" key={row.bookingId}><div><h2 className="cl-row-title">{row.memberName || 'Name unavailable'}</h2><p>{row.memberCode} · {row.memberPhone ?? 'Phone unavailable'}</p><StatusWord status={row.status} label={row.status === 'booked' && Date.parse(session.startsAt) <= now ? 'Not marked' : humanize(row.status)} /><p>{row.membershipLive ? 'Current membership' : 'Membership not live'} · {row.hasApp ? 'App linked' : 'No app; contact by phone'}</p>{row.checkedInAt ? <p>Check-in: {formatDateTime(row.checkedInAt, session.timezone)}. Booking outcome is separate.</p> : <p>No check-in recorded for this day.</p>}</div><div className="class-actions">{mayMark && ['booked', 'attended', 'no_show'].includes(row.status) && now <= grace ? <>{now >= Date.parse(session.startsAt) - CLASS_LIMITS.markLeadMinutes * MS_PER_HOUR / MINUTES_PER_HOUR ? <button className="cl-btn" disabled={command.disabled} onClick={() => void act('/api/class-bookings/attendance', { bookingId: row.bookingId, status: 'attended' }, 'Marked attended.')}>Attended</button> : null}{now >= Date.parse(session.startsAt) ? <button className="cl-btn cl-btn--quiet" disabled={command.disabled} onClick={() => void act('/api/class-bookings/attendance', { bookingId: row.bookingId, status: 'no_show' }, 'Marked no-show.')}>No-show</button> : null}{row.status !== 'booked' ? <button className="cl-btn cl-btn--quiet" disabled={command.disabled} onClick={() => void act('/api/class-bookings/attendance', { bookingId: row.bookingId, status: 'booked' }, 'Mark undone. Booking retained.')}>Undo mark</button> : null}</> : null}{desk && open && row.status === 'booked' && now < Date.parse(session.endsAt) ? <button className="cl-btn cl-btn--quiet" disabled={command.disabled} onClick={() => { setReason(''); setCancel(row.bookingId); }}>Cancel booking</button> : null}</div></li>)}</ul>}
    {desk && open && now < Date.parse(session.endsAt) ? <section><h2 className="cl-section-title">Add a {nouns.member}</h2><form><label>Search phone<input className="cl-input" type="search" name="q" /></label><button className="cl-btn">Search</button></form><ul className="class-ledger">{members.map((row) => <li className="class-entry" key={row.id}><span>{row.full_name} · {row.phone}</span><button className="cl-btn" disabled={command.disabled || row.erased_at !== null || ['blocked', 'cancelled'].includes(row.status)} onClick={() => setSelected(row)}>Add</button></li>)}</ul></section> : null}
    <ClassConfirmation open={selected !== null} close={() => setSelected(null)} title={`Add ${selected?.full_name ?? nouns.member}?`}><p>{session.serviceName} · {session.spotsLeft} spots left</p><ClassCommandStatus command={command} /><button className="cl-btn" disabled={command.disabled} onClick={async () => { if (selected && await command.send('/api/class-bookings/desk', { sessionId: session.sessionId, memberId: selected.id })) { setSelected(null); command.setMessage('Booking confirmed.'); } }}>Confirm booking</button><button className="cl-btn cl-btn--quiet" onClick={() => setSelected(null)}>Back</button></ClassConfirmation>
    <ClassConfirmation open={cancel !== null} close={() => setCancel(null)} title="Cancel this booking?"><label>Reason<textarea className="cl-input" value={reason} onChange={(event) => setReason(event.target.value)} minLength={CLASS_LIMITS.reasonMin} maxLength={CLASS_LIMITS.reasonMax} /></label><ClassCommandStatus command={command} /><button className="cl-btn" disabled={command.disabled || reason.trim().length < CLASS_LIMITS.reasonMin} onClick={async () => { if (await command.send('/api/class-bookings/desk-cancel', { bookingId: cancel, reason })) { setCancel(null); command.setMessage('Booking cancelled.'); } }}>Confirm cancellation</button><button className="cl-btn cl-btn--quiet" onClick={() => setCancel(null)}>Back</button></ClassConfirmation>
  </section>;
}
